/*
* This header is generated by classdump-dyld 1.0
* on Wednesday, June 6, 2018 at 1:27:44 PM China Standard Time
* Operating System: Version 8.2 (Build 12D508)
* Image Source: /private/var/db/stash/_.8k0vmU/Applications/Compass.app/Compass
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos.
*/

#import <Compass/Compass-Structs.h>
#import <UIKit/UIViewController.h>
#import <Compass/CompassPage.h>

@class CompassView, CalibrationViewController, CompassCopyableLabel, UILabel, CLLocation, CMMotionManager, NSTimer, NSMutableDictionary, CLLocationManager, NSString;

@interface CompassPageViewController : UIViewController <CompassPage> {

	CompassView* _compassView;
	CalibrationViewController* _calibrationController;
	CompassCopyableLabel* _coordinatesLabel;
	UILabel* _altitudeLabel;
	UILabel* _directionLabel;
	UILabel* _lowDirectionLabel;
	UILabel* _degreesLabel;
	UILabel* _centeredDegreesLabel;
	UILabel* _primaryPlaceLabel;
	UILabel* _secondaryPlaceLabel;
	CLLocation* _userLocation;
	double _currentCompassAngle;
	BOOL _recentlyCalibrated;
	BOOL _dismissingCalibrationController;
	CMMotionManager* _manager;
	long long _currentDisplayHeading;
	double _headingFilter;
	NSTimer* _compassIdleTimer;
	NSMutableDictionary* _formattedDegreeText;
	BOOL _usesTrueNorth;
	CLLocationManager* _sharedLocationManager;
	BOOL _showCalibration;
	BOOL _timeoutDisabled;
	BOOL _calibrationDisabled;
	BOOL _shouldCompleteTics;
	UILabel* _consoleLabel;

}

@property (nonatomic,retain) CLLocation * userLocation; 
@property (nonatomic,readonly) BOOL isShowingCalibration; 
@property (readonly) unsigned long long hash; 
@property (readonly) Class superclass; 
@property (copy,readonly) NSString * description; 
@property (copy,readonly) NSString * debugDescription; 
+(void)initialize;
-(void)_enableIdleTimer;
-(void)setSharedLocationManager:(id)arg1 ;
-(BOOL)isShowingCalibration;
-(void)dismissCalibration;
-(void)showCalibration;
-(void)updateConsole;
-(void)_openMaps;
-(void)startMotionManager;
-(void)_updatePlaceLabels;
-(void)displayCalibrationViewIfNecessary;
-(void)hideCalibrationViewIfNecessary;
-(void)setCompassToAngle:(double)arg1 ;
-(void)setCrosshairLevelForData:(SCD_Struct_Co0)arg1 ;
-(void)_updateHeadingLabels;
-(void)_geocodeIfNecessaryForTime:(double)arg1 distance:(double)arg2 ;
-(id)calibrationController;
-(void)_updateDegreesLabel;
-(void)_updateDirectionLabel;
-(void)_updatePlaceLabelLayout;
-(void)_updateCoordinateLabel;
-(void)userDefaultsChanged:(id)arg1 ;
-(void)addConstraints;
-(void)updateDisplay:(id)arg1 ;
-(CLLocation *)userLocation;
-(void)dealloc;
-(id)init;
-(long long)preferredStatusBarStyle;
-(void)viewWillAppear:(BOOL)arg1 ;
-(void)viewDidLoad;
-(void)viewDidDisappear:(BOOL)arg1 ;
-(void)setUserLocation:(CLLocation *)arg1 ;
@end

