/*
* This header is generated by classdump-dyld 1.0
* on Tuesday, June 5, 2018 at 10:50:08 PM China Standard Time
* Operating System: Version 8.2 (Build 12D508)
* Image Source: /private/var/db/stash/_.8k0vmU/Applications/MobileSafari.app/MobileSafari
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos.
*/

#import <MobileSafari/MobileSafari-Structs.h>
#import <UIKit/UIActivityItemProvider.h>

@class NSURL, NSString;

@interface ActionPanelActivityItemProvider : UIActivityItemProvider {

	NSURL* _url;
	NSString* _pageTitle;

}

@property (nonatomic,retain) NSURL * url;                     //@synthesize url=_url - In the implementation block
@property (nonatomic,copy) NSString * pageTitle;              //@synthesize pageTitle=_pageTitle - In the implementation block
-(id)initWithURL:(id)arg1 pageTitle:(id)arg2 ;
-(NSURL *)url;
-(id)item;
-(void)setUrl:(NSURL *)arg1 ;
-(id)activityViewControllerPlaceholderItem:(id)arg1 ;
-(id)activityViewController:(id)arg1 itemForActivityType:(id)arg2 ;
-(NSString *)pageTitle;
-(id)activityViewController:(id)arg1 subjectForActivityType:(id)arg2 ;
-(id)activityViewController:(id)arg1 thumbnailImageForActivityType:(id)arg2 suggestedSize:(CGSize)arg3 ;
-(void)setPageTitle:(NSString *)arg1 ;
@end

