/*
* This header is generated by classdump-dyld 1.0
* on Tuesday, June 5, 2018 at 10:50:08 PM China Standard Time
* Operating System: Version 8.2 (Build 12D508)
* Image Source: /private/var/db/stash/_.8k0vmU/Applications/MobileSafari.app/MobileSafari
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos.
*/

#import <UIKit/UIActivity.h>
#import <MobileSafari/SingleBookmarkNavigationControllerDelegate.h>

@class SingleBookmarkNavigationController;

@interface AddBookmarkUIActivity : UIActivity <SingleBookmarkNavigationControllerDelegate> {

	SingleBookmarkNavigationController* _bookmarkNavController;

}
-(void)addBookmarkNavController:(id)arg1 didFinishWithResult:(BOOL)arg2 ;
-(id)parentBookmark;
-(id)aggregateDKey;
-(id)activityType;
-(id)activityTitle;
-(void)activityDidFinish:(BOOL)arg1 ;
-(BOOL)canPerformWithActivityItems:(id)arg1 ;
-(id)activityImage;
-(id)activityViewController;
-(void)prepareWithActivityItems:(id)arg1 ;
-(id)_beforeActivity;
-(id)_embeddedActivityViewController;
@end

