/*
* This header is generated by classdump-dyld 1.0
* on Tuesday, June 5, 2018 at 10:50:08 PM China Standard Time
* Operating System: Version 8.2 (Build 12D508)
* Image Source: /private/var/db/stash/_.8k0vmU/Applications/MobileSafari.app/MobileSafari
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos.
*/


@class WebBookmark, WBSCloudTab, NSURL, WBSAutomaticReadingListItem;

@interface NavigationDestination : NSObject {

	unsigned long long _type;
	WebBookmark* _bookmark;
	WBSCloudTab* _cloudTab;
	NSURL* _URL;
	WBSAutomaticReadingListItem* _automaticReadingListItem;

}

@property (nonatomic,readonly) unsigned long long type;                                           //@synthesize type=_type - In the implementation block
@property (nonatomic,retain) WebBookmark * bookmark;                                              //@synthesize bookmark=_bookmark - In the implementation block
@property (nonatomic,retain) WBSCloudTab * cloudTab;                                              //@synthesize cloudTab=_cloudTab - In the implementation block
@property (nonatomic,retain) NSURL * URL;                                                         //@synthesize URL=_URL - In the implementation block
@property (nonatomic,retain) WBSAutomaticReadingListItem * automaticReadingListItem;              //@synthesize automaticReadingListItem=_automaticReadingListItem - In the implementation block
+(id)navigationDestinationWithBookmark:(id)arg1 ;
+(id)navigationDestinationWithCloudTab:(id)arg1 ;
+(id)navigationDestinationWithHistoryURL:(id)arg1 ;
+(id)navigationDestinationWithAutomaticReadingListItem:(id)arg1 ;
+(id)navigationDestinationWithSocialProfileURL:(id)arg1 ;
-(WBSAutomaticReadingListItem *)automaticReadingListItem;
-(WBSCloudTab *)cloudTab;
-(void)setCloudTab:(WBSCloudTab *)arg1 ;
-(void)setAutomaticReadingListItem:(WBSAutomaticReadingListItem *)arg1 ;
-(id)description;
-(unsigned long long)type;
-(NSURL *)URL;
-(void)setURL:(NSURL *)arg1 ;
-(WebBookmark *)bookmark;
-(id)_initWithType:(unsigned long long)arg1 ;
-(void)setBookmark:(WebBookmark *)arg1 ;
@end

