/*
* This header is generated by classdump-dyld 1.0
* on Tuesday, June 5, 2018 at 10:50:08 PM China Standard Time
* Operating System: Version 8.2 (Build 12D508)
* Image Source: /private/var/db/stash/_.8k0vmU/Applications/MobileSafari.app/MobileSafari
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos.
*/


@class TabDocumentWK2, _WKRemoteObjectInterface;

@interface PageLoadTestWK2 : NSObject {

	TabDocumentWK2* _tabDocument;
	_WKRemoteObjectInterface* _eventsListenerInterface;

}
-(id)initWithTabDocument:(id)arg1 ;
-(void)_setUpPageLoadTestEventsListener;
-(void)_enablePageLoadMeasurementCollection;
-(void)didFinishPageLoadWithLoadData:(id)arg1 ;
-(void)dealloc;
@end

