/*
* This header is generated by classdump-dyld 1.0
* on Tuesday, June 5, 2018 at 10:50:08 PM China Standard Time
* Operating System: Version 8.2 (Build 12D508)
* Image Source: /private/var/db/stash/_.8k0vmU/Applications/MobileSafari.app/MobileSafari
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos.
*/

#import <MobileSafari/MobileSafari-Structs.h>
#import <UIKit/UIViewController.h>
#import <MobileSafari/BookmarksPanelStateRestoring.h>
#import <MobileSafari/BookmarksToolbarItemProvider.h>
#import <UIKit/UITableViewDelegate.h>
#import <UIKit/UITableViewDataSource.h>
#import <MobileSafari/WebBookmarksClientDelegateProtocol.h>

@protocol ReadingListViewControllerDelegate;
@class UITableView, UIBarButtonItem, WebBookmarkCollection, WebBookmarkList, SafariFetcherServerProxy, NSString, _UIContentUnavailableView, NSTimer;

@interface ReadingListViewController : UIViewController <BookmarksPanelStateRestoring, BookmarksToolbarItemProvider, UITableViewDelegate, UITableViewDataSource, WebBookmarksClientDelegateProtocol> {

	UITableView* _tableView;
	UIBarButtonItem* _unreadFilterButton;
	WebBookmarkCollection* _collection;
	BOOL _networkIsReachable;
	WebBookmarkList* _readingList;
	SafariFetcherServerProxy* _safariFetcherServerProxy;
	NSString* _archivingBookmarkUUID;
	_UIContentUnavailableView* _explanationView;
	NSTimer* _deletionNotificationTimer;
	BOOL _loadIconsSynchronously;
	BOOL _showingAllBookmarks;
	id<ReadingListViewControllerDelegate> _delegate;

}

@property (nonatomic,readonly) BOOL showingAllBookmarks;                                         //@synthesize showingAllBookmarks=_showingAllBookmarks - In the implementation block
@property (assign,nonatomic,__weak) id<ReadingListViewControllerDelegate> delegate;              //@synthesize delegate=_delegate - In the implementation block
@property (readonly) unsigned long long hash; 
@property (readonly) Class superclass; 
@property (copy,readonly) NSString * description; 
@property (copy,readonly) NSString * debugDescription; 
@property (nonatomic,readonly) NSString * collectionType; 
-(id)currentStateDictionary;
-(BOOL)restoreStateWithDictionary:(id)arg1 ;
-(double)currentScrollPosition;
-(void)restoreScrollPosition:(double)arg1 ;
-(NSString *)collectionType;
-(id)bookmarksRightBarButtonItem;
-(id)bookmarksNavigationController;
-(id)_bookmarkAtIndexPath:(id)arg1 ;
-(id)safari_tableViewScrollPositionSaveIdentifier;
-(void)_readingListBookmarkDidUpdate:(id)arg1 ;
-(void)_connectSafariFetcherServerProxy;
-(void)_disconnectSafariFetcherServerProxy;
-(void)_clearExplanationView;
-(void)_reloadReadingList;
-(id)_unreadFilterButtonTitle;
-(void)_didChangeUnreadFilter;
-(void)_showExplanationView;
-(void)_reloadReadingListAndTable;
-(void)didAddNewReadingListBookmark;
-(void)_scheduleDelayedChangeNotification;
-(void)_addReadingListItem;
-(void)didMarkBookmarkUnreadAtIndex:(unsigned long long)arg1 ;
-(id)safari_tableViewForScrollPositionSaving;
-(BOOL)showingAllBookmarks;
-(void)dealloc;
-(void)setDelegate:(id<ReadingListViewControllerDelegate>)arg1 ;
-(id)init;
-(void)tableView:(id)arg1 willDisplayCell:(id)arg2 forRowAtIndexPath:(id)arg3 ;
-(void)tableView:(id)arg1 didSelectRowAtIndexPath:(id)arg2 ;
-(void)scrollViewWillBeginDragging:(id)arg1 ;
-(long long)tableView:(id)arg1 numberOfRowsInSection:(long long)arg2 ;
-(id)tableView:(id)arg1 cellForRowAtIndexPath:(id)arg2 ;
-(long long)numberOfSectionsInTableView:(id)arg1 ;
-(void)tableView:(id)arg1 commitEditingStyle:(long long)arg2 forRowAtIndexPath:(id)arg3 ;
-(id<ReadingListViewControllerDelegate>)delegate;
-(void)viewWillLayoutSubviews;
-(CGSize)preferredContentSize;
-(void)loadView;
-(void)viewWillAppear:(BOOL)arg1 ;
-(void)viewDidAppear:(BOOL)arg1 ;
-(void)viewWillDisappear:(BOOL)arg1 ;
-(void)_webBookmarksDidReload:(id)arg1 ;
-(void)_contentSizeCategoryDidChange:(id)arg1 ;
-(void)_postChangeNotification;
-(void)_networkReachabilityChanged:(id)arg1 ;
-(void)bookmarksServerProxyConnectionInvalidated:(id)arg1 ;
-(void)bookmarksServerProxy:(id)arg1 didStartFetchingReadingListItem:(id)arg2 ;
-(void)bookmarksServerProxy:(id)arg1 didStopFetchingReadingListItem:(id)arg2 ;
-(void)bookmarksServerProxyDidFinishFetching:(id)arg1 ;
@end

