/*
* This header is generated by classdump-dyld 1.0
* on Tuesday, June 5, 2018 at 10:50:08 PM China Standard Time
* Operating System: Version 8.2 (Build 12D508)
* Image Source: /private/var/db/stash/_.8k0vmU/Applications/MobileSafari.app/MobileSafari
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos.
*/

#import <MobileSafari/MobileSafari-Structs.h>
#import <UIKit/UIPopoverController.h>

@class UIView;

@interface RotatablePopoverController : UIPopoverController {

	BOOL _supportsRotation;
	UIView* _presentationView;
	long long _buttonIdentifier;
	unsigned long long _permittedArrowDirections;
	CGRect _presentationRect;

}

@property (assign,nonatomic,__weak) id<RotatablePopoverControllerDelegate> delegate; 
@property (assign,nonatomic) CGRect presentationRect;                                             //@synthesize presentationRect=_presentationRect - In the implementation block
@property (nonatomic,retain) UIView * presentationView;                                           //@synthesize presentationView=_presentationView - In the implementation block
@property (assign,nonatomic) long long buttonIdentifier;                                          //@synthesize buttonIdentifier=_buttonIdentifier - In the implementation block
@property (assign,nonatomic) unsigned long long permittedArrowDirections;                         //@synthesize permittedArrowDirections=_permittedArrowDirections - In the implementation block
@property (assign,nonatomic) BOOL supportsRotation;                                               //@synthesize supportsRotation=_supportsRotation - In the implementation block
-(void)setPresentationRect:(CGRect)arg1 ;
-(void)setPresentationView:(UIView *)arg1 ;
-(void)setSupportsRotation:(BOOL)arg1 ;
-(void)setButtonIdentifier:(long long)arg1 ;
-(BOOL)supportsRotation;
-(void)presentPopoverFromBarButtonItem:(id)arg1 animated:(BOOL)arg2 ;
-(CGRect)presentationRect;
-(UIView *)presentationView;
-(void)setDelegate:(id<RotatablePopoverControllerDelegate>)arg1 ;
-(id<RotatablePopoverControllerDelegate>)delegate;
-(unsigned long long)permittedArrowDirections;
-(void)setPermittedArrowDirections:(unsigned long long)arg1 ;
-(id)initWithContentViewController:(id)arg1 ;
-(void)presentPopoverAnimated:(BOOL)arg1 ;
-(long long)buttonIdentifier;
@end

