/*
* This header is generated by classdump-dyld 1.0
* on Tuesday, June 5, 2018 at 10:50:08 PM China Standard Time
* Operating System: Version 8.2 (Build 12D508)
* Image Source: /private/var/db/stash/_.8k0vmU/Applications/MobileSafari.app/MobileSafari
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos.
*/


@interface SharedDataMigration : NSObject
+(id)_userCachesDirectoryPath;
+(BOOL)_migrateCacheFileFromSubpath:(id)arg1 toSubpath:(id)arg2 ensureIsDirectory:(BOOL)arg3 ;
+(void)migratePersistentStorageDefaults;
+(BOOL)migrateRecentSearches;
+(BOOL)migrateThumbnails;
@end

