/*
* This header is generated by classdump-dyld 1.0
* on Tuesday, June 5, 2018 at 10:50:08 PM China Standard Time
* Operating System: Version 8.2 (Build 12D508)
* Image Source: /private/var/db/stash/_.8k0vmU/Applications/MobileSafari.app/MobileSafari
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos.
*/


@protocol UniversalSearchFirstTimeExperienceViewDelegate <NSObject>
@required
-(id)iconImageNamesForFirstTimeExperienceView:(id)arg1;
-(id)descriptionTextForFirstTimeExperienceView:(id)arg1;
-(id)learnMoreTextForFirstTimeExperienceView:(id)arg1;
-(void)didTapLearnMoreLinkForFirstTimeExperienceView:(id)arg1;
-(void)didInteractWithUniversalSearchFirstTimeExperienceView:(id)arg1;

@end

