/*
* This header is generated by classdump-dyld 1.0
* on Tuesday, June 5, 2018 at 12:40:25 PM China Standard Time
* Operating System: Version 8.2 (Build 12D508)
* Image Source: /private/var/db/stash/_.8k0vmU/Applications/MobilePhone.app/MobilePhone
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos.
*/

@class NSString;


@protocol PHAudioPlayerDataSource <NSObject>
@property (readonly) NSString * audioFilePath; 
@property (readonly) BOOL fullFileAvailable; 
@property (readonly) double duration; 
@property (readonly) unsigned long long availableBytes; 
@property (readonly) unsigned long long expectedTotalBytes; 
@optional
-(unsigned long long)expectedTotalBytes;
-(double)duration;
-(unsigned long long)availableBytes;

@required
-(BOOL)fullFileAvailable;
-(NSString *)audioFilePath;

@end

