/*
* This header is generated by classdump-dyld 1.0
* on Tuesday, June 5, 2018 at 12:40:25 PM China Standard Time
* Operating System: Version 8.2 (Build 12D508)
* Image Source: /private/var/db/stash/_.8k0vmU/Applications/MobilePhone.app/MobilePhone
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos.
*/

#import <MobilePhone/MobilePhone-Structs.h>
#import <UIKit/UIView.h>
#import <MobilePhone/PHRecentsHeaderSummaryView.h>

@class UILabel;

@interface PHRecentsPhoneHeaderSummaryView : UIView <PHRecentsHeaderSummaryView> {

	UILabel* _topmostLabel;
	UILabel* _bottommostLabel;
	double _intrinsicContentHeight;

}

@property (assign) UILabel * topmostLabel;                     //@synthesize topmostLabel=_topmostLabel - In the implementation block
@property (assign) UILabel * bottommostLabel;                  //@synthesize bottommostLabel=_bottommostLabel - In the implementation block
@property (assign) double intrinsicContentHeight;              //@synthesize intrinsicContentHeight=_intrinsicContentHeight - In the implementation block
-(void)setTopmostLabel:(UILabel *)arg1 ;
-(void)setBottommostLabel:(UILabel *)arg1 ;
-(void)setIntrinsicContentHeight:(double)arg1 ;
-(UILabel *)topmostLabel;
-(UILabel *)bottommostLabel;
-(id)initWithFrame:(CGRect)arg1 recentCall:(id)arg2 occurrenceDate:(id)arg3 status:(unsigned)arg4 duration:(double)arg5 type:(unsigned)arg6 ;
-(double)intrinsicContentHeight;
-(CGSize)sizeThatFits:(CGSize)arg1 ;
-(CGSize)intrinsicContentSize;
@end

