/*
* This header is generated by classdump-dyld 1.0
* on Tuesday, June 5, 2018 at 12:40:25 PM China Standard Time
* Operating System: Version 8.2 (Build 12D508)
* Image Source: /private/var/db/stash/_.8k0vmU/Applications/MobilePhone.app/MobilePhone
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos.
*/

#import <MobilePhone/PHStarkGenericTableViewCell.h>

@class UILabel, UIDateLabel, NSLayoutConstraint, UIImageView;

@interface PHStarkRecentsTableViewCell : PHStarkGenericTableViewCell {

	UILabel* _nameLabel;
	UILabel* _phoneNumberTypeLabel;
	UIDateLabel* _dateLabel;
	NSLayoutConstraint* _nameLabelVerticalLayoutConstraint;
	UIImageView* _outgoingCallIconImageView;

}

@property (retain) UILabel * nameLabel;                                                 //@synthesize nameLabel=_nameLabel - In the implementation block
@property (retain) UILabel * phoneNumberTypeLabel;                                      //@synthesize phoneNumberTypeLabel=_phoneNumberTypeLabel - In the implementation block
@property (retain) UIDateLabel * dateLabel;                                             //@synthesize dateLabel=_dateLabel - In the implementation block
@property (retain) NSLayoutConstraint * nameLabelVerticalLayoutConstraint;              //@synthesize nameLabelVerticalLayoutConstraint=_nameLabelVerticalLayoutConstraint - In the implementation block
@property (retain) UIImageView * outgoingCallIconImageView;                             //@synthesize outgoingCallIconImageView=_outgoingCallIconImageView - In the implementation block
-(void)setRepresentedRecentCall:(id)arg1 ;
-(void)setPhoneNumberTypeLabel:(UILabel *)arg1 ;
-(UILabel *)phoneNumberTypeLabel;
-(void)setNameLabelVerticalLayoutConstraint:(NSLayoutConstraint *)arg1 ;
-(NSLayoutConstraint *)nameLabelVerticalLayoutConstraint;
-(UIImageView *)outgoingCallIconImageView;
-(void)setShowsOutgoingCallIcon:(BOOL)arg1 ;
-(void)setOutgoingCallIconImageView:(UIImageView *)arg1 ;
-(void)setDateLabel:(UIDateLabel *)arg1 ;
-(void)dealloc;
-(id)initWithStyle:(long long)arg1 reuseIdentifier:(id)arg2 ;
-(UIDateLabel *)dateLabel;
-(void)setNameLabel:(UILabel *)arg1 ;
-(UILabel *)nameLabel;
@end

