/*
* This header is generated by classdump-dyld 1.0
* on Tuesday, June 5, 2018 at 12:40:25 PM China Standard Time
* Operating System: Version 8.2 (Build 12D508)
* Image Source: /private/var/db/stash/_.8k0vmU/Applications/MobilePhone.app/MobilePhone
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos.
*/

#import <MobilePhone/PhoneViewController.h>
#import <MobilePhone/PHVoicemailListMaskViewDelegate.h>
#import <MobilePhone/ABUnknownPersonViewControllerDelegate.h>
#import <UIKit/UIGestureRecognizerDelegate.h>
#import <MobilePhone/PHVoicemailCellDelegate.h>
#import <UIKit/UITableViewDataSource.h>
#import <UIKit/UITableViewDelegate.h>

@protocol OS_dispatch_queue, OS_dispatch_group;
@class UITableView, PHVoicemailNavigationController, PHVoicemailListMaskView, NSObject, NSArray, NSIndexPath, VMVoicemail, UIGestureRecognizer, NSString;

@interface PHVoicemailListViewController : PhoneViewController <PHVoicemailListMaskViewDelegate, ABUnknownPersonViewControllerDelegate, UIGestureRecognizerDelegate, PHVoicemailCellDelegate, UITableViewDataSource, UITableViewDelegate> {

	UITableView* _tableView;
	PHVoicemailNavigationController* _navigationController;
	PHVoicemailListMaskView* _maskView;
	NSObject*<OS_dispatch_queue> _queue;
	int _disableUserInteractionCountLock;
	int _disableUserInteractionCount;
	int _isReloadingTableViewLock;
	BOOL _isReloadingTableView;
	BOOL _shouldReloadTableView;
	NSObject*<OS_dispatch_queue> _initialSetupQueue;
	int _isSettingUpLock;
	BOOL _isSettingUp;
	BOOL _reloadAfterInitialSetup;
	NSObject*<OS_dispatch_group> _loadingGroup;
	NSArray* _voicemails;
	NSArray* _childListViewControllersWithContent;
	BOOL _showingUnavailableCell;
	BOOL _visible;
	NSIndexPath* _detailIndexPath;
	VMVoicemail* _selectedVoicemail;
	UIGestureRecognizer* _navBarGestureRecognizer;
	UIGestureRecognizer* _leftBarButtonItemGestureRecognizer;
	UIGestureRecognizer* _rightBarButtonItemGestureRecognizer;

}

@property (assign) PHVoicemailNavigationController * navigationController;                 //@synthesize navigationController=_navigationController - In the implementation block
@property (retain) NSArray * voicemails;                                                   //@synthesize voicemails=_voicemails - In the implementation block
@property (readonly) BOOL shouldBeShown; 
@property (assign) BOOL showingUnavailableCell;                                            //@synthesize showingUnavailableCell=_showingUnavailableCell - In the implementation block
@property (assign) BOOL visible;                                                           //@synthesize visible=_visible - In the implementation block
@property (retain) NSIndexPath * detailIndexPath;                                          //@synthesize detailIndexPath=_detailIndexPath - In the implementation block
@property (retain) VMVoicemail * selectedVoicemail;                                        //@synthesize selectedVoicemail=_selectedVoicemail - In the implementation block
@property (retain) NSArray * childListViewControllersWithContent;                          //@synthesize childListViewControllersWithContent=_childListViewControllersWithContent - In the implementation block
@property (retain) UIGestureRecognizer * navBarGestureRecognizer;                          //@synthesize navBarGestureRecognizer=_navBarGestureRecognizer - In the implementation block
@property (retain) UIGestureRecognizer * leftBarButtonItemGestureRecognizer;               //@synthesize leftBarButtonItemGestureRecognizer=_leftBarButtonItemGestureRecognizer - In the implementation block
@property (retain) UIGestureRecognizer * rightBarButtonItemGestureRecognizer;              //@synthesize rightBarButtonItemGestureRecognizer=_rightBarButtonItemGestureRecognizer - In the implementation block
@property (readonly) unsigned long long hash; 
@property (readonly) Class superclass; 
@property (copy,readonly) NSString * description; 
@property (copy,readonly) NSString * debugDescription; 
-(id)table;
-(void)_handleContentSizeDidChange:(id)arg1 ;
-(void)closeVoicemail;
-(NSArray *)voicemails;
-(BOOL)showingUnavailableCell;
-(id)_fetchCurrentVoicemails;
-(void)setVoicemails:(NSArray *)arg1 ;
-(id)_fetchCurrentChildListViewControllersWithContent;
-(void)setChildListViewControllersWithContent:(NSArray *)arg1 ;
-(void)setShowingUnavailableCell:(BOOL)arg1 ;
-(void)_handleVoicemailListChanged:(id)arg1 ;
-(void)_handleBackgroundNotification:(id)arg1 ;
-(void)_voicemailUnavailableCellHeightChanged:(id)arg1 ;
-(long long)_firstVoicemailOffset;
-(id)_indexPathForItem:(id)arg1 inList:(id)arg2 offset:(long long)arg3 ;
-(NSIndexPath *)detailIndexPath;
-(void)setDetailIndexPath:(NSIndexPath *)arg1 ;
-(void)setSelectedVoicemail:(VMVoicemail *)arg1 ;
-(void)_reloadTableViewIfNecessary;
-(void)_reloadVoicemailUI;
-(BOOL)shouldBeShown;
-(void)_handleSignificantTimeChange:(id)arg1 ;
-(NSArray *)childListViewControllersWithContent;
-(void)_updateUIForMaskViewChange;
-(void)maskViewWasTappedOutsideOfShownCell:(id)arg1 ;
-(VMVoicemail *)selectedVoicemail;
-(void)_popOffIfNeeded;
-(void)_disableInteraction;
-(id)_indexPathsForItems:(id)arg1 inList:(id)arg2 offset:(long long)arg3 ;
-(void)_enableInteraction;
-(void)_performEfficientTableViewReloadWithVoicemails:(id)arg1 childListControllersWithContent:(id)arg2 showingUnavailableCell:(BOOL)arg3 ;
-(void)_forceCompleteTableViewReloadWithVoicemails:(id)arg1 childListControllersWithContent:(id)arg2 showingUnavailableCell:(BOOL)arg3 ;
-(UIGestureRecognizer *)navBarGestureRecognizer;
-(void)_handleNavBarTap:(id)arg1 ;
-(void)setNavBarGestureRecognizer:(UIGestureRecognizer *)arg1 ;
-(UIGestureRecognizer *)leftBarButtonItemGestureRecognizer;
-(void)setLeftBarButtonItemGestureRecognizer:(UIGestureRecognizer *)arg1 ;
-(UIGestureRecognizer *)rightBarButtonItemGestureRecognizer;
-(void)setRightBarButtonItemGestureRecognizer:(UIGestureRecognizer *)arg1 ;
-(void)playVoicemail:(id)arg1 ;
-(void)dealloc;
-(double)tableView:(id)arg1 estimatedHeightForRowAtIndexPath:(id)arg2 ;
-(void)tableView:(id)arg1 accessoryButtonTappedForRowWithIndexPath:(id)arg2 ;
-(void)tableView:(id)arg1 didSelectRowAtIndexPath:(id)arg2 ;
-(void)tableView:(id)arg1 didDeselectRowAtIndexPath:(id)arg2 ;
-(long long)tableView:(id)arg1 editingStyleForRowAtIndexPath:(id)arg2 ;
-(id)tableView:(id)arg1 titleForDeleteConfirmationButtonForRowAtIndexPath:(id)arg2 ;
-(void)tableView:(id)arg1 willBeginEditingRowAtIndexPath:(id)arg2 ;
-(void)tableView:(id)arg1 didEndEditingRowAtIndexPath:(id)arg2 ;
-(long long)tableView:(id)arg1 numberOfRowsInSection:(long long)arg2 ;
-(id)tableView:(id)arg1 cellForRowAtIndexPath:(id)arg2 ;
-(BOOL)tableView:(id)arg1 canEditRowAtIndexPath:(id)arg2 ;
-(BOOL)tableView:(id)arg1 canMoveRowAtIndexPath:(id)arg2 ;
-(void)tableView:(id)arg1 commitEditingStyle:(long long)arg2 forRowAtIndexPath:(id)arg3 ;
-(BOOL)gestureRecognizer:(id)arg1 shouldReceiveTouch:(id)arg2 ;
-(void)setEditing:(BOOL)arg1 animated:(BOOL)arg2 ;
-(PHVoicemailNavigationController *)navigationController;
-(void)loadView;
-(void)setVisible:(BOOL)arg1 ;
-(void)viewWillAppear:(BOOL)arg1 ;
-(id)contentScrollView;
-(void)viewDidLoad;
-(void)viewDidDisappear:(BOOL)arg1 ;
-(BOOL)visible;
-(void)setNavigationController:(PHVoicemailNavigationController *)arg1 ;
-(void)unknownPersonViewController:(id)arg1 didResolveToPerson:(void*)arg2 ;
-(void)_updateTitle;
-(id)initWithNavigationController:(id)arg1 ;
@end

