/*
* This header is generated by classdump-dyld 1.0
* on Wednesday, June 6, 2018 at 7:04:48 PM China Standard Time
* Operating System: Version 8.2 (Build 12D508)
* Image Source: /private/var/db/stash/_.8k0vmU/Applications/AdSheet.app/AdSheet
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos.
*/


@class NSURL;

@interface _ADResourceTrackingRecord : NSObject {

	double _startTime;
	double _requestTime;
	double _responseTime;
	NSURL* _URL;

}

@property (assign,nonatomic) double startTime;                 //@synthesize startTime=_startTime - In the implementation block
@property (assign,nonatomic) double requestTime;               //@synthesize requestTime=_requestTime - In the implementation block
@property (assign,nonatomic) double responseTime;              //@synthesize responseTime=_responseTime - In the implementation block
@property (nonatomic,retain) NSURL * URL;                      //@synthesize URL=_URL - In the implementation block
-(double)requestTime;
-(void)setRequestTime:(double)arg1 ;
-(void)dealloc;
-(void)setStartTime:(double)arg1 ;
-(NSURL *)URL;
-(void)setURL:(NSURL *)arg1 ;
-(double)startTime;
-(void)setResponseTime:(double)arg1 ;
-(double)responseTime;
@end

