/*
* This header is generated by classdump-dyld 1.0
* on Wednesday, June 6, 2018 at 7:04:48 PM China Standard Time
* Operating System: Version 8.2 (Build 12D508)
* Image Source: /private/var/db/stash/_.8k0vmU/Applications/AdSheet.app/AdSheet
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos.
*/

#import <AdSheet/ADJavaScriptObject.h>
#import <AdSheet/ADRewardsJSO_Bindings.h>

@class JSValue, NSArray, NSMutableSet;

@interface ADRewardsJSO : ADJavaScriptObject <ADRewardsJSO_Bindings> {

	NSMutableSet* _lookedUpRewards;

}

@property (nonatomic,retain) NSMutableSet * lookedUpRewards;              //@synthesize lookedUpRewards=_lookedUpRewards - In the implementation block
@property (nonatomic,retain) JSValue * listener; 
@property (nonatomic,readonly) NSArray * rewardTokens; 
-(id)initWithDelegate:(id)arg1 impressionController:(id)arg2 ;
-(NSArray *)rewardTokens;
-(void)_processRewardResponse:(id)arg1 forToken:(id)arg2 ;
-(NSMutableSet *)lookedUpRewards;
-(void)_reportResult:(BOOL)arg1 forReward:(id)arg2 withErrorMessage:(id)arg3 ;
-(void)lookupReward:(id)arg1 ;
-(void)userRedeemedReward:(id)arg1 ;
-(void)reportRedeemFailureForReward:(id)arg1 withErrorMessage:(id)arg2 ;
-(void)setLookedUpRewards:(NSMutableSet *)arg1 ;
-(void)dealloc;
@end

