/*
* This header is generated by classdump-dyld 1.0
* on Wednesday, June 6, 2018 at 7:04:48 PM China Standard Time
* Operating System: Version 8.2 (Build 12D508)
* Image Source: /private/var/db/stash/_.8k0vmU/Applications/AdSheet.app/AdSheet
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos.
*/


#import <AdSheet/AdSheet-Structs.h>
@class ADSAdImpression, NSString, NSMutableSet, NSTimer, ADSCreativeController, ADAdImpressionPublicAttributes;

@interface ADSAdImpressionController : NSObject {

	BOOL _supportsAuthentication;
	BOOL _policyEngineManagedAd;
	ADSAdImpression* _ad;
	NSString* _authenticationUserName;
	/*^block*/id _loadCompletionHandler;
	NSMutableSet* _pendingRequiredItems;
	NSMutableSet* _allDownloadJobs;
	NSTimer* _loadTimeoutTimer;
	ADSCreativeController* _creativeController;
	NSString* _clientBundleIdentifier;

}

@property (nonatomic,readonly) double accumulatedVisibleTime; 
@property (nonatomic,copy,readonly) NSString * adIdentifier; 
@property (nonatomic,readonly) ADAdImpressionPublicAttributes * publicAttributes; 
@property (nonatomic,readonly) ADSAdImpression * ad;                                           //@synthesize ad=_ad - In the implementation block
@property (nonatomic,copy) NSString * authenticationUserName;                                  //@synthesize authenticationUserName=_authenticationUserName - In the implementation block
@property (assign,nonatomic) BOOL supportsAuthentication;                                      //@synthesize supportsAuthentication=_supportsAuthentication - In the implementation block
@property (nonatomic,readonly) BOOL shouldUseTimeBasedConfirmedClick; 
@property (assign,nonatomic) BOOL policyEngineManagedAd;                                       //@synthesize policyEngineManagedAd=_policyEngineManagedAd - In the implementation block
@property (nonatomic,readonly) BOOL shouldPreloadActionViewController; 
@property (nonatomic,copy) id loadCompletionHandler;                                           //@synthesize loadCompletionHandler=_loadCompletionHandler - In the implementation block
@property (nonatomic,retain) NSMutableSet * pendingRequiredItems;                              //@synthesize pendingRequiredItems=_pendingRequiredItems - In the implementation block
@property (nonatomic,retain) NSMutableSet * allDownloadJobs;                                   //@synthesize allDownloadJobs=_allDownloadJobs - In the implementation block
@property (nonatomic,retain) NSTimer * loadTimeoutTimer;                                       //@synthesize loadTimeoutTimer=_loadTimeoutTimer - In the implementation block
@property (nonatomic,retain) ADSCreativeController * creativeController;                       //@synthesize creativeController=_creativeController - In the implementation block
@property (nonatomic,copy,readonly) NSString * clientBundleIdentifier;                         //@synthesize clientBundleIdentifier=_clientBundleIdentifier - In the implementation block
@property (nonatomic,readonly) BOOL hasValidAdIdentifier; 
+(id)sharedDownloader;
+(id)probeDictionaryForAdData:(id)arg1 ;
+(void)validateAdData:(id)arg1 forClient:(id)arg2 completion:(/*^block*/id)arg3 ;
+(BOOL)validateAdCandidate:(id)arg1 forContainerSize:(CGSize)arg2 creativeType:(int)arg3 ;
-(void)reportSystemEvent:(int)arg1 ;
-(void)reportAdPaused;
-(void)loadCreativeControllerForSize:(CGSize)arg1 completion:(/*^block*/id)arg2 ;
-(id)initWithAdData:(id)arg1 bundleID:(id)arg2 loadedCompletion:(/*^block*/id)arg3 ;
-(void)setPolicyEngineManagedAd:(BOOL)arg1 ;
-(ADAdImpressionPublicAttributes *)publicAttributes;
-(BOOL)shouldPreloadActionViewController;
-(void)reportImpression;
-(double)accumulatedVisibleTime;
-(void)reportAdHasFinishedForContentHash:(id)arg1 ;
-(void)reportAdPlaybackFailedForURL:(id)arg1 ;
-(void)reportAdStartedForImpressionSource:(int)arg1 ;
-(void)reportAdResumed;
-(void)reportPrerollDidStart;
-(void)reportPrerollDidStop;
-(void)reportAdActionBegan;
-(void)reportClickAtLocation:(CGPoint)arg1 withAdViewFrame:(CGRect)arg2 ;
-(void)scheduleTimeBasedConfirmedClickIfNeeded;
-(void)reportExternalActionApproved:(BOOL)arg1 ;
-(void)adActionEndedWithSystemEvent:(int)arg1 ;
-(BOOL)shouldUseTimeBasedConfirmedClick;
-(void)reportConfirmedClick;
-(void)reportContentEvent:(id)arg1 ;
-(void)reportServerErrorWithCode:(int)arg1 details:(id)arg2 failingURLs:(id)arg3 ;
-(void)reportContentErrorWithInfo:(id)arg1 ;
-(NSString *)adIdentifier;
-(void)reportAdRewardResult:(BOOL)arg1 forReward:(id)arg2 withErrorMessage:(id)arg3 ;
-(void)requestReward:(id)arg1 callback:(/*^block*/id)arg2 ;
-(BOOL)hasValidAdIdentifier;
-(NSMutableSet *)pendingRequiredItems;
-(id)loadCompletionHandler;
-(void)setLoadTimeoutTimer:(NSTimer *)arg1 ;
-(void)setLoadCompletionHandler:(id)arg1 ;
-(NSMutableSet *)allDownloadJobs;
-(id)_assetRetrieveErrorForURLString:(id)arg1 errorMessage:(id)arg2 ;
-(void)_processCompletionOfItem:(id)arg1 error:(id)arg2 ;
-(BOOL)_handleArchiveSubResource:(id)arg1 maxAge:(double)arg2 ;
-(void)_fetchDataAtURL:(id)arg1 completion:(/*^block*/id)arg2 ;
-(void)_loadTimedOut;
-(void)_fetchWebArchiveWithURL:(id)arg1 injectQueryString:(id)arg2 completion:(/*^block*/id)arg3 ;
-(void)setCreativeController:(ADSCreativeController *)arg1 ;
-(ADSCreativeController *)creativeController;
-(BOOL)policyEngineManagedAd;
-(void)reportDidShowAd;
-(void)reportDidHideAd;
-(void)setPendingRequiredItems:(NSMutableSet *)arg1 ;
-(void)setAllDownloadJobs:(NSMutableSet *)arg1 ;
-(NSTimer *)loadTimeoutTimer;
-(void)dealloc;
-(void)observeValueForKeyPath:(id)arg1 ofObject:(id)arg2 change:(id)arg3 context:(void*)arg4 ;
-(void)_load;
-(void)setAuthenticationUserName:(NSString *)arg1 ;
-(NSString *)authenticationUserName;
-(void)setAdSpaceType:(int)arg1 ;
-(void)setSupportsAuthentication:(BOOL)arg1 ;
-(BOOL)supportsAuthentication;
-(NSString *)clientBundleIdentifier;
-(void)_failWithError:(id)arg1 ;
-(ADSAdImpression *)ad;
-(void)cancelLoading;
@end

