/*
* This header is generated by classdump-dyld 1.0
* on Wednesday, June 6, 2018 at 7:04:48 PM China Standard Time
* Operating System: Version 8.2 (Build 12D508)
* Image Source: /private/var/db/stash/_.8k0vmU/Applications/AdSheet.app/AdSheet
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos.
*/

#import <AdSheet/AdSheet-Structs.h>
#import <AdSheet/ADJavaScriptObject.h>
#import <AdSheet/ADSBannerJSO_Bindings.h>

@protocol OS_dispatch_queue;
@class NSString, NSObject, ADWebView, ADSStoryboardController;

@interface ADSBannerJSO : ADJavaScriptObject <ADSBannerJSO_Bindings> {

	NSObject*<OS_dispatch_queue> _iVarQueue;
	NSString* _bannerCustomMetadata;
	ADWebView* _webView;
	ADSStoryboardController* _storyboardController;
	BOOL _contentVisible;

}

@property (assign,nonatomic,__weak) ADWebView * webView; 
@property (assign,nonatomic,__weak) ADSStoryboardController * storyboardController; 
@property (assign,nonatomic) BOOL contentVisible;                                                //@synthesize contentVisible=_contentVisible - In the implementation block
@property (nonatomic,readonly) CGRect rectOnScreen; 
@property (nonatomic,readonly) CGPoint tapLocation; 
@property (nonatomic,copy) NSString * bannerCustomMetadata; 
+(void)initializeInContext:(id)arg1 ;
-(id)initWithDelegate:(id)arg1 impressionController:(id)arg2 ;
-(CGPoint)tapLocation;
-(CGRect)rectOnScreen;
-(NSString *)bannerCustomMetadata;
-(BOOL)isTargetApplicationInstalled;
-(void)setBannerCustomMetadata:(NSString *)arg1 ;
-(BOOL)contentVisible;
-(ADSStoryboardController *)storyboardController;
-(void)setStoryboardController:(ADSStoryboardController *)arg1 ;
-(void)dealloc;
-(BOOL)canOpenURL:(id)arg1 ;
-(ADWebView *)webView;
-(void)setWebView:(ADWebView *)arg1 ;
-(void)setContentVisible:(BOOL)arg1 ;
@end

