/*
* This header is generated by classdump-dyld 1.0
* on Wednesday, June 6, 2018 at 7:04:48 PM China Standard Time
* Operating System: Version 8.2 (Build 12D508)
* Image Source: /private/var/db/stash/_.8k0vmU/Applications/AdSheet.app/AdSheet
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos.
*/


@class NSString;

@interface AdSheetJSSetWallpaperRequest : NSObject {

	NSString* _url;
	NSString* _title;

}

@property (nonatomic,copy) NSString * url;                //@synthesize url=_url - In the implementation block
@property (nonatomic,copy) NSString * title;              //@synthesize title=_title - In the implementation block
-(void)dealloc;
-(void)setTitle:(NSString *)arg1 ;
-(NSString *)url;
-(NSString *)title;
-(void)setUrl:(NSString *)arg1 ;
@end

