/*
* This header is generated by classdump-dyld 1.0
* on Wednesday, June 6, 2018 at 7:04:48 PM China Standard Time
* Operating System: Version 8.2 (Build 12D508)
* Image Source: /private/var/db/stash/_.8k0vmU/Applications/AdSheet.app/AdSheet
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos.
*/

#import <AdSheet/ADJavaScriptObject.h>
#import <AdSheet/ADTwitterJSO_Bindings.h>

@class JSValue, NSString, NSArray, NSMutableArray;

@interface ADTwitterJSO : ADJavaScriptObject <ADTwitterJSO_Bindings> {

	NSString* _text;
	NSMutableArray* _tweetImageRecords;
	NSArray* _tweetURLs;

}

@property (nonatomic,retain) NSMutableArray * tweetImageRecords;              //@synthesize tweetImageRecords=_tweetImageRecords - In the implementation block
@property (nonatomic,copy) NSArray * tweetURLs;                               //@synthesize tweetURLs=_tweetURLs - In the implementation block
@property (nonatomic,retain) JSValue * listener; 
@property (nonatomic,copy) NSString * text;                                   //@synthesize text=_text - In the implementation block
@property (nonatomic,retain) NSArray * images; 
@property (nonatomic,retain) NSArray * URLs; 
+(void)initializeInContext:(id)arg1 ;
-(id)initWithDelegate:(id)arg1 impressionController:(id)arg2 ;
-(void)adWillDismiss;
-(void)presentComposer;
-(void)setTweetURLs:(NSArray *)arg1 ;
-(void)setTweetImageRecords:(NSMutableArray *)arg1 ;
-(void)followScreenName:(id)arg1 userID:(id)arg2 ;
-(NSMutableArray *)tweetImageRecords;
-(NSArray *)tweetURLs;
-(void)dealloc;
-(NSString *)text;
-(void)setText:(NSString *)arg1 ;
-(NSArray *)images;
-(void)setImages:(NSArray *)arg1 ;
-(void)setURLs:(NSArray *)arg1 ;
-(NSArray *)URLs;
@end

