/*
* This header is generated by classdump-dyld 1.0
* on Tuesday, June 5, 2018 at 12:15:12 PM China Standard Time
* Operating System: Version 8.2 (Build 12D508)
* Image Source: /private/var/db/stash/_.8k0vmU/Applications/FieldTest.app/FieldTest
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos.
*/


@class NSObject;

@interface Base : NSObject {

	NSObject* sectionRef;

}
+(short)lookUpECNO:(unsigned)arg1 ;
-(id)getSectionName;
-(void)updateLogCodeDict:(id)arg1 ;
-(void)replaceArray:(id)arg1 With:(id)arg2 ;
-(id)getLogCodeArray;
-(void)updateWithData:(id)arg1 logCode:(int)arg2 ;
-(void)clearElementsInArray:(id)arg1 ;
-(void)updateSectionRef:(id)arg1 ;
-(id)init;
@end

