/*
* This header is generated by classdump-dyld 1.0
* on Tuesday, June 5, 2018 at 12:15:12 PM China Standard Time
* Operating System: Version 8.2 (Build 12D508)
* Image Source: /private/var/db/stash/_.8k0vmU/Applications/FieldTest.app/FieldTest
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos.
*/

#import <FieldTest/Base.h>

@interface UTRANServingCellInfo : Base
-(id)getSectionName;
-(id)initWithDict:(id)arg1 codeDict:(id)arg2 ;
-(id)getLogCodeArray;
-(void)updateWithData:(id)arg1 logCode:(int)arg2 ;
@end

