/*
* This header is generated by classdump-dyld 1.0
* on Wednesday, June 6, 2018 at 7:46:59 PM China Standard Time
* Operating System: Version 8.2 (Build 12D508)
* Image Source: /private/var/db/stash/_.8k0vmU/Applications/SiriViewService.app/SiriViewService
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos.
*/

#import <SiriViewService/SiriViewService-Structs.h>
#import <UIKit/UIView.h>

@class UILabel, UIImageView;

@interface SVSStarkGatekeeperContactView : UIView {

	UILabel* _nameLabel;
	UIImageView* _photoImageView;

}

@property (getter=_nameLabel,nonatomic,readonly) UILabel * nameLabel;                            //@synthesize nameLabel=_nameLabel - In the implementation block
@property (getter=_photoImageView,nonatomic,readonly) UIImageView * photoImageView;              //@synthesize photoImageView=_photoImageView - In the implementation block
-(id)initWithSms:(id)arg1 ;
-(id)_displayNameForSms:(id)arg1 ;
-(id)_photoImageView;
-(id)_nameLabel;
-(void)layoutSubviews;
-(CGSize)sizeThatFits:(CGSize)arg1 ;
@end

