/*
* This header is generated by classdump-dyld 1.0
* on Wednesday, June 6, 2018 at 7:46:57 PM China Standard Time
* Operating System: Version 8.2 (Build 12D508)
* Image Source: /private/var/db/stash/_.8k0vmU/Applications/SiriViewService.app/SiriViewService
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos.
*/

#import <SiriViewService/SiriViewService-Structs.h>
#import <UIKit/UIViewController.h>
#import <SiriViewService/AFUIQueueDelegate.h>
#import <SiriViewService/SiriUISnippetViewControllerDelegate.h>
#import <SiriViewService/SiriUISnippetViewControllerDelegatePrivate.h>
#import <SiriViewService/SiriUIAceObjectViewControllerDelegate.h>
#import <SiriViewService/SiriUIAceObjectViewControllerDelegatePrivate.h>
#import <SiriViewService/SVSSuggestionsViewControllerDelegate.h>
#import <SiriViewService/SVSTranscriptDataSource.h>
#import <SiriViewService/SVSTranscriptDelegate.h>
#import <UIKit/UICollectionViewDataSource.h>
#import <UIKit/UICollectionViewDelegate.h>

@protocol SVSTranscriptViewControllerDataSource, SVSTranscriptViewControllerDelegate, SiriUIViewController;
@class SVSSuggestionsViewController, SVSTranscriptFlowLayout, SVSTranscript, SVSTranscriptAnimationQueue, SiriUITranscriptItem, NSMutableSet, UIViewController, UITapGestureRecognizer, NSMutableDictionary, NSUUID, SVSTranscriptView, NSString;

@interface SVSTranscriptViewController : UIViewController <AFUIQueueDelegate, SiriUISnippetViewControllerDelegate, SiriUISnippetViewControllerDelegatePrivate, SiriUIAceObjectViewControllerDelegate, SiriUIAceObjectViewControllerDelegatePrivate, SVSSuggestionsViewControllerDelegate, SVSTranscriptDataSource, SVSTranscriptDelegate, UICollectionViewDataSource, UICollectionViewDelegate> {

	long long _updateAnimationCount;
	BOOL _viewIsDisappearing;
	BOOL _viewIsInViewHierarchy;
	BOOL _didLoadConversationList;
	BOOL _showsTranscriptEndWhenVisible;
	id<SVSTranscriptViewControllerDataSource> _dataSource;
	id<SVSTranscriptViewControllerDelegate> _delegate;
	SVSSuggestionsViewController* _suggestionsViewController;
	SVSTranscriptFlowLayout* _layout;
	SVSTranscript* _transcript;
	SVSTranscriptAnimationQueue* _animationQueue;
	SVSTranscriptAnimationQueue* _pinAnimationQueue;
	double _lastAnimationTime;
	double _lastPinAnimationTime;
	double _currentPinMinimumDuration;
	SiriUITranscriptItem* _currentPin;
	NSMutableSet* _identifiersOfItemsWithPendingActions;
	UIViewController*<SiriUIViewController> _editingViewController;
	UITapGestureRecognizer* _editingEndGestureRecognizer;
	double _pinDistance;
	double _gridHeight;
	double _lastTranscriptDragStartTime;
	double _lastTranscriptEditingStartTime;
	NSMutableDictionary* _displayTimeByTranscriptIdentifier;

}

@property (nonatomic,readonly) NSUUID * identifierOfLastDisplayedItem; 
@property (nonatomic,readonly) BOOL transcriptStartIsVisible; 
@property (nonatomic,readonly) BOOL transcriptEndIsVisible; 
@property (nonatomic,readonly) BOOL transcriptIsAnimating; 
@property (assign,nonatomic,__weak) id<SVSTranscriptViewControllerDataSource> dataSource;                                                                                   //@synthesize dataSource=_dataSource - In the implementation block
@property (assign,nonatomic,__weak) id<SVSTranscriptViewControllerDelegate> delegate;                                                                                       //@synthesize delegate=_delegate - In the implementation block
@property (nonatomic,retain) SVSTranscriptView * view; 
@property (assign,setter=_setViewIsInViewHierarchy:,getter=_viewIsInViewHierarchy,nonatomic) BOOL viewIsInViewHierarchy;                                                    //@synthesize viewIsInViewHierarchy=_viewIsInViewHierarchy - In the implementation block
@property (getter=_suggestionsViewController,nonatomic,readonly) SVSSuggestionsViewController * suggestionsViewController;                                                  //@synthesize suggestionsViewController=_suggestionsViewController - In the implementation block
@property (getter=_layout,nonatomic,readonly) SVSTranscriptFlowLayout * layout;                                                                                             //@synthesize layout=_layout - In the implementation block
@property (getter=_transcript,nonatomic,readonly) SVSTranscript * transcript;                                                                                               //@synthesize transcript=_transcript - In the implementation block
@property (assign,setter=_setDidLoadConversationList:,getter=_didLoadConversationList,nonatomic) BOOL didLoadConversationList;                                              //@synthesize didLoadConversationList=_didLoadConversationList - In the implementation block
@property (getter=_animationQueue,nonatomic,readonly) SVSTranscriptAnimationQueue * animationQueue;                                                                         //@synthesize animationQueue=_animationQueue - In the implementation block
@property (getter=_pinAnimationQueue,nonatomic,readonly) SVSTranscriptAnimationQueue * pinAnimationQueue;                                                                   //@synthesize pinAnimationQueue=_pinAnimationQueue - In the implementation block
@property (assign,setter=_setLastAnimationTime:,getter=_lastAnimationTime,nonatomic) double lastAnimationTime;                                                              //@synthesize lastAnimationTime=_lastAnimationTime - In the implementation block
@property (assign,setter=_setLastPinAnimationTime:,getter=_lastPinAnimationTime,nonatomic) double lastPinAnimationTime;                                                     //@synthesize lastPinAnimationTime=_lastPinAnimationTime - In the implementation block
@property (assign,setter=_setCurrentPinMinimumDuration:,getter=_currentPinMinimumDuration,nonatomic) double currentPinMinimumDuration;                                      //@synthesize currentPinMinimumDuration=_currentPinMinimumDuration - In the implementation block
@property (setter=_setCurrentPin:,getter=_currentPin,nonatomic,retain) SiriUITranscriptItem * currentPin;                                                                   //@synthesize currentPin=_currentPin - In the implementation block
@property (getter=_identifiersOfItemsWithPendingActions,nonatomic,readonly) NSMutableSet * identifiersOfItemsWithPendingActions;                                            //@synthesize identifiersOfItemsWithPendingActions=_identifiersOfItemsWithPendingActions - In the implementation block
@property (setter=_setEditingViewController:,getter=_editingViewController,nonatomic,retain) UIViewController*<SiriUIViewController> editingViewController;                 //@synthesize editingViewController=_editingViewController - In the implementation block
@property (setter=_setEditingEndGestureRecognizer:,getter=_editingEndGestureRecognizer,nonatomic,retain) UITapGestureRecognizer * editingEndGestureRecognizer;              //@synthesize editingEndGestureRecognizer=_editingEndGestureRecognizer - In the implementation block
@property (assign,setter=_setShowsTranscriptEndWhenVisible:,getter=_showsTranscriptEndWhenVisible,nonatomic) BOOL showsTranscriptEndWhenVisible;                            //@synthesize showsTranscriptEndWhenVisible=_showsTranscriptEndWhenVisible - In the implementation block
@property (getter=_pinDistance,nonatomic,readonly) double pinDistance;                                                                                                      //@synthesize pinDistance=_pinDistance - In the implementation block
@property (getter=_gridHeight,nonatomic,readonly) double gridHeight;                                                                                                        //@synthesize gridHeight=_gridHeight - In the implementation block
@property (assign,setter=_setLastTranscriptDragStartTime:,getter=_lastTranscriptDragStartTime,nonatomic) double lastTranscriptDragStartTime;                                //@synthesize lastTranscriptDragStartTime=_lastTranscriptDragStartTime - In the implementation block
@property (assign,setter=_setLastTranscriptEditingStartTime:,getter=_lastTranscriptEditingStartTime,nonatomic) double lastTranscriptEditingStartTime;                       //@synthesize lastTranscriptEditingStartTime=_lastTranscriptEditingStartTime - In the implementation block
@property (getter=_displayTimeByTranscriptIdentifier,nonatomic,readonly) NSMutableDictionary * displayTimeByTranscriptIdentifier;                                           //@synthesize displayTimeByTranscriptIdentifier=_displayTimeByTranscriptIdentifier - In the implementation block
@property (readonly) unsigned long long hash; 
@property (readonly) Class superclass; 
@property (copy,readonly) NSString * description; 
@property (copy,readonly) NSString * debugDescription; 
-(void)svscvc_setItemIdentifier:(id)arg1 ;
-(id)svscvc_itemIdentifier;
-(id)_transcript;
-(void)_updateGridAndPinHeight;
-(double)_gridHeight;
-(id)_suggestionsViewController;
-(Class)aceControllerCellClass;
-(void)_registerReusableView:(Class)arg1 ;
-(Class)snippetControllerCellClass;
-(void)_updateStatusBarRelatedAttributesAndUpdateContentInset:(BOOL)arg1 ;
-(BOOL)_didLoadConversationList;
-(void)_setDidLoadConversationList:(BOOL)arg1 ;
-(double)_bottomBarInset;
-(double)_pinDistance;
-(id)_snippetViewControllerIfExistsAtItemIndex:(long long)arg1 ;
-(BOOL)_showsTranscriptEndWhenVisible;
-(void)_setShowsTranscriptEndWhenVisible:(BOOL)arg1 ;
-(void)showTranscriptEnd;
-(void)_setViewIsInViewHierarchy:(BOOL)arg1 ;
-(id)_conversationItemList;
-(id)_displayTimeByTranscriptIdentifier;
-(void)_logMetricsForVisibleSnippets;
-(void)_showSuggestionsIfNecessary;
-(BOOL)_viewIsInViewHierarchy;
-(void)_appendExtraSpaceToContentInsets;
-(void)_updateNavigationBarFrame;
-(void)_updateViewTopMarginHeight;
-(void)_updateViewContentInset;
-(double)_contentHeight;
-(id)_animationQueue;
-(id)_pinAnimationQueue;
-(id)_identifiersOfItemsWithPendingActions;
-(void)insertItemsAtIndexes:(id)arg1 ;
-(void)reloadItemsAtIndexes:(id)arg1 ;
-(void)removeItemsWithIdentifiers:(id)arg1 atIndexes:(id)arg2 ;
-(void)presentationStateDidChangeForItemsAtIndexes:(id)arg1 ;
-(double)_nextPinAnimationTime;
-(void)_scheduleNextPinAnimationAfterDelay:(double)arg1 ;
-(NSUUID *)identifierOfLastDisplayedItem;
-(void)_removeConversationItemWithIdentifier:(id)arg1 ;
-(void)siriViewController:(id)arg1 openURL:(id)arg2 completion:(/*^block*/id)arg3 ;
-(id)_domainObjectStore;
-(void)_setLastTranscriptEditingStartTime:(double)arg1 ;
-(void)_setCurrentPin:(id)arg1 ;
-(void)_pinTranscriptToCurrentPin;
-(void)_setupEditingForViewController:(id)arg1 ;
-(double)_lastTranscriptEditingStartTime;
-(void)_teardownEditingViewController:(id)arg1 ;
-(id)_transcriptItemForSiriViewController:(id)arg1 ;
-(void)siriViewControllerHeightDidChange:(id)arg1 pinTopOfSnippet:(BOOL)arg2 ;
-(id)_indexPathForItemAtIndex:(long long)arg1 ;
-(double)_expectedWidthForItemIndex:(unsigned long long)arg1 ;
-(UIEdgeInsets)_edgeInsetsForItemIndex:(unsigned long long)arg1 ;
-(CGRect)_frameForItemAtIndex:(unsigned long long)arg1 ;
-(double)_pinDistanceFromTop;
-(void)_speakText:(id)arg1 isPhonetic:(BOOL)arg2 completion:(/*^block*/id)arg3 ;
-(id)_conversationItemAtIndex:(long long)arg1 ;
-(id)_dialogPhaseForItemAtIndex:(long long)arg1 ;
-(void)_removeConversationItemsWithIdentifiers:(id)arg1 ;
-(id)_invalidIndexesToRemoveBeforeIndex:(long long)arg1 ;
-(id)_indexPathsForItemsAtIndexes:(id)arg1 ;
-(void)_processAnimationQueue;
-(void)_updateBottomKeylineForScrollView:(id)arg1 ;
-(id)_aceViewControllerIfExistsForTranscriptItem:(id)arg1 ;
-(id)_snippetViewControllerIfExistsForTranscriptItem:(id)arg1 ;
-(id)_currentPin;
-(void)animateTranscriptWithUpdates:(/*^block*/id)arg1 ;
-(id)_aceViewControllerIfExistsAtItemIndex:(long long)arg1 ;
-(void)_logMetricsForSnippetAtIndexPath:(id)arg1 ;
-(id)_controllerForItemIndex:(long long)arg1 ;
-(double)_heightForHeaderAtItemIndex:(long long)arg1 ;
-(double)_heightForFooterAtItemIndex:(long long)arg1 ;
-(void)_setLastTranscriptDragStartTime:(double)arg1 ;
-(double)_lastTranscriptDragStartTime;
-(BOOL)_itemIndexIsInset:(unsigned long long)arg1 ;
-(id)_indexPathForFirstResponder;
-(void)_tappedOutsideEditingView:(id)arg1 ;
-(void)_setEditingEndGestureRecognizer:(id)arg1 ;
-(void)_setEditingViewController:(id)arg1 ;
-(UIEdgeInsets)_requiredExtraSpaceToPinTranscriptItem:(id)arg1 ;
-(double)_nextAnimationTime;
-(void)_scheduleNextAnimationAfterDelay:(double)arg1 ;
-(double)_lastAnimationTime;
-(double)_lastPinAnimationTime;
-(double)_currentPinMinimumDuration;
-(void)_setLastAnimationTime:(double)arg1 ;
-(void)_performNextAnimation;
-(void)_processPinAnimationQueue;
-(void)_setLastPinAnimationTime:(double)arg1 ;
-(void)_setCurrentPinMinimumDuration:(double)arg1 ;
-(void)_performNextPinAnimation;
-(BOOL)_shouldConditionallyPinToTranscriptItem:(id)arg1 ;
-(id)_aceCommandIdentifierForItemAtIndex:(long long)arg1 ;
-(void)_animateSnippetTossInCell:(id)arg1 ;
-(void)_animateSnippetCancellation:(id)arg1 ;
-(void)_animateSnippetConfirmation:(id)arg1 ;
-(id)_tossAnimationForCell;
-(void)siriSnippetViewController:(id)arg1 pushSirilandSnippets:(id)arg2 ;
-(void)siriSnippetViewControllerWillBecomeFirstResponder:(id)arg1 ;
-(void)siriSnippetViewControllerViewDidLoad:(id)arg1 ;
-(void)siriSnippetViewController:(id)arg1 setStatusViewHidden:(BOOL)arg2 ;
-(void)siriSnippetViewController:(id)arg1 setStatusBarHidden:(BOOL)arg2 ;
-(void)siriSnippetViewController:(id)arg1 shouldPresentPicker:(id)arg2 completion:(/*^block*/id)arg3 ;
-(BOOL)siriViewController:(id)arg1 openURL:(id)arg2 ;
-(id)siriViewController:(id)arg1 domainObjectForIdentifier:(id)arg2 ;
-(void)siriViewController:(id)arg1 setDomainObject:(id)arg2 forIdentifier:(id)arg3 ;
-(id)siriViewControllerEffectiveBundleForCoreLocation:(id)arg1 ;
-(CGSize)siriViewControllerVisibleContentArea:(id)arg1 ;
-(void)siriViewControllerHeightDidChange:(id)arg1 ;
-(void)siriViewController:(id)arg1 setContentOffset:(double)arg2 ;
-(id)siriViewController:(id)arg1 disambiguationItemForListItem:(id)arg2 disambiguationKey:(id)arg3 ;
-(void)siriViewController:(id)arg1 addSelectionResponse:(id)arg2 ;
-(id)persistentStoreForSiriViewController:(id)arg1 ;
-(void)siriViewController:(id)arg1 didHideVibrantView:(id)arg2 ;
-(UIEdgeInsets)siriViewControllerDisplayInsetsForVisibleSpace:(id)arg1 ;
-(double)siriSnippetViewControllerExpectedWidth:(id)arg1 ;
-(void)siriViewController:(id)arg1 sendGenericAceCommands:(id)arg2 ;
-(BOOL)siriViewController:(id)arg1 openPunchOut:(id)arg2 ;
-(void)siriViewController:(id)arg1 speakText:(id)arg2 completion:(/*^block*/id)arg3 ;
-(void)cancelSpeakingForSiriViewController:(id)arg1 ;
-(BOOL)siriViewControllerShouldPreventUserInteraction:(id)arg1 ;
-(void)siriViewControllerWillBeginEditing:(id)arg1 ;
-(void)siriViewControllerDidEndEditing:(id)arg1 ;
-(void)siriViewController:(id)arg1 startCorrectedSpeechRequestWithText:(id)arg2 correctionIdentifier:(id)arg3 ;
-(void)removeSiriViewController:(id)arg1 ;
-(void)suggestionsViewDidShowSuggestions:(id)arg1 ;
-(CGRect)statusBarFrameForSuggestionsViewController:(id)arg1 ;
-(double)statusViewHeightForSuggestionsViewController:(id)arg1 ;
-(void)suggestionsViewController:(id)arg1 didHideVibrantView:(id)arg2 ;
-(long long)numberOfItemsInTranscript:(id)arg1 ;
-(id)transcript:(id)arg1 identifierOfItemAtIndex:(long long)arg2 ;
-(id)transcript:(id)arg1 dialogPhaseForItemAtIndex:(long long)arg2 ;
-(id)transcript:(id)arg1 aceCommandIdentifierForItemAtIndex:(long long)arg2 ;
-(BOOL)transcript:(id)arg1 itemAtIndexIsVirgin:(long long)arg2 ;
-(id)transcript:(id)arg1 aceObjectForItemAtIndex:(long long)arg2 ;
-(long long)transcript:(id)arg1 presentationStateForItemAtIndex:(long long)arg2 ;
-(id)viewControllerDelegateForTranscript:(id)arg1 ;
-(void)transcript:(id)arg1 didInsertTranscriptItemsAtIndexes:(id)arg2 ;
-(void)transcript:(id)arg1 didReplaceTranscriptItemsAtIndexes:(id)arg2 replacedTranscriptItems:(id)arg3 ;
-(void)transcript:(id)arg1 didReloadTranscriptItemsAtIndexes:(id)arg2 ;
-(void)transcript:(id)arg1 didRemoveTranscriptItems:(id)arg2 atIndexes:(id)arg3 ;
-(void)transcript:(id)arg1 presentationStateDidChangeForItemsAtIndexPaths:(id)arg2 ;
-(void)_runSirilandTransitionTestWithIterations:(int)arg1 ;
-(void)siriDidTransitionFromState:(long long)arg1 event:(long long)arg2 ;
-(void)statusBarFrameDidChange;
-(void)updateSuggestedUtterances:(id)arg1 forLanguage:(id)arg2 ;
-(BOOL)transcriptStartIsVisible;
-(BOOL)transcriptEndIsVisible;
-(BOOL)transcriptIsAnimating;
-(void)siriDidFinishActionsForConversationItemWithIdentifier:(id)arg1 ;
-(void)siriRequestWillStart;
-(void)pinItemWithIdentifier:(id)arg1 ;
-(void)siriBeganFingerprintingMusic;
-(void)siriStoppedFingerprintingMusic;
-(id)_editingViewController;
-(id)_editingEndGestureRecognizer;
-(BOOL)_isNavigationBarHidden;
-(id)_navigationBar;
-(void)dealloc;
-(void)setDataSource:(id<SVSTranscriptViewControllerDataSource>)arg1 ;
-(void)setDelegate:(id<SVSTranscriptViewControllerDelegate>)arg1 ;
-(void)reloadData;
-(void)scrollViewDidScroll:(id)arg1 ;
-(void)scrollViewWillBeginDragging:(id)arg1 ;
-(void)scrollViewDidEndDragging:(id)arg1 willDecelerate:(BOOL)arg2 ;
-(void)scrollViewDidEndDecelerating:(id)arg1 ;
-(void)scrollViewDidEndScrollingAnimation:(id)arg1 ;
-(id<SVSTranscriptViewControllerDataSource>)dataSource;
-(id<SVSTranscriptViewControllerDelegate>)delegate;
-(void)invalidate;
-(BOOL)_isRootViewController;
-(void)viewDidLayoutSubviews;
-(id)initWithNibName:(id)arg1 bundle:(id)arg2 ;
-(void)collectionView:(id)arg1 didEndDisplayingCell:(id)arg2 forItemAtIndexPath:(id)arg3 ;
-(long long)collectionView:(id)arg1 numberOfItemsInSection:(long long)arg2 ;
-(id)collectionView:(id)arg1 cellForItemAtIndexPath:(id)arg2 ;
-(long long)numberOfSectionsInCollectionView:(id)arg1 ;
-(void)loadView;
-(CGSize)collectionView:(id)arg1 layout:(id)arg2 sizeForItemAtIndexPath:(id)arg3 ;
-(void)viewWillAppear:(BOOL)arg1 ;
-(void)_setNavigationControllerContentInsetAdjustment:(UIEdgeInsets)arg1 ;
-(void)viewDidLoad;
-(void)viewDidAppear:(BOOL)arg1 ;
-(void)viewWillDisappear:(BOOL)arg1 ;
-(void)viewDidDisappear:(BOOL)arg1 ;
-(void)_keyboardWillHide:(id)arg1 ;
-(void)didRotateFromInterfaceOrientation:(long long)arg1 ;
-(double)_navigationControllerContentOffsetAdjustment;
-(double)_topBarHeight;
-(CGPoint)_contentOffset;
-(id)_layout;
-(void)_keyboardDidShow:(id)arg1 ;
-(id)_collectionView;
-(void)queue:(id)arg1 didEnqueueObjects:(id)arg2 ;
-(void)siriWillActivateFromSource:(long long)arg1 ;
-(void)siriDidDeactivate;
-(CGRect)_statusBarFrame;
-(void)_updateTitle;
-(id)requestContext;
-(void)cancelRequestForSiriSnippetViewController:(id)arg1 ;
-(void)siriSnippetViewController:(id)arg1 willPresentViewController:(id)arg2 ;
-(void)siriViewController:(id)arg1 performAceCommands:(id)arg2 ;
-(void)siriSnippetViewController:(id)arg1 willDismissViewController:(id)arg2 ;
-(double)siriViewControllerExpectedWidth:(id)arg1 ;
@end

