/*
* This header is generated by classdump-dyld 1.0
* on Tuesday, June 5, 2018 at 10:45:23 PM China Standard Time
* Operating System: Version 8.2 (Build 12D508)
* Image Source: /private/var/db/stash/_.8k0vmU/Applications/Calculator.app/Calculator
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos.
*/

#import <Calculator/Calculator-Structs.h>
#import <UIKit/UIView.h>

@protocol CalculatorKeypadViewDelegate;
@class NSArray, NSMutableDictionary, UIView, UIFont;

@interface CalculatorKeypadView : UIView {

	long long _keypadType;
	NSArray* _buttons;
	double _activeBorderWidth;
	unsigned long long _rows;
	unsigned long long _columns;
	CGPoint _previousLocation;
	NSMutableDictionary* _activeButtonViews;
	UIView* _pressedView;
	UIFont* _defaultFont;
	UIFont* _smallTextFont;
	id<CalculatorKeypadViewDelegate> _delegate;

}

@property (assign,nonatomic,__weak) id<CalculatorKeypadViewDelegate> delegate;              //@synthesize delegate=_delegate - In the implementation block
-(id)initWithFrame:(CGRect)arg1 keypadType:(long long)arg2 ;
-(void)setShowingAlternate:(BOOL)arg1 forButton:(unsigned long long)arg2 ;
-(void)setShowingActive:(BOOL)arg1 forButton:(unsigned long long)arg2 ;
-(id)_smallTextFont;
-(CGRect)_frameForRow:(unsigned long long)arg1 column:(unsigned long long)arg2 ;
-(CGRect)_ringFrameForButtonFrame:(CGRect)arg1 row:(unsigned long long)arg2 column:(unsigned long long)arg3 ;
-(void)_animateToSelectedState:(BOOL)arg1 forView:(id)arg2 borderWidth:(double)arg3 completion:(/*^block*/id)arg4 ;
-(void)_addActiveRingToButton:(id)arg1 row:(unsigned long long)arg2 column:(unsigned long long)arg3 ;
-(void)_removeActiveRingFromButton:(id)arg1 ;
-(void)_setFontsIfNeeded;
-(id)_buttonAtPoint:(CGPoint)arg1 ;
-(void)_removePressedView;
-(CGRect)_pressedFrameForButton:(id)arg1 ;
-(void)_drawGradientWithComponents:(double*)arg1 inRect:(CGRect)arg2 ;
-(void)drawRect:(CGRect)arg1 ;
-(void)setDelegate:(id<CalculatorKeypadViewDelegate>)arg1 ;
-(void)setFrame:(CGRect)arg1 ;
-(void)layoutSubviews;
-(id<CalculatorKeypadViewDelegate>)delegate;
-(void)touchesCancelled:(id)arg1 withEvent:(id)arg2 ;
-(void)touchesBegan:(id)arg1 withEvent:(id)arg2 ;
-(void)touchesMoved:(id)arg1 withEvent:(id)arg2 ;
-(void)touchesEnded:(id)arg1 withEvent:(id)arg2 ;
-(id)_defaultFont;
@end

