/*
* This header is generated by classdump-dyld 1.0
* on Wednesday, June 6, 2018 at 1:30:51 PM China Standard Time
* Operating System: Version 8.2 (Build 12D508)
* Image Source: /private/var/db/stash/_.8k0vmU/Applications/Tips.app/Tips
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos.
*/

#import <UIKit/UITableViewController.h>
#import <UIKit/UITableViewDataSource.h>
#import <UIKit/UITableViewDelegate.h>

@protocol TPSTableOfContentViewControllerDelegate;
@class TPSAppController, TPSTip, NSArray, NSString;

@interface TPSTableOfContentViewController : UITableViewController <UITableViewDataSource, UITableViewDelegate> {

	TPSAppController* _appController;
	id<TPSTableOfContentViewControllerDelegate> _delegate;
	TPSTip* _selectedTip;
	NSArray* _tips;

}

@property (assign,nonatomic,__weak) id<TPSTableOfContentViewControllerDelegate> delegate;              //@synthesize delegate=_delegate - In the implementation block
@property (nonatomic,retain) TPSTip * selectedTip;                                                     //@synthesize selectedTip=_selectedTip - In the implementation block
@property (nonatomic,retain) NSArray * tips;                                                           //@synthesize tips=_tips - In the implementation block
@property (readonly) unsigned long long hash; 
@property (readonly) Class superclass; 
@property (copy,readonly) NSString * description; 
@property (copy,readonly) NSString * debugDescription; 
-(TPSTip *)selectedTip;
-(id)initWithStyle:(long long)arg1 appController:(id)arg2 ;
-(void)setSelectedTip:(TPSTip *)arg1 ;
-(NSArray *)tips;
-(void)setTips:(NSArray *)arg1 ;
-(void)setDelegate:(id<TPSTableOfContentViewControllerDelegate>)arg1 ;
-(void)tableView:(id)arg1 didSelectRowAtIndexPath:(id)arg2 ;
-(long long)tableView:(id)arg1 numberOfRowsInSection:(long long)arg2 ;
-(id)tableView:(id)arg1 cellForRowAtIndexPath:(id)arg2 ;
-(id<TPSTableOfContentViewControllerDelegate>)delegate;
-(unsigned long long)supportedInterfaceOrientations;
-(void)viewWillAppear:(BOOL)arg1 ;
-(void)viewDidLoad;
-(void)viewDidAppear:(BOOL)arg1 ;
-(void)dismiss:(id)arg1 ;
@end

