/*
* This header is generated by classdump-dyld 1.0
* on Wednesday, June 6, 2018 at 1:30:51 PM China Standard Time
* Operating System: Version 8.2 (Build 12D508)
* Image Source: /private/var/db/stash/_.8k0vmU/Applications/Tips.app/Tips
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos.
*/

#import <UIKit/UIViewController.h>

@class TPSAppController, UIView, NSString, UIActivityIndicatorView, APDKVOManager, UILabel;

@interface TPSViewController : UIViewController {

	TPSAppController* _appController;
	UIView* _contentStructView;
	NSString* _defaultErrorTitleText;
	NSString* _messageLabelTitle;
	NSString* _messageLabelDetailText;
	UIActivityIndicatorView* _activityIndicatorView;
	BOOL _viewDidAppeared;
	BOOL _loading;
	APDKVOManager* _kvoManager;
	UILabel* _messageLabel;

}

@property (assign,nonatomic) BOOL viewDidAppeared;                          //@synthesize viewDidAppeared=_viewDidAppeared - In the implementation block
@property (assign,nonatomic) BOOL loading;                                  //@synthesize loading=_loading - In the implementation block
@property (nonatomic,retain) TPSAppController * appController;              //@synthesize appController=_appController - In the implementation block
@property (nonatomic,retain) APDKVOManager * kvoManager;                    //@synthesize kvoManager=_kvoManager - In the implementation block
@property (nonatomic,retain) UIView * contentStructView;                    //@synthesize contentStructView=_contentStructView - In the implementation block
@property (nonatomic,retain) UILabel * messageLabel;                        //@synthesize messageLabel=_messageLabel - In the implementation block
-(TPSAppController *)appController;
-(id)initWithAppController:(id)arg1 ;
-(void)setAppController:(TPSAppController *)arg1 ;
-(APDKVOManager *)kvoManager;
-(void)connectionChangedInitialCall;
-(void)commonUnloadView;
-(void)connectionChanged;
-(void)showInlineLabelWithTitle:(id)arg1 message:(id)arg2 ;
-(UIView *)contentStructView;
-(void)removeInlineMessageLabel;
-(void)showInlineNoConnectionMessage;
-(void)showInlineGenericErrorMessage;
-(void)showInlineMessageForError:(id)arg1 ;
-(void)setContentStructView:(UIView *)arg1 ;
-(BOOL)viewDidAppeared;
-(void)setViewDidAppeared:(BOOL)arg1 ;
-(void)setKvoManager:(APDKVOManager *)arg1 ;
-(void)dealloc;
-(id)initWithCoder:(id)arg1 ;
-(void)didReceiveMemoryWarning;
-(unsigned long long)supportedInterfaceOrientations;
-(id)initWithNibName:(id)arg1 bundle:(id)arg2 ;
-(UILabel *)messageLabel;
-(void)viewWillAppear:(BOOL)arg1 ;
-(void)viewDidLoad;
-(void)viewDidUnload;
-(void)viewDidAppear:(BOOL)arg1 ;
-(void)viewWillDisappear:(BOOL)arg1 ;
-(void)viewDidDisappear:(BOOL)arg1 ;
-(void)commonInit;
-(void)contentSizeCategoryDidChange:(id)arg1 ;
-(void)setMessageLabel:(UILabel *)arg1 ;
-(void)setLoading:(BOOL)arg1 ;
-(BOOL)loading;
@end

