/*
* This header is generated by classdump-dyld 1.0
* on Wednesday, June 6, 2018 at 1:30:51 PM China Standard Time
* Operating System: Version 8.2 (Build 12D508)
* Image Source: /private/var/db/stash/_.8k0vmU/Applications/Tips.app/Tips
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos.
*/

#import <Tips/Tips-Structs.h>
#import <Tips/TPSViewController.h>

@protocol TPSWelcomeViewControllerDelegate;
@class UIImageView, UIButton, UILabel, NSLayoutConstraint, TPSWelcomeAppearance, UIView;

@interface TPSWelcomeViewController : TPSViewController {

	BOOL _hasAnimated;
	UIImageView* _appIconImageView;
	UIButton* _startLearningButton;
	UILabel* _titleLabel;
	UILabel* _mainTextLabel;
	NSLayoutConstraint* _iconTopConstraint;
	NSLayoutConstraint* _startLearningButtonCenterXConstraint;
	TPSWelcomeAppearance* _welcomeAppearance;
	id<TPSWelcomeViewControllerDelegate> _delegate;
	UIView* _separatorLine;

}

@property (assign,nonatomic,__weak) id<TPSWelcomeViewControllerDelegate> delegate;              //@synthesize delegate=_delegate - In the implementation block
@property (nonatomic,retain) UIView * separatorLine;                                            //@synthesize separatorLine=_separatorLine - In the implementation block
-(void)showStartLearningButton;
-(void)createViews;
-(id)startLearningButtonFont;
-(void)startLearningTapped:(id)arg1 ;
-(void)updateAllLabelFonts;
-(void)dealloc;
-(void)setDelegate:(id<TPSWelcomeViewControllerDelegate>)arg1 ;
-(id<TPSWelcomeViewControllerDelegate>)delegate;
-(void)viewDidLayoutSubviews;
-(void)viewWillTransitionToSize:(CGSize)arg1 withTransitionCoordinator:(id)arg2 ;
-(void)viewDidAppear:(BOOL)arg1 ;
-(id)titleLabelFont;
-(void)contentSizeCategoryDidChange:(id)arg1 ;
-(UIView *)separatorLine;
-(void)setSeparatorLine:(UIView *)arg1 ;
@end

