/*
* This header is generated by classdump-dyld 1.0
* on Tuesday, June 5, 2018 at 6:50:54 PM China Standard Time
* Operating System: Version 8.2 (Build 12D508)
* Image Source: /private/var/db/stash/_.8k0vmU/Applications/MobileStore.app/MobileStore
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos.
*/

#import <MobileStore/MobileStore-Structs.h>
#import <MobileStore/SKUIApplicationDelegate.h>
#import <MobileStore/SSDownloadManagerObserver.h>
#import <MobileStore/SUPurchaseManagerDelegate.h>
#import <UIKit/UIApplicationDelegate.h>

@class UIWindow, SKUIApplicationController, SSDownloadManager, MSLaunchNotificationsController, SKUIURL, SULegacyClientBridge, NSString;

@interface MSApplicationDelegate : NSObject <SKUIApplicationDelegate, SSDownloadManagerObserver, SUPurchaseManagerDelegate, UIApplicationDelegate> {

	SKUIApplicationController* _applicationController;
	SSDownloadManager* _downloadManager;
	MSLaunchNotificationsController* _launchNotificationsController;
	SKUIURL* _launchURL;
	SULegacyClientBridge* _legacyBridge;
	long long _networkStartCount;
	BOOL _onActiveShouldResumeApplication;
	UIWindow* _window;

}

@property (readonly) unsigned long long hash; 
@property (readonly) Class superclass; 
@property (copy,readonly) NSString * description; 
@property (copy,readonly) NSString * debugDescription; 
@property (nonatomic,retain) UIWindow * window; 
-(void)_networkingStartNotification:(id)arg1 ;
-(void)_networkingStopNotification:(id)arg1 ;
-(long long)_tabBarStyleWithWidth:(double)arg1 ;
-(id)_newTabBarItemsWithStyle:(long long)arg1 ;
-(long long)_maximumTabBarItemsForStyle:(long long)arg1 ;
-(BOOL)_showsDownloadsTabForDownloadManager:(id)arg1 ;
-(void)_loadApplicationWithLaunchOptions:(id)arg1 ;
-(void)_showExternalURL:(id)arg1 ;
-(id)_newDefaultTabBarItemsWithClientContext:(id)arg1 style:(long long)arg2 ;
-(id)_downloadManager;
-(void)downloadManagerDownloadsDidChange:(id)arg1 ;
-(void)dealloc;
-(id)init;
-(BOOL)application:(id)arg1 openURL:(id)arg2 sourceApplication:(id)arg3 annotation:(id)arg4 ;
-(void)applicationDidBecomeActive:(id)arg1 ;
-(void)applicationWillResignActive:(id)arg1 ;
-(BOOL)application:(id)arg1 didFinishLaunchingWithOptions:(id)arg2 ;
-(BOOL)application:(id)arg1 runTest:(id)arg2 options:(id)arg3 ;
-(id)purchaseManager:(id)arg1 purchaseBatchForItems:(id)arg2 ;
-(id)purchaseManager:(id)arg1 purchaseBatchForPurchases:(id)arg2 ;
-(void)applicationDidCustomizeTabBarItems:(id)arg1 ;
-(void)application:(id)arg1 willTransitionToSize:(CGSize)arg2 withTransitionCoordinator:(id)arg3 ;
-(void)application:(id)arg1 didFailToLoadWithError:(id)arg2 ;
-(id)bootstrapScriptURLForApplication:(id)arg1 ;
-(id)application:(id)arg1 navigationControllerWithTabBarItem:(id)arg2 ;
-(void)applicationDidChangeClientContext:(id)arg1 ;
-(void)applicationDidDisplayFirstPage:(id)arg1 ;
@end

