/*
* This header is generated by classdump-dyld 1.0
* on Tuesday, June 5, 2018 at 6:43:31 PM China Standard Time
* Operating System: Version 8.2 (Build 12D508)
* Image Source: /private/var/db/stash/_.8k0vmU/Applications/MobileNotes.app/MobileNotes
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos.
*/


@protocol UISearchControllerDelegate <NSObject>
@optional
-(void)willPresentSearchController:(id)arg1;
-(void)didPresentSearchController:(id)arg1;
-(void)willDismissSearchController:(id)arg1;
-(void)didDismissSearchController:(id)arg1;
-(void)presentSearchController:(id)arg1;

@end

