/*
* This header is generated by classdump-dyld 1.0
* on Wednesday, June 6, 2018 at 1:23:39 PM China Standard Time
* Operating System: Version 8.2 (Build 12D508)
* Image Source: /private/var/db/stash/_.8k0vmU/Applications/Music.app/Music
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos.
*/

#import <Music/MAAppDelegate.h>

@class MPHRootViewController;

@interface MAPHAppDelegate : MAAppDelegate {

	MPHRootViewController* _rootViewController;
	BOOL _navigationControllerNeedsSupportsCoverFlowDidChange;

}
-(BOOL)_MAApplication:(id)arg1 willFinishLaunchingWithOptions:(id)arg2 ;
-(void)navigationController:(id)arg1 willShowViewController:(id)arg2 animated:(BOOL)arg3 ;
-(void)navigationController:(id)arg1 didShowViewController:(id)arg2 animated:(BOOL)arg3 ;
-(void)music_tabBarController:(id)arg1 didSelectViewController:(id)arg2 ;
@end

