/*
* This header is generated by classdump-dyld 1.0
* on Tuesday, June 5, 2018 at 11:54:56 AM China Standard Time
* Operating System: Version 8.2 (Build 12D508)
* Image Source: /System/Library/CoreServices/SpringBoard.app/SpringBoard
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos.
*/

#import <SpringBoard/SpringBoard-Structs.h>
#import <SpringBoard/SBAlert.h>

@class UIViewController;

@interface SBAlertAdapter : SBAlert {

	UIViewController* _effectiveViewController;

}
-(id)alertDisplayViewWithSize:(CGSize)arg1 ;
-(id)_basicDescription;
-(id)viewControllerForSupportedInterfaceOrientations;
-(id)effectiveViewController;
-(void)alertWindow:(id)arg1 resizedFromContentFrame:(CGRect)arg2 toContentFrame:(CGRect)arg3 ;
-(void)dealloc;
-(id)display;
-(BOOL)shouldAutorotate;
-(unsigned long long)supportedInterfaceOrientations;
-(void)setView:(id)arg1 ;
-(BOOL)shouldAutorotateToInterfaceOrientation:(long long)arg1 ;
-(BOOL)shouldAutomaticallyForwardRotationMethods;
-(BOOL)shouldAutomaticallyForwardAppearanceMethods;
-(id)initWithViewController:(id)arg1 ;
-(void)setDisplay:(id)arg1 ;
@end

