/*
* This header is generated by classdump-dyld 1.0
* on Tuesday, June 5, 2018 at 11:54:56 AM China Standard Time
* Operating System: Version 8.2 (Build 12D508)
* Image Source: /System/Library/CoreServices/SpringBoard.app/SpringBoard
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos.
*/


@class SBBBSectionInfo, SBBBBulletinInfo;

@interface SBBBInfoOperand : NSObject {

	SBBBSectionInfo* _section;
	SBBBBulletinInfo* _bulletin;

}

@property (nonatomic,readonly) SBBBSectionInfo * section;                                //@synthesize section=_section - In the implementation block
@property (nonatomic,readonly) SBBBBulletinInfo * bulletin;                              //@synthesize bulletin=_bulletin - In the implementation block
@property (getter=isSectionOperand,nonatomic,readonly) BOOL sectionOperand; 
+(id)operandWithSection:(id)arg1 bulletin:(id)arg2 ;
-(BOOL)isSectionOperand;
-(id)initWithSection:(id)arg1 bulletin:(id)arg2 ;
-(void)dealloc;
-(BOOL)isEqual:(id)arg1 ;
-(unsigned long long)hash;
-(id)description;
-(SBBBSectionInfo *)section;
-(SBBBBulletinInfo *)bulletin;
@end

