/*
* This header is generated by classdump-dyld 1.0
* on Tuesday, June 5, 2018 at 11:54:54 AM China Standard Time
* Operating System: Version 8.2 (Build 12D508)
* Image Source: /System/Library/CoreServices/SpringBoard.app/SpringBoard
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos.
*/


@protocol SBBulletinViewControllerDelegate <NSObject>
@optional
-(BOOL)bulletinViewController:(id)arg1 didSelectAction:(id)arg2 forBulletin:(id)arg3 inSection:(id)arg4;
-(long long)bulletinViewController:(id)arg1 insertionAnimationForBulletin:(id)arg2 inSection:(id)arg3;
-(long long)bulletinViewController:(id)arg1 removalAnimationForBulletin:(id)arg2 inSection:(id)arg3;
-(long long)bulletinViewController:(id)arg1 replacementAnimationForBulletin:(id)arg2 inSection:(id)arg3;
-(BOOL)bulletinViewController:(id)arg1 shouldHighlightBulletin:(id)arg2 inSection:(id)arg3;
-(BOOL)bulletinViewController:(id)arg1 didSelectBulletin:(id)arg2 inSection:(id)arg3;
-(long long)layoutModeForBulletinViewController:(id)arg1;

@end

