/*
* This header is generated by classdump-dyld 1.0
* on Tuesday, June 5, 2018 at 11:54:56 AM China Standard Time
* Operating System: Version 8.2 (Build 12D508)
* Image Source: /System/Library/CoreServices/SpringBoard.app/SpringBoard
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos.
*/

#import <UIKit/UIViewController.h>

@class _UILegibilityLabel;

@interface SBLockScreenStatusTextViewController : UIViewController {

	_UILegibilityLabel* _textLabel;

}
-(id)statusTextView;
-(void)_restoreStateChanged:(id)arg1 ;
-(id)_legalString;
-(id)_restoreString;
-(void)dealloc;
-(id)initWithNibName:(id)arg1 bundle:(id)arg2 ;
-(void)loadView;
-(void)didMoveToParentViewController:(id)arg1 ;
-(void)updateTextView;
@end

