/*
* This header is generated by classdump-dyld 1.0
* on Tuesday, June 5, 2018 at 11:54:55 AM China Standard Time
* Operating System: Version 8.2 (Build 12D508)
* Image Source: /System/Library/CoreServices/SpringBoard.app/SpringBoard
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos.
*/


@interface SBNewsstand : NSObject
+(void)reloadDefaults;
+(BOOL)newsstandEnabled;
+(BOOL)addManyIcons;
+(id)bundleIDToReplicate;
+(BOOL)newsstandStoreIsAvailable;
+(BOOL)addFakeApps;
+(void)openNewsstandAppStore;
+(BOOL)useInternationalAssets;
+(BOOL)alwaysShowIconLabels;
+(void)_checkStoreSupport;
+(void)_availableStoreItemKindsDidChange:(id)arg1 ;
+(void)_iconVisibilityDidChange:(id)arg1 ;
+(BOOL)_newsstandStoreIsSupported;
+(BOOL)_newsstandStoreIsRestricted;
+(void)_updateStoreAvailability;
+(void)noteAppRestrictionsDidChange;
+(BOOL)disableIconSkew;
+(void)initialize;
+(void)_loadDefaults;
@end

