/*
* This header is generated by classdump-dyld 1.0
* on Tuesday, June 5, 2018 at 11:54:55 AM China Standard Time
* Operating System: Version 8.2 (Build 12D508)
* Image Source: /System/Library/CoreServices/SpringBoard.app/SpringBoard
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos.
*/

#import <SpringBoard/SBFolderIcon.h>

@interface SBNewsstandIcon : SBFolderIcon
-(void)launchFromLocation:(int)arg1 ;
-(id)generateIconImage:(int)arg1 ;
-(id)getUnmaskedIconImage:(int)arg1 ;
-(BOOL)isNewsstandIcon;
-(BOOL)hasFolderIconView;
-(id)_newsstandIconImageName;
-(id)_generateImageUsingMask:(BOOL)arg1 ;
-(id)displayName;
-(id)folder;
@end

