/*
* This header is generated by classdump-dyld 1.0
* on Tuesday, June 5, 2018 at 11:54:55 AM China Standard Time
* Operating System: Version 8.2 (Build 12D508)
* Image Source: /System/Library/CoreServices/SpringBoard.app/SpringBoard
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos.
*/

#import <SpringBoard/SpringBoard-Structs.h>
#import <UIKit/UIView.h>

@interface SBNotificationSeparatorView : UIView {

	double _height;

}
+(long long)separatorViewModeForCurrentState;
+(id)separatorForCurrentState;
+(id)separatorWithScreenScale:(double)arg1 mode:(long long)arg2 ;
+(long long)blendMode;
+(id)color;
-(void)updateForCurrentState;
-(void)setFrame:(CGRect)arg1 ;
-(void)setBounds:(CGRect)arg1 ;
-(id)initWithFrame:(CGRect)arg1 mode:(long long)arg2 ;
@end

