/*
* This header is generated by classdump-dyld 1.0
* on Tuesday, June 5, 2018 at 11:54:54 AM China Standard Time
* Operating System: Version 8.2 (Build 12D508)
* Image Source: /System/Library/CoreServices/SpringBoard.app/SpringBoard
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos.
*/


@interface SBScreenShotter : NSObject {

	BOOL _writingScreenshot;
	unsigned long long _screenshotWriteCount;

}
+(Class)safeCategoryTargetClass;
+(id)sharedInstance;
-(BOOL)_isWritingSnapshot;
-(void)_incrementWriteCount;
-(void)finishedWritingScreenshot:(id)arg1 didFinishSavingWithError:(id)arg2 context:(void*)arg3 ;
-(void)finishedWritingCarScreenshot:(id)arg1 didFinishSavingWithError:(id)arg2 context:(void*)arg3 ;
-(void)_decrementWriteCount;
-(void)saveScreenshot:(BOOL)arg1 ;
@end

