/*
* This header is generated by classdump-dyld 1.0
* on Tuesday, June 5, 2018 at 11:54:55 AM China Standard Time
* Operating System: Version 8.2 (Build 12D508)
* Image Source: /System/Library/CoreServices/SpringBoard.app/SpringBoard
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos.
*/


@class NSMutableDictionary;

@interface SBStarkFakeIconOperationController : NSObject {

	NSMutableDictionary* _launchOperationForDisplayIDMap;

}
-(BOOL)performOperationForFakeIconWithDisplayID:(id)arg1 ;
-(void)addLaunchOperation:(/*^block*/id)arg1 withDisplayID:(id)arg2 ;
-(void)dealloc;
-(id)init;
@end

