/*
* This header is generated by classdump-dyld 1.0
* on Tuesday, June 5, 2018 at 6:38:24 PM China Standard Time
* Operating System: Version 8.2 (Build 12D508)
* Image Source: /private/var/db/stash/_.8k0vmU/Applications/Maps.app/Maps
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos.
*/

#import <Maps/Presenter.h>

@protocol TraitsChangeObserving;
@class AdaptivePresenterChoice, NSMutableArray, Presenter;

@interface AdaptivePresenter : Presenter {

	AdaptivePresenterChoice* _defaultChoice;
	NSMutableArray* _overrides;
	id<TraitsChangeObserving> _traitsObservingSource;
	AdaptivePresenterChoice* _currentChoice;
	BOOL _mustRepresentForTraitsChange;
	/*^block*/id _pendingPresentationCompletion;
	Presenter* _currentChildPresenter;
	/*^block*/id _willMoveToNewPresenterHandler;

}

@property (nonatomic,copy) id willMoveToNewPresenterHandler;                   //@synthesize willMoveToNewPresenterHandler=_willMoveToNewPresenterHandler - In the implementation block
@property (nonatomic,readonly) Presenter * currentChildPresenter;              //@synthesize currentChildPresenter=_currentChildPresenter - In the implementation block
+(id)placeCardPresenterForContentViewController:(id)arg1 ;
+(id)modalOrPopoverPresenterForViewController:(id)arg1 modalPresentationStyle:(long long)arg2 adaptivePresentationStyle:(long long)arg3 dismissalBlock:(/*^block*/id)arg4 ;
+(id)modalOrPopoverPresenterForViewController:(id)arg1 dismissalBlock:(/*^block*/id)arg2 ;
+(id)modalOrPopoverPresenterForViewController:(id)arg1 modalPresentationStyle:(long long)arg2 dismissalBlock:(/*^block*/id)arg3 ;
+(id)modalFormSheetWhenPossibleForViewController:(id)arg1 dismissalBlock:(/*^block*/id)arg2 ;
-(void)_didDismiss;
-(Presenter *)currentChildPresenter;
-(BOOL)isPresentingUsingPresenterOfClass:(Class)arg1 ;
-(id)initWithPresentedViewController:(id)arg1 defaultPresenterCreationBlock:(/*^block*/id)arg2 dismissalBlock:(/*^block*/id)arg3 ;
-(id)when:(id)arg1 usePresenterCreatedFromBlock:(/*^block*/id)arg2 ;
-(void)setWillMoveToNewPresenterHandler:(id)arg1 ;
-(void)_performPresentationOfViewController:(id)arg1 fromViewController:(id)arg2 animated:(BOOL)arg3 completion:(/*^block*/id)arg4 ;
-(void)_performDismissalAnimated:(BOOL)arg1 ;
-(id)currentChildPresenterIfOfClass:(Class)arg1 ;
-(id)choiceForPresentingFromViewController:(id)arg1 ;
-(id)initWithPresentedViewController:(id)arg1 defaultPresenterClass:(Class)arg2 dismissalBlock:(/*^block*/id)arg3 ;
-(id)when:(id)arg1 usePresenterOfClass:(Class)arg2 ;
-(id)initWithPresentedViewController:(id)arg1 defaultPresenterCreationBlock:(/*^block*/id)arg2 opaque:(BOOL)arg3 dismissalBlock:(/*^block*/id)arg4 ;
-(id)when:(id)arg1 usePresenterCreatedFromBlock:(/*^block*/id)arg2 opaque:(BOOL)arg3 ;
-(void)removeOverrideForCondition:(id)arg1 ;
-(id)_choiceMatchingCurrentTraits;
-(id)_choiceMatchingTraitsForSource:(id)arg1 ;
-(BOOL)_traitsConditionIsMatching:(id)arg1 fromTraitsSource:(id)arg2 ;
-(void)_didDismissChildPresenter:(id)arg1 ;
-(void)_representIfNeededAnimated:(BOOL)arg1 completion:(/*^block*/id)arg2 ;
-(id)_newChildPresenterFromChoice:(id)arg1 ;
-(id)willMoveToNewPresenterHandler;
-(id)defaultChoice;
-(BOOL)presentationMatchesChoice:(id)arg1 ;
-(BOOL)presentationFromViewController:(id)arg1 matchesOrWillMatchChoice:(id)arg2 ;
@end

