/*
* This header is generated by classdump-dyld 1.0
* on Tuesday, June 5, 2018 at 6:38:22 PM China Standard Time
* Operating System: Version 8.2 (Build 12D508)
* Image Source: /private/var/db/stash/_.8k0vmU/Applications/Maps.app/Maps
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos.
*/

#import <Maps/Maps-Structs.h>
#import <UIKit/UIView.h>

@class _UIBackdropView, UIColor;

@interface BlurView : UIView {

	_UIBackdropView* _backdrop;
	BOOL _blurDisabled;
	UIColor* _blurDisabledBackgroundColor;
	long long _privateStyle;
	long long _style;

}

@property (assign,nonatomic) long long style;                           //@synthesize style=_style - In the implementation block
@property (nonatomic,readonly) _UIBackdropView * backdrop;              //@synthesize backdrop=_backdrop - In the implementation block
+(BOOL)_isBlurDisabledButBackdropViewShownForDevice;
+(BOOL)_isBlurDisabledViaDefaults;
-(void)_configChanged;
-(void)_transitionToCurrentStyle;
-(void)_updateForStyleChange;
-(id)_backdropSettings;
-(void)_removeBackDrop;
-(void)_addBackDrop;
-(BOOL)_hasBackdrop;
-(void)setBlurDisabledBackgroundColor:(id)arg1 ;
-(void)dealloc;
-(long long)style;
-(void)didAddSubview:(id)arg1 ;
-(void)setStyle:(long long)arg1 ;
-(id)initWithPrivateStyle:(long long)arg1 ;
-(void)transitionToStyle:(long long)arg1 ;
-(id)initWithFrame:(CGRect)arg1 privateStyle:(long long)arg2 ;
-(void)transitionToPrivateStyle:(long long)arg1 ;
-(_UIBackdropView *)backdrop;
@end

