/*
* This header is generated by classdump-dyld 1.0
* on Tuesday, June 5, 2018 at 6:38:22 PM China Standard Time
* Operating System: Version 8.2 (Build 12D508)
* Image Source: /private/var/db/stash/_.8k0vmU/Applications/Maps.app/Maps
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos.
*/


@protocol CustomSearchManagerObserver <NSObject>
@required
-(void)customSearchManager:(id)arg1 didReplaceCustomSearchResult:(id)arg2 animated:(BOOL)arg3 shouldSelectOnMap:(BOOL)arg4;
-(void)customSearchManager:(id)arg1 didModifyCustomSearchResult:(id)arg2;

@end

