/*
* This header is generated by classdump-dyld 1.0
* on Tuesday, June 5, 2018 at 6:38:22 PM China Standard Time
* Operating System: Version 8.2 (Build 12D508)
* Image Source: /private/var/db/stash/_.8k0vmU/Applications/Maps.app/Maps
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos.
*/

#import <UIKit/UITableViewController.h>

@class UITableViewCell, UISegmentedControl, UIDatePicker, NSDate;

@interface DirectionsSearchDepartureArrivalSelectionViewController : UITableViewController {

	UITableViewCell* _selectorCell;
	UITableViewCell* _datePickerCell;
	UISegmentedControl* _selector;
	UIDatePicker* _datePicker;
	unsigned long long _suspendedViewUpdatesCount;
	NSDate* _departureDate;
	NSDate* _arrivalDate;
	/*^block*/id _didChangeValues;

}

@property (nonatomic,copy) NSDate * departureDate;              //@synthesize departureDate=_departureDate - In the implementation block
@property (nonatomic,copy) NSDate * arrivalDate;                //@synthesize arrivalDate=_arrivalDate - In the implementation block
@property (nonatomic,copy) id didChangeValues;                  //@synthesize didChangeValues=_didChangeValues - In the implementation block
-(id)_selector;
-(void)_updateViews;
-(void)_selectorDidChangeValue;
-(void)_datePickerDidChangeValue;
-(id)didChangeValues;
-(void)_invokeChangeHandler;
-(void)_performPreventingViewUpdates:(/*^block*/id)arg1 ;
-(void)setDidChangeValues:(id)arg1 ;
-(void)setArrivalDate:(NSDate *)arg1 ;
-(void)setDepartureDate:(NSDate *)arg1 ;
-(id)init;
-(double)tableView:(id)arg1 heightForRowAtIndexPath:(id)arg2 ;
-(long long)tableView:(id)arg1 numberOfRowsInSection:(long long)arg2 ;
-(id)tableView:(id)arg1 cellForRowAtIndexPath:(id)arg2 ;
-(void)viewDidLoad;
-(id)_datePicker;
-(NSDate *)departureDate;
-(NSDate *)arrivalDate;
@end

