/*
* This header is generated by classdump-dyld 1.0
* on Tuesday, June 5, 2018 at 6:38:22 PM China Standard Time
* Operating System: Version 8.2 (Build 12D508)
* Image Source: /private/var/db/stash/_.8k0vmU/Applications/Maps.app/Maps
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos.
*/

#import <UIKit/UITableViewCell.h>

@class MNSimpleSignView, RouteStepLabelListView, UIImageView;

@interface DirectionsTableViewCell : UITableViewCell {

	MNSimpleSignView* _signView;
	RouteStepLabelListView* _labelListView;
	UIImageView* _iconView;
	BOOL _alignLeftIfNoManeuverSign;
	BOOL _isDimmedStep;
	BOOL _isNightMode;

}

@property (assign,nonatomic) BOOL isNightMode;              //@synthesize isNightMode=_isNightMode - In the implementation block
+(double)heightForWidth:(double)arg1 route:(id)arg2 step:(id)arg3 ;
+(Class)_labelListViewClassForRoute:(id)arg1 step:(id)arg2 ;
+(double)_textWidthForWidth:(double)arg1 withManeuver:(BOOL)arg2 ;
+(id)currentStepColor;
+(id)reuseIdentifier;
-(void)_updateStyleValuesFromTheme;
-(void)setRoute:(id)arg1 step:(id)arg2 stepIndex:(unsigned long long)arg3 currentStep:(BOOL)arg4 alignToLeftEdgeIfNoManeuverSign:(BOOL)arg5 shieldText:(id)arg6 shieldArtwork:(id)arg7 ;
-(void)setIsDimmedStep:(BOOL)arg1 ;
-(void)setIsNightMode:(BOOL)arg1 ;
-(BOOL)isNightMode;
-(void)layoutSubviews;
-(id)initWithStyle:(long long)arg1 reuseIdentifier:(id)arg2 ;
-(void)prepareForReuse;
@end

