/*
* This header is generated by classdump-dyld 1.0
* on Tuesday, June 5, 2018 at 6:38:24 PM China Standard Time
* Operating System: Version 8.2 (Build 12D508)
* Image Source: /private/var/db/stash/_.8k0vmU/Applications/Maps.app/Maps
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos.
*/


@protocol DirectionsInfoDisplay <NSObject,MainChromeViewControllerBackdropLightness>
@required
-(void)setShowsDimmedDisplay:(BOOL)arg1 animation:(id)arg2;
-(void)setAlternateRoutesCount:(unsigned long long)arg1;
-(void)setSelectedRoute:(id)arg1 withIndex:(unsigned long long)arg2 destinationName:(id)arg3;
-(void)setTimeEstimate:(double)arg1 andDistanceEstimate:(double)arg2;
-(void)setDestinationName:(id)arg1;

@end

