/*
* This header is generated by classdump-dyld 1.0
* on Tuesday, June 5, 2018 at 6:38:24 PM China Standard Time
* Operating System: Version 8.2 (Build 12D508)
* Image Source: /private/var/db/stash/_.8k0vmU/Applications/Maps.app/Maps
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos.
*/

#import <Maps/Maps-Structs.h>
#import <Maps/MainChromeTopBarContent.h>
#import <Maps/DirectionsInfoDisplay.h>

@protocol DirectionsInfoBarDelegate;
@class NSArray, UIBarButtonItem, RouteStartStepView, RouteInfoLabelView, TopBarTitleView, MainChromeViewController, NSString;

@interface DirectionsInfoBar : NSObject <MainChromeTopBarContent, DirectionsInfoDisplay> {

	NSArray* _itemsForDirections;
	NSArray* _itemsForNavigation;
	NSArray* _itemsForLoading;
	UIBarButtonItem* _paddingItem1;
	UIBarButtonItem* _paddingItem2;
	UIBarButtonItem* _startButton;
	RouteStartStepView* _routeInfoView;
	RouteInfoLabelView* _routeInfoLabelView;
	TopBarTitleView* _loadingTitleView;
	long long _directionsInfoBarMode;
	id<DirectionsInfoBarDelegate> delegate;
	MainChromeViewController* _chromeViewController;
	NSArray* _items;

}

@property (assign,nonatomic,__weak) id<DirectionsInfoBarDelegate> delegate; 
@property (assign,nonatomic) long long directionsInfoBarMode;                              //@synthesize directionsInfoBarMode=_directionsInfoBarMode - In the implementation block
@property (nonatomic,retain) NSArray * _items;                                             //@synthesize items=_items - In the implementation block
@property (readonly) unsigned long long hash; 
@property (readonly) Class superclass; 
@property (copy,readonly) NSString * description; 
@property (copy,readonly) NSString * debugDescription; 
@property (assign,nonatomic) MainChromeViewController * chromeViewController;              //@synthesize chromeViewController=_chromeViewController - In the implementation block
+(double)defaultHeight;
-(MainChromeViewController *)chromeViewController;
-(void)setChromeViewController:(MainChromeViewController *)arg1 ;
-(void)setShowsDimmedDisplay:(BOOL)arg1 animation:(id)arg2 ;
-(long long)directionsInfoBarMode;
-(void)setDirectionsInfoBarMode:(long long)arg1 animated:(BOOL)arg2 ;
-(void)setAlternateRoutesCount:(unsigned long long)arg1 ;
-(void)setSelectedRoute:(id)arg1 withIndex:(unsigned long long)arg2 destinationName:(id)arg3 ;
-(void)refreshRouteInfoView;
-(void)setTimeEstimate:(double)arg1 andDistanceEstimate:(double)arg2 ;
-(void)setBackdropLightness:(long long)arg1 animation:(id)arg2 ;
-(void)topBarSizeWillChange:(CGSize)arg1 ;
-(void)_updateRouteInfoLabelView;
-(BOOL)isUIDark;
-(void)_startButtonTapped;
-(id)_startButton;
-(void)_clearDirectionsTapped;
-(id)_routeInfoView;
-(void)_endNavigationButtonTapped;
-(void)_resumeNavigationButtonTapped;
-(id)_routeInfoLabelView;
-(void)_cancelDirectionsLoadingTapped;
-(id)_loadingTitleView;
-(id)_itemsForDirections;
-(id)_itemsForNavigation;
-(id)_itemsForLoading;
-(void)set_items:(NSArray *)arg1 ;
-(double)overviewWidth;
-(void)setDirectionsInfoBarMode:(long long)arg1 ;
-(void)_handleLocaleChangeNotification:(id)arg1 ;
-(void)setDestinationName:(id)arg1 ;
-(void)dealloc;
-(void)setDelegate:(id<DirectionsInfoBarDelegate>)arg1 ;
-(id<DirectionsInfoBarDelegate>)delegate;
-(id)toolbarItems;
-(NSArray *)_items;
-(BOOL)isDimmed;
-(id)initWithMode:(long long)arg1 ;
@end

