/*
* This header is generated by classdump-dyld 1.0
* on Tuesday, June 5, 2018 at 6:38:24 PM China Standard Time
* Operating System: Version 8.2 (Build 12D508)
* Image Source: /private/var/db/stash/_.8k0vmU/Applications/Maps.app/Maps
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos.
*/

#import <UIKit/UITableViewCell.h>

@class UIButton, UIActivityIndicatorView;

@interface EnvironmentTableViewCell : UITableViewCell {

	UIButton* _errorButton;
	UIActivityIndicatorView* _loadingView;

}

@property (nonatomic,readonly) UIButton * errorButton;              //@synthesize errorButton=_errorButton - In the implementation block
-(UIButton *)errorButton;
-(void)configureFromEnvironment:(id)arg1 ;
-(void)_configureEnvironmentCell;
-(void)layoutSubviews;
-(id)initWithReuseIdentifier:(id)arg1 ;
-(void)setHighlighted:(BOOL)arg1 animated:(BOOL)arg2 ;
@end

