/*
* This header is generated by classdump-dyld 1.0
* on Tuesday, June 5, 2018 at 6:38:24 PM China Standard Time
* Operating System: Version 8.2 (Build 12D508)
* Image Source: /private/var/db/stash/_.8k0vmU/Applications/Maps.app/Maps
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos.
*/

#import <Maps/MapsDebugViewControllerDelegate.h>
#import <Maps/DirectionsStepsTableViewControllerDelegate.h>
#import <Maps/MainChromeModeController.h>

@class DirectionsStepsTableViewController, UINavigationController, DirectionsController, MapsDebugController, UIBarButtonItem, MapsChromeViewController, NSString, ChromeViewController;

@interface FullscreenGuidanceModeController : NSObject <MapsDebugViewControllerDelegate, DirectionsStepsTableViewControllerDelegate, MainChromeModeController> {

	DirectionsStepsTableViewController* _directionsSteps;
	UINavigationController* _navigationController;
	DirectionsController* _directionsController;
	MapsDebugController* _debugController;
	UIBarButtonItem* _debugItem;
	BOOL _hasShownDrivingNavModeAdvisory;
	BOOL _hasShownWalkingNavModeAdvisory;
	BOOL _locationPulseEnabled;
	MapsChromeViewController* _chromeViewController;

}

@property (readonly) unsigned long long hash; 
@property (readonly) Class superclass; 
@property (copy,readonly) NSString * description; 
@property (copy,readonly) NSString * debugDescription; 
@property (assign,nonatomic) BOOL hasShownDrivingNavModeAdvisory;                      //@synthesize hasShownDrivingNavModeAdvisory=_hasShownDrivingNavModeAdvisory - In the implementation block
@property (assign,nonatomic) BOOL hasShownWalkingNavModeAdvisory;                      //@synthesize hasShownWalkingNavModeAdvisory=_hasShownWalkingNavModeAdvisory - In the implementation block
@property (assign,nonatomic) BOOL locationPulseEnabled;                                //@synthesize locationPulseEnabled=_locationPulseEnabled - In the implementation block
@property (assign,nonatomic) ChromeViewController * chromeViewController; 
-(void)debugController:(id)arg1 choseTracePlayer:(id)arg2 startNav:(BOOL)arg3 ;
-(ChromeViewController *)chromeViewController;
-(void)debugControllerDidFinish:(id)arg1 ;
-(void)setChromeViewController:(ChromeViewController *)arg1 ;
-(void)becomeCurrentModeWithViews:(id)arg1 animated:(BOOL)arg2 state:(id)arg3 fromMode:(id)arg4 ;
-(void)resignCurrentModeAnimated:(BOOL)arg1 toMode:(id)arg2 ;
-(BOOL)canDisplayTraffic;
-(void)directionsStepsTableViewController:(id)arg1 didTapRowForRouteStep:(id)arg2 ;
-(void)directionsStepsTableViewController:(id)arg1 didTapDisclosureForSearchResult:(id)arg2 ;
-(BOOL)directionsStepsTableViewControllerShouldAllowInfoCardsForEndpoints:(id)arg1 ;
-(BOOL)directionsStepsTableViewControllerShouldShowOverview:(id)arg1 ;
-(void)hideDebugControls;
-(void)showDebugControls;
-(id)allVisibleMapViewsForDebugController:(id)arg1 ;
-(BOOL)hasShownDrivingNavModeAdvisory;
-(void)setHasShownDrivingNavModeAdvisory:(BOOL)arg1 ;
-(BOOL)hasShownWalkingNavModeAdvisory;
-(void)setHasShownWalkingNavModeAdvisory:(BOOL)arg1 ;
-(BOOL)locationPulseEnabled;
-(void)setLocationPulseEnabled:(BOOL)arg1 ;
-(id)initWithDirectionsController:(id)arg1 ;
-(void)_showDebugPanel;
-(BOOL)shouldAutorotate;
-(unsigned long long)supportedInterfaceOrientations;
-(void)willRotateToInterfaceOrientation:(long long)arg1 duration:(double)arg2 ;
-(void)willAnimateRotationToInterfaceOrientation:(long long)arg1 duration:(double)arg2 ;
-(void)didRotateFromInterfaceOrientation:(long long)arg1 ;
@end

