/*
* This header is generated by classdump-dyld 1.0
* on Tuesday, June 5, 2018 at 6:38:22 PM China Standard Time
* Operating System: Version 8.2 (Build 12D508)
* Image Source: /private/var/db/stash/_.8k0vmU/Applications/Maps.app/Maps
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos.
*/

#import <Maps/Maps-Structs.h>
#import <UIKit/UIView.h>

@class NSMutableArray, UIColor, NSArray;

@interface LabelListView : UIView {

	NSMutableArray* _labels;
	UIColor* _textColor;
	UIColor* _shadowColor;
	long long _textAlignment;
	UIEdgeInsets _insets;

}

@property (nonatomic,readonly) NSArray * labels;                   //@synthesize labels=_labels - In the implementation block
@property (nonatomic,retain) UIColor * textColor;                  //@synthesize textColor=_textColor - In the implementation block
@property (nonatomic,retain) UIColor * shadowColor;                //@synthesize shadowColor=_shadowColor - In the implementation block
@property (assign,nonatomic) long long textAlignment;              //@synthesize textAlignment=_textAlignment - In the implementation block
@property (assign,nonatomic) UIEdgeInsets insets;                  //@synthesize insets=_insets - In the implementation block
+(double)heightForWidth:(double)arg1 strings:(id)arg2 fonts:(id)arg3 ;
-(void)addLabelWithText:(id)arg1 accessibilityText:(id)arg2 font:(id)arg3 ;
-(void)layoutToFitSize:(CGSize)arg1 ;
-(void)removeAllLabels;
-(id)initWithFrame:(CGRect)arg1 ;
-(void)setTextColor:(UIColor *)arg1 ;
-(void)setTextAlignment:(long long)arg1 ;
-(void)setShadowColor:(UIColor *)arg1 ;
-(UIColor *)shadowColor;
-(UIColor *)textColor;
-(long long)textAlignment;
-(UIEdgeInsets)insets;
-(void)setInsets:(UIEdgeInsets)arg1 ;
-(NSArray *)labels;
@end

