/*
* This header is generated by classdump-dyld 1.0
* on Tuesday, June 5, 2018 at 6:38:23 PM China Standard Time
* Operating System: Version 8.2 (Build 12D508)
* Image Source: /private/var/db/stash/_.8k0vmU/Applications/Maps.app/Maps
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos.
*/

#import <Maps/Maps-Structs.h>
#import <UIKit/UIView.h>

@class BlurView, BarShadowView, UILabel, UIButton, UIView, MainChromeDetailsBarContent, UIFont;

@interface MainChromeDetailsBarView : UIView {

	BlurView* _backdrop;
	BarShadowView* _shadow;
	UILabel* _titleLabel;
	UIButton* _listButton;
	UIView* _contentView;
	MainChromeDetailsBarContent* _content;

}

@property (nonatomic,retain) MainChromeDetailsBarContent * content;              //@synthesize content=_content - In the implementation block
@property (nonatomic,readonly) double availableTitleLabelWidth; 
@property (nonatomic,readonly) UIFont * titleLabelFont; 
+(double)defaultHeight;
+(BOOL)requiresConstraintBasedLayout;
-(double)availableTitleLabelWidth;
-(id)initWithFrame:(CGRect)arg1 settingsButtonWidth:(double)arg2 ;
-(void)setContent:(id)arg1 animated:(BOOL)arg2 ;
-(void)_didTapListButton;
-(void)_updateFromContentAnimated:(BOOL)arg1 ;
-(void)setLightness:(long long)arg1 ;
-(void)_setNeedsUpdateFromContent;
-(id)hitTest:(CGPoint)arg1 withEvent:(id)arg2 ;
-(void)layoutSubviews;
-(CGSize)sizeThatFits:(CGSize)arg1 ;
-(void)layoutMarginsDidChange;
-(void)_update;
-(MainChromeDetailsBarContent *)content;
-(void)transitionToPrivateStyle:(long long)arg1 ;
-(UIFont *)titleLabelFont;
-(void)setContent:(MainChromeDetailsBarContent *)arg1 ;
@end

