/*
* This header is generated by classdump-dyld 1.0
* on Tuesday, June 5, 2018 at 6:38:23 PM China Standard Time
* Operating System: Version 8.2 (Build 12D508)
* Image Source: /private/var/db/stash/_.8k0vmU/Applications/Maps.app/Maps
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos.
*/

#import <Maps/MainChromeTopBarContentProvider.h>

@protocol MainChromeTopBarContent;
@class MainChromeViewController, NSString;

@interface MainChromeLegacyTopBarProvider : NSObject <MainChromeTopBarContentProvider> {

	id<MainChromeTopBarContent> _content;

}

@property (readonly) unsigned long long hash; 
@property (readonly) Class superclass; 
@property (copy,readonly) NSString * description; 
@property (copy,readonly) NSString * debugDescription; 
@property (assign,nonatomic) MainChromeViewController * chromeViewController; 
-(id)topBarContentForVariant:(long long)arg1 ;
-(id)initWithTopBarContent:(id)arg1 ;
@end

