/*
* This header is generated by classdump-dyld 1.0
* on Tuesday, June 5, 2018 at 6:38:22 PM China Standard Time
* Operating System: Version 8.2 (Build 12D508)
* Image Source: /private/var/db/stash/_.8k0vmU/Applications/Maps.app/Maps
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos.
*/


#import <Maps/Maps-Structs.h>
@interface MapScaleCell : NSObject {

	double _distanceInMeters;
	BOOL _useMetric;
	BOOL _useYardsForShortDistances;

}
-(id)initWithDistanceInMeters:(double)arg1 useMetric:(BOOL)arg2 useYardsForShortDistances:(BOOL)arg3 ;
-(id)_legendStringForDistanceString:(id)arg1 index:(int)arg2 ;
-(void)drawInRect:(CGRect)arg1 ;
@end

