/*
* This header is generated by classdump-dyld 1.0
* on Tuesday, June 5, 2018 at 6:38:24 PM China Standard Time
* Operating System: Version 8.2 (Build 12D508)
* Image Source: /private/var/db/stash/_.8k0vmU/Applications/Maps.app/Maps
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos.
*/

#import <Maps/MNBTAJobDelegate.h>
#import <Maps/GEORoutePreloadSessionDelegate.h>

@protocol GEORoutePreloadSession;
@class MNBTAJob, NSString;

@interface MapsRoutePreloadSession : NSObject <MNBTAJobDelegate, GEORoutePreloadSessionDelegate> {

	id<GEORoutePreloadSession> _preloadSession;
	MNBTAJob* _wifiJob;
	MNBTAJob* _goodCellularJob;

}

@property (readonly) id<GEORoutePreloadSession> preloadSession;              //@synthesize preloadSession=_preloadSession - In the implementation block
@property (readonly) unsigned long long hash; 
@property (readonly) Class superclass; 
@property (copy,readonly) NSString * description; 
@property (copy,readonly) NSString * debugDescription; 
-(id<GEORoutePreloadSession>)preloadSession;
-(id)initWithRoute:(id)arg1 traits:(id)arg2 ;
-(void)routePreloadSessionPausedLoading:(id)arg1 ;
-(void)routePreloadSessionBeganLoading:(id)arg1 ;
-(void)routePreloadSessionStoppedLoading:(id)arg1 wasEnabledAndNotPaused:(BOOL)arg2 ;
-(void)btaJob:(id)arg1 updatedState:(id)arg2 ;
-(void)_createBTAJobs;
-(void)_destroyBTAJobs;
-(void)dealloc;
@end

