/*
* This header is generated by classdump-dyld 1.0
* on Tuesday, June 5, 2018 at 6:38:23 PM China Standard Time
* Operating System: Version 8.2 (Build 12D508)
* Image Source: /private/var/db/stash/_.8k0vmU/Applications/Maps.app/Maps
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos.
*/

#import <Maps/Maps-Structs.h>
#import <Maps/MKAnnotation.h>

@class NSString;

@interface MNCircleAnnotation : NSObject <MKAnnotation> {

	double _color[4];
	double _radius;
	SCD_Struct_RA0 _coordinate;

}

@property (assign,nonatomic) SCD_Struct_RA0 coordinate;               //@synthesize coordinate=_coordinate - In the implementation block
@property (nonatomic,readonly) double red; 
@property (nonatomic,readonly) double green; 
@property (nonatomic,readonly) double blue; 
@property (nonatomic,readonly) double alpha; 
@property (assign,nonatomic) double radius;                           //@synthesize radius=_radius - In the implementation block
@property (readonly) unsigned long long hash; 
@property (readonly) Class superclass; 
@property (copy,readonly) NSString * description; 
@property (copy,readonly) NSString * debugDescription; 
@property (nonatomic,copy,readonly) NSString * title; 
@property (nonatomic,copy,readonly) NSString * subtitle; 
-(void)setColorRed:(double)arg1 green:(double)arg2 blue:(double)arg3 alpha:(double)arg4 ;
-(id)initWithCoordinate:(SCD_Struct_RA0)arg1 ;
-(double)alpha;
-(double)red;
-(double)green;
-(double)blue;
-(double)radius;
-(void)setRadius:(double)arg1 ;
-(SCD_Struct_RA0)coordinate;
-(void)setCoordinate:(SCD_Struct_RA0)arg1 ;
@end

