/*
* This header is generated by classdump-dyld 1.0
* on Tuesday, June 5, 2018 at 6:38:23 PM China Standard Time
* Operating System: Version 8.2 (Build 12D508)
* Image Source: /private/var/db/stash/_.8k0vmU/Applications/Maps.app/Maps
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos.
*/

#import <Maps/Maps-Structs.h>
#import <Maps/MKAnnotation.h>

@class CLLocation, NSString;

@interface MNDebugLocationAnnotation : NSObject <MKAnnotation> {

	CLLocation* _location;
	int _locationType;
	long long _navType;

}

@property (nonatomic,retain) CLLocation * location;                   //@synthesize location=_location - In the implementation block
@property (assign,nonatomic) int locationType;                        //@synthesize locationType=_locationType - In the implementation block
@property (assign,nonatomic) long long navType;                       //@synthesize navType=_navType - In the implementation block
@property (assign,nonatomic) SCD_Struct_RA0 coordinate; 
@property (readonly) unsigned long long hash; 
@property (readonly) Class superclass; 
@property (copy,readonly) NSString * description; 
@property (copy,readonly) NSString * debugDescription; 
@property (nonatomic,copy,readonly) NSString * title; 
@property (nonatomic,copy,readonly) NSString * subtitle; 
-(void)setNavType:(long long)arg1 ;
-(long long)navType;
-(CLLocation *)location;
-(void)setLocation:(CLLocation *)arg1 ;
-(void)setLocationType:(int)arg1 ;
-(int)locationType;
-(SCD_Struct_RA0)coordinate;
-(void)setCoordinate:(SCD_Struct_RA0)arg1 ;
-(double)course;
@end

