/*
* This header is generated by classdump-dyld 1.0
* on Tuesday, June 5, 2018 at 6:38:25 PM China Standard Time
* Operating System: Version 8.2 (Build 12D508)
* Image Source: /private/var/db/stash/_.8k0vmU/Applications/Maps.app/Maps
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos.
*/

#import <Maps/Maps-Structs.h>
#import <Maps/MNRouteManagerDelegate.h>

@class MNNavigationSession, MNRouteManager, MNRouteLoader, BKSProcessAssertion, RAPGraphDirectionsRecorder, NSString;

@interface MNDirectionsSession : NSObject <MNRouteManagerDelegate> {

	MNNavigationSession* _navigationSession;
	MNRouteManager* _routeManager;
	MNRouteLoader* _routeLoader;
	BOOL _didBeginNavigation;
	BOOL _didEndNavigation;
	BKSProcessAssertion* _priorityAssertion;
	SBSThermalWarningAssertionRef _thermalWarningAssertion;
	RAPGraphDirectionsRecorder* _reportAProblemRecorder;

}

@property (nonatomic,readonly) MNNavigationSession * navigationSession;                          //@synthesize navigationSession=_navigationSession - In the implementation block
@property (nonatomic,readonly) MNRouteManager * routeManager;                                    //@synthesize routeManager=_routeManager - In the implementation block
@property (nonatomic,readonly) MNRouteLoader * routeLoader;                                      //@synthesize routeLoader=_routeLoader - In the implementation block
@property (nonatomic,readonly) RAPGraphDirectionsRecorder * reportAProblemRecorder;              //@synthesize reportAProblemRecorder=_reportAProblemRecorder - In the implementation block
@property (nonatomic,retain) BKSProcessAssertion * priorityAssertion;                            //@synthesize priorityAssertion=_priorityAssertion - In the implementation block
@property (assign,nonatomic) SBSThermalWarningAssertionRef thermalWarningAssertion;              //@synthesize thermalWarningAssertion=_thermalWarningAssertion - In the implementation block
@property (readonly) unsigned long long hash; 
@property (readonly) Class superclass; 
@property (copy,readonly) NSString * description; 
@property (copy,readonly) NSString * debugDescription; 
+(BOOL)canRunDirectionsSessionWithSelectedRoute:(id)arg1 ;
+(BOOL)canRunDirectionsSessionWithLeg:(id)arg1 ;
+(BOOL)canRunDirectionsSessionWithRoutesWithTransportType:(int)arg1 ;
-(MNNavigationSession *)navigationSession;
-(MNRouteManager *)routeManager;
-(id)initWithRouteLoader:(id)arg1 ;
-(BOOL)setupNavigatorForTransportType:(int)arg1 useSimulation:(BOOL)arg2 tracePlayer:(id)arg3 ;
-(RAPGraphDirectionsRecorder *)reportAProblemRecorder;
-(void)routeManagerDidChangeState:(id)arg1 newRouteState:(int)arg2 ;
-(void)routeManager:(id)arg1 didChangeRoutePreloadSession:(id)arg2 ;
-(void)routeManager:(id)arg1 recordRouteRequest:(id)arg2 ;
-(void)routeManagerDidCancelRoute:(id)arg1 errorCode:(long long)arg2 ;
-(void)routeManagerWillRequestRoute:(id)arg1 traceRecorderFailed:(BOOL)arg2 ;
-(void)routeManagerDidFailToRecalculateRoute:(id)arg1 previousRoute:(id)arg2 errorCode:(long long)arg3 ;
-(void)routeManagerWillRecalculateRoute:(id)arg1 ;
-(void)routeManager:(id)arg1 didSwitchToNewRoute:(id)arg2 alreadyOnRoute:(BOOL)arg3 forcedSwitch:(BOOL)arg4 ;
-(void)routeManager:(id)arg1 recordRouteResponse:(id)arg2 ;
-(void)routeManager:(id)arg1 didReceiveRouteSet:(id)arg2 ;
-(void)routeManager:(id)arg1 didRecalculateNewRoute:(id)arg2 ;
-(void)routeManagerDidFailToReceiveRoute:(id)arg1 error:(id)arg2 ;
-(void)routeManager:(id)arg1 failedWithError:(id)arg2 ;
-(void)routeManagerUpdatedETA:(id)arg1 ;
-(void)routeManagerUpdatedTrafficIncidents:(id)arg1 ;
-(void)routeManager:(id)arg1 recommendsNewRoute:(id)arg2 etaRoute:(id)arg3 oldEstimatedTime:(unsigned)arg4 newEstimatedTime:(unsigned)arg5 ;
-(BKSProcessAssertion *)priorityAssertion;
-(void)setPriorityAssertion:(BKSProcessAssertion *)arg1 ;
-(void)setThermalWarningAssertion:(SBSThermalWarningAssertionRef)arg1 ;
-(MNRouteLoader *)routeLoader;
-(SBSThermalWarningAssertionRef)thermalWarningAssertion;
-(void)dealloc;
@end

