/*
* This header is generated by classdump-dyld 1.0
* on Tuesday, June 5, 2018 at 6:38:22 PM China Standard Time
* Operating System: Version 8.2 (Build 12D508)
* Image Source: /private/var/db/stash/_.8k0vmU/Applications/Maps.app/Maps
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos.
*/

#import <Maps/Maps-Structs.h>
#import <UIKit/UIView.h>
#import <UIKit/UIGestureRecognizerDelegate.h>

@protocol MNGuidanceSignViewDelegate;
@class MNGuidanceSignView, MNGuidanceSecondarySignView, NSString;

@interface MNGuidanceSignContainerView : UIView <UIGestureRecognizerDelegate> {

	id<MNGuidanceSignViewDelegate> _delegate;
	double _maximumWidth;
	MNGuidanceSignView* _primarySignView;
	MNGuidanceSecondarySignView* _secondarySignView;

}

@property (assign,nonatomic,__weak) id<MNGuidanceSignViewDelegate> delegate;               //@synthesize delegate=_delegate - In the implementation block
@property (assign,nonatomic) double maximumWidth;                                          //@synthesize maximumWidth=_maximumWidth - In the implementation block
@property (nonatomic,retain) MNGuidanceSignView * primarySignView;                         //@synthesize primarySignView=_primarySignView - In the implementation block
@property (nonatomic,retain) MNGuidanceSecondarySignView * secondarySignView;              //@synthesize secondarySignView=_secondarySignView - In the implementation block
@property (readonly) unsigned long long hash; 
@property (readonly) Class superclass; 
@property (copy,readonly) NSString * description; 
@property (copy,readonly) NSString * debugDescription; 
-(void)_alignAndCenterSigns;
-(MNGuidanceSecondarySignView *)secondarySignView;
-(MNGuidanceSignView *)primarySignView;
-(void)setPrimarySignView:(MNGuidanceSignView *)arg1 ;
-(void)setSecondarySignView:(MNGuidanceSecondarySignView *)arg1 ;
-(id)initWithFrame:(CGRect)arg1 ;
-(void)setDelegate:(id<MNGuidanceSignViewDelegate>)arg1 ;
-(void)setNeedsLayout;
-(void)layoutSubviews;
-(CGSize)sizeThatFits:(CGSize)arg1 ;
-(id<MNGuidanceSignViewDelegate>)delegate;
-(BOOL)gestureRecognizerShouldBegin:(id)arg1 ;
-(void)setMaximumWidth:(double)arg1 ;
-(double)maximumWidth;
-(void)_handleSingleTap:(id)arg1 ;
@end

