/*
* This header is generated by classdump-dyld 1.0
* on Tuesday, June 5, 2018 at 6:38:23 PM China Standard Time
* Operating System: Version 8.2 (Build 12D508)
* Image Source: /private/var/db/stash/_.8k0vmU/Applications/Maps.app/Maps
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos.
*/

#import <Maps/Maps-Structs.h>
#import <Maps/GuidanceSignView.h>

@class UIView, MNGuidanceSignDistanceLabel, MNGuidanceSignInstructionsLabel, MNGuidanceManeuverView, UIActivityIndicatorView, UIImageView, MNGuidanceSignBackgroundView, NSString, NSArray, UIImage;

@interface MNGuidanceSignView : GuidanceSignView {

	double _maximumWidth;
	UIView* _containerView;
	CGRect _pendingContainerFrame;
	BOOL _disallowMutation;
	MNGuidanceSignDistanceLabel* _distanceLabel;
	MNGuidanceSignInstructionsLabel* _instructionsLabel;
	MNGuidanceManeuverView* _maneuverView;
	BOOL _shouldShowSpinner;
	UIActivityIndicatorView* _activityView;
	UIImageView* _borderView;
	MNGuidanceSignBackgroundView* _backgroundView;
	UIView* _dividerView;
	UIImageView* _shieldView;
	CGPoint _shieldCenter;
	NSString* _shieldText;
	int _shieldType;
	NSArray* _instructionsTextAlternatives;
	BOOL _showsSubviewBounds;
	BOOL _delayLayout;

}

@property (assign,nonatomic) double maximumWidth;                                             //@synthesize maximumWidth=_maximumWidth - In the implementation block
@property (nonatomic,copy) NSString * distanceText; 
@property (nonatomic,copy) NSArray * instructionsTextAlternatives;                            //@synthesize instructionsTextAlternatives=_instructionsTextAlternatives - In the implementation block
@property (assign,nonatomic) unsigned long long maximumNumberOfInstructionLines; 
@property (nonatomic,readonly) MNGuidanceManeuverView * maneuverView;                         //@synthesize maneuverView=_maneuverView - In the implementation block
@property (nonatomic,retain) UIImage * shieldImage; 
@property (assign,nonatomic) CGPoint shieldCenter;                                            //@synthesize shieldCenter=_shieldCenter - In the implementation block
@property (nonatomic,copy) NSString * shieldText;                                             //@synthesize shieldText=_shieldText - In the implementation block
@property (assign,nonatomic) int shieldType;                                                  //@synthesize shieldType=_shieldType - In the implementation block
@property (assign,nonatomic) BOOL shouldShowSpinner;                                          //@synthesize shouldShowSpinner=_shouldShowSpinner - In the implementation block
-(MNGuidanceManeuverView *)maneuverView;
-(UIImage *)shieldImage;
-(void)setShieldImage:(UIImage *)arg1 ;
-(void)setDistanceText:(NSString *)arg1 ;
-(void)finalizePosition;
-(BOOL)textIsCentered;
-(double)instructionStartingX;
-(void)setContentFrameX:(double)arg1 ;
-(NSString *)shieldText;
-(id)_activityView;
-(void)willAnimateStyleValuesFromTheme;
-(void)didAnimateStyleValuesFromTheme;
-(void)updateStyleValuesFromTheme;
-(id)instructionsLabel;
-(void)setViewAlpha:(double)arg1 withoutManuever:(BOOL)arg2 withoutInstructions:(BOOL)arg3 ;
-(void)setDelayLayout:(BOOL)arg1 ;
-(void)textLinesShouldAnimateFromHeight:(double)arg1 ;
-(void)animateTextUpWithDuration:(double)arg1 ;
-(void)animateTextDownWithDuration:(double)arg1 ;
-(NSArray *)instructionsTextAlternatives;
-(void)setInstructionsTextAlternatives:(NSArray *)arg1 ;
-(void)setInstructionsText:(id)arg1 shorterAlternatives:(id)arg2 ;
-(void)setMaximumNumberOfInstructionLines:(unsigned long long)arg1 ;
-(void)setShieldCenter:(CGPoint)arg1 ;
-(void)setShieldText:(NSString *)arg1 ;
-(BOOL)shouldShowSpinner;
-(void)setShouldShowSpinner:(BOOL)arg1 ;
-(void)disallowMutation;
-(double)heightThatFitsWidth:(double)arg1 ;
-(BOOL)manueverNeedsPeekingAdjustment;
-(void)updateManueverOriginXForScrollPosition:(double)arg1 ;
-(NSString *)distanceText;
-(void)transformSublayersByPercentComplete:(double)arg1 ;
-(unsigned long long)maximumNumberOfInstructionLines;
-(void)updateDividerHeightForRect:(CGRect)arg1 ;
-(CGPoint)shieldCenter;
-(id)initWithFrame:(CGRect)arg1 ;
-(void)dealloc;
-(void)setNeedsLayout;
-(void)setHidden:(BOOL)arg1 ;
-(void)layoutSubviews;
-(CGSize)sizeThatFits:(CGSize)arg1 ;
-(void)setMaximumWidth:(double)arg1 ;
-(double)maximumWidth;
-(void)observeValueForKeyPath:(id)arg1 ofObject:(id)arg2 change:(id)arg3 context:(void*)arg4 ;
-(BOOL)delayLayout;
-(CGRect)contentFrame;
-(int)shieldType;
-(void)setShieldType:(int)arg1 ;
-(void)setVariant:(int)arg1 ;
@end

