/*
* This header is generated by classdump-dyld 1.0
* on Tuesday, June 5, 2018 at 6:38:24 PM China Standard Time
* Operating System: Version 8.2 (Build 12D508)
* Image Source: /private/var/db/stash/_.8k0vmU/Applications/Maps.app/Maps
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos.
*/

#import <Maps/MNLocationTracker.h>

@class GEORouteMatcher, GEORouteMatch;

@interface MNSteppingLocationTracker : MNLocationTracker {

	GEORouteMatcher* _routeMatcher;
	GEORouteMatch* _lastRouteMatch;

}
-(unsigned long long)lastMatchedStepIndex;
-(unsigned long long)lastMatchedLegIndex;
-(void)startTrackingWithGuidanceEnabled:(BOOL)arg1 midRoute:(BOOL)arg2 ;
-(id)initWithNavigationSession:(id)arg1 ;
-(void)resetForTracePlayerAtLocation:(id)arg1 ;
-(id)_routeMatchForLocation:(id)arg1 ;
-(void)stopTracking;
-(void)updateLocation:(id)arg1 ;
@end

