/*
* This header is generated by classdump-dyld 1.0
* on Tuesday, June 5, 2018 at 6:38:24 PM China Standard Time
* Operating System: Version 8.2 (Build 12D508)
* Image Source: /private/var/db/stash/_.8k0vmU/Applications/Maps.app/Maps
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos.
*/


@protocol MNTraceControlViewDelegate <NSObject>
@required
-(void)traceControlViewJumpedBack:(id)arg1;
-(void)traceControlView:(id)arg1 setPlaying:(BOOL)arg2;
-(void)traceControlView:(id)arg1 setPlaySpeed:(double)arg2;
-(void)traceControlViewPressedBookmarksButton:(id)arg1;
-(void)traceControlViewPressedStartLoggingButton:(id)arg1;
-(void)traceControlViewPressedEndLoggingButton:(id)arg1;

@end

