/*
* This header is generated by classdump-dyld 1.0
* on Tuesday, June 5, 2018 at 6:38:23 PM China Standard Time
* Operating System: Version 8.2 (Build 12D508)
* Image Source: /private/var/db/stash/_.8k0vmU/Applications/Maps.app/Maps
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos.
*/


@class NSFileManager, NSString;

@interface MNTraceManager : NSObject {

	NSFileManager* _fileManager;
	NSString* _userTracesDirectory;

}

@property (nonatomic,retain) NSString * userTracesDirectory;              //@synthesize userTracesDirectory=_userTracesDirectory - In the implementation block
+(id)sharedManager;
-(BOOL)deleteUserTraceWithName:(id)arg1 ;
-(id)pathForUserTrace:(id)arg1 ;
-(BOOL)moveUserTraceAtPath:(id)arg1 toPath:(id)arg2 ;
-(id)preferredUserTracePathForName:(id)arg1 ;
-(void)setUserTracesDirectory:(NSString *)arg1 ;
-(BOOL)createFolderIfNotPresent:(id)arg1 error:(id*)arg2 ;
-(id)filenameForUserTrace:(id)arg1 ;
-(id)listOfTracesFromPaths:(id)arg1 ;
-(id)_cleanPathForDirectory:(id)arg1 ;
-(id)listOfUserTraces;
-(id)clearSimulatedTracePath;
-(NSString *)userTracesDirectory;
-(id)init;
@end

