/*
* This header is generated by classdump-dyld 1.0
* on Tuesday, June 5, 2018 at 6:38:24 PM China Standard Time
* Operating System: Version 8.2 (Build 12D508)
* Image Source: /private/var/db/stash/_.8k0vmU/Applications/Maps.app/Maps
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos.
*/

#import <Maps/Presenter.h>
#import <UIKit/UIAdaptivePresentationControllerDelegate.h>

@class NSString;

@interface ModalPresenter : Presenter <UIAdaptivePresentationControllerDelegate> {

	BOOL _modalsThatComposeOverBackgroundTakeOverScreen;
	BOOL _presentsViewControllerInNavigationController;
	long long _adaptivePresentationStyle;
	long long _presentationStyle;
	/*^block*/id _navigationControllerCreationBlock;

}

@property (assign,nonatomic) long long presentationStyle;                                     //@synthesize presentationStyle=_presentationStyle - In the implementation block
@property (assign,nonatomic) long long adaptivePresentationStyle;                             //@synthesize adaptivePresentationStyle=_adaptivePresentationStyle - In the implementation block
@property (assign,nonatomic) BOOL modalsThatComposeOverBackgroundTakeOverScreen;              //@synthesize modalsThatComposeOverBackgroundTakeOverScreen=_modalsThatComposeOverBackgroundTakeOverScreen - In the implementation block
@property (assign,nonatomic) BOOL presentsViewControllerInNavigationController;               //@synthesize presentsViewControllerInNavigationController=_presentsViewControllerInNavigationController - In the implementation block
@property (nonatomic,copy) id navigationControllerCreationBlock;                              //@synthesize navigationControllerCreationBlock=_navigationControllerCreationBlock - In the implementation block
@property (readonly) unsigned long long hash; 
@property (readonly) Class superclass; 
@property (copy,readonly) NSString * description; 
@property (copy,readonly) NSString * debugDescription; 
+(/*^block*/id)creationBlockForModalPresentersWithPresentationStyle:(long long)arg1 ;
+(BOOL)presentationIsOpaqueForPresentationStyle:(long long)arg1 ;
+(id)useModalPresentationStyle:(long long)arg1 forAdaptivePresenter:(id)arg2 when:(id)arg3 ;
+(BOOL)defaultPresentationIsOpaque;
-(id)initWithPresentedViewController:(id)arg1 dismissalBlock:(/*^block*/id)arg2 ;
-(void)setPresentationStyle:(long long)arg1 ;
-(void)setAdaptivePresentationStyle:(long long)arg1 ;
-(void)_performPresentationOfViewController:(id)arg1 fromViewController:(id)arg2 animated:(BOOL)arg3 completion:(/*^block*/id)arg4 ;
-(void)_performDismissalAnimated:(BOOL)arg1 ;
-(void)setPresentsViewControllerInNavigationController:(BOOL)arg1 ;
-(void)setNavigationControllerCreationBlock:(id)arg1 ;
-(BOOL)modalsThatComposeOverBackgroundTakeOverScreen;
-(BOOL)presentsViewControllerInNavigationController;
-(id)navigationControllerCreationBlock;
-(void)willPresentViewControllerAnimated:(BOOL)arg1 ;
-(void)setModalsThatComposeOverBackgroundTakeOverScreen:(BOOL)arg1 ;
-(long long)presentationStyle;
-(long long)adaptivePresentationStyleForPresentationController:(id)arg1 ;
-(long long)adaptivePresentationStyle;
@end

