/*
* This header is generated by classdump-dyld 1.0
* on Tuesday, June 5, 2018 at 6:38:23 PM China Standard Time
* Operating System: Version 8.2 (Build 12D508)
* Image Source: /private/var/db/stash/_.8k0vmU/Applications/Maps.app/Maps
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos.
*/

#import <Maps/SearchResult.h>

@interface POIPlaceholderSearchResult : SearchResult {

	BOOL _temporary;

}

@property (getter=isTemporary,nonatomic,readonly) BOOL temporary;              //@synthesize temporary=_temporary - In the implementation block
-(id)initWithLabelMarker:(id)arg1 ;
-(BOOL)isTemporary;
-(BOOL)isPlaceHolder;
@end

