/*
* This header is generated by classdump-dyld 1.0
* on Tuesday, June 5, 2018 at 6:38:24 PM China Standard Time
* Operating System: Version 8.2 (Build 12D508)
* Image Source: /private/var/db/stash/_.8k0vmU/Applications/Maps.app/Maps
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos.
*/

#import <Maps/Maps-Structs.h>
#import <Maps/Presenter.h>
#import <UIKit/UIPopoverPresentationControllerDelegate.h>

@class NSString;

@interface PopoverPresenter : Presenter <UIPopoverPresentationControllerDelegate> {

	BOOL _presentsViewControllerInNavigationController;
	/*^block*/id _navigationControllerCreationBlock;

}

@property (assign,nonatomic) CGSize popoverContentSize; 
@property (assign,nonatomic) BOOL presentsViewControllerInNavigationController;              //@synthesize presentsViewControllerInNavigationController=_presentsViewControllerInNavigationController - In the implementation block
@property (nonatomic,copy) id navigationControllerCreationBlock;                             //@synthesize navigationControllerCreationBlock=_navigationControllerCreationBlock - In the implementation block
@property (readonly) unsigned long long hash; 
@property (readonly) Class superclass; 
@property (copy,readonly) NSString * description; 
@property (copy,readonly) NSString * debugDescription; 
+(id)traitsConditionWhenPopoverInappropriate;
-(void)_didDismiss;
-(void)_performPresentationOfViewController:(id)arg1 fromViewController:(id)arg2 animated:(BOOL)arg3 completion:(/*^block*/id)arg4 ;
-(void)_performDismissalAnimated:(BOOL)arg1 ;
-(void)setPresentsViewControllerInNavigationController:(BOOL)arg1 ;
-(void)setNavigationControllerCreationBlock:(id)arg1 ;
-(BOOL)presentsViewControllerInNavigationController;
-(id)navigationControllerCreationBlock;
-(void)willPresentPopoverAnimated:(BOOL)arg1 ;
-(BOOL)popoverPresentationControllerShouldDismissPopover:(id)arg1 ;
-(void)popoverPresentationControllerDidDismissPopover:(id)arg1 ;
-(void)popoverPresentationController:(id)arg1 willRepositionPopoverToRect:(inout CGRect*)arg2 inView:(inout id*)arg3 ;
-(CGSize)popoverContentSize;
-(void)setPopoverContentSize:(CGSize)arg1 ;
@end

