/*
* This header is generated by classdump-dyld 1.0
* on Tuesday, June 5, 2018 at 6:38:24 PM China Standard Time
* Operating System: Version 8.2 (Build 12D508)
* Image Source: /private/var/db/stash/_.8k0vmU/Applications/Maps.app/Maps
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos.
*/

#import <Maps/RAPQuestion.h>

@class RAPCommentQuestion, NSString;

@interface RAPPlaceClosureQuestion : RAPQuestion {

	RAPCommentQuestion* _commentQuestion;

}

@property (nonatomic,readonly) NSString * localizedConfirmationText; 
@property (nonatomic,readonly) RAPCommentQuestion * commentQuestion;              //@synthesize commentQuestion=_commentQuestion - In the implementation block
-(RAPCommentQuestion *)commentQuestion;
-(void)_fillSubmittableProblem:(id)arg1 ;
-(NSString *)localizedConfirmationText;
-(BOOL)isComplete;
@end

