/*
* This header is generated by classdump-dyld 1.0
* on Tuesday, June 5, 2018 at 6:38:22 PM China Standard Time
* Operating System: Version 8.2 (Build 12D508)
* Image Source: /private/var/db/stash/_.8k0vmU/Applications/Maps.app/Maps
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos.
*/

#import <UIKit/UITableViewDataSource.h>

@protocol RAPPresentingViewController;
@class UIViewController, NSMutableArray, UITableView, NSArray, NSString;

@interface RAPTablePartsDataSource : NSObject <UITableViewDataSource> {

	UIViewController*<RAPPresentingViewController> _presentingViewController;
	NSMutableArray* _tableParts;
	NSMutableArray* _tableSections;
	UITableView* _tableView;

}

@property (nonatomic,retain) UITableView * tableView;               //@synthesize tableView=_tableView - In the implementation block
@property (nonatomic,copy) NSArray * tableParts;                    //@synthesize tableParts=_tableParts - In the implementation block
@property (readonly) unsigned long long hash; 
@property (readonly) Class superclass; 
@property (copy,readonly) NSString * description; 
@property (copy,readonly) NSString * debugDescription; 
-(NSArray *)tableParts;
-(void)_clearPartsAndSections;
-(void)setTableParts:(id)arg1 withRowAnimation:(long long)arg2 ;
-(void)pushTablePart:(id)arg1 withRowAnimation:(long long)arg2 ;
-(void)popTablePart:(id)arg1 withRowAnimation:(long long)arg2 ;
-(void)_rebuildTableSections;
-(void)_createPartAndSectionArraysIfNeeded;
-(long long)indexOfSection:(id)arg1 ;
-(id)initWithPresentingViewController:(id)arg1 ;
-(void)setTableParts:(NSArray *)arg1 ;
-(void)tablePartDidChange:(id)arg1 ;
-(id)indexPathForRow:(long long)arg1 ofSection:(id)arg2 ;
-(void)dealloc;
-(long long)tableView:(id)arg1 numberOfRowsInSection:(long long)arg2 ;
-(id)tableView:(id)arg1 cellForRowAtIndexPath:(id)arg2 ;
-(long long)numberOfSectionsInTableView:(id)arg1 ;
-(id)tableView:(id)arg1 titleForHeaderInSection:(long long)arg2 ;
-(id)tableView:(id)arg1 titleForFooterInSection:(long long)arg2 ;
-(BOOL)tableView:(id)arg1 canEditRowAtIndexPath:(id)arg2 ;
-(void)tableView:(id)arg1 commitEditingStyle:(long long)arg2 forRowAtIndexPath:(id)arg3 ;
-(void)setTableView:(UITableView *)arg1 ;
-(UITableView *)tableView;
-(id)sectionAtIndex:(long long)arg1 ;
@end

