/*
* This header is generated by classdump-dyld 1.0
* on Tuesday, June 5, 2018 at 6:38:24 PM China Standard Time
* Operating System: Version 8.2 (Build 12D508)
* Image Source: /private/var/db/stash/_.8k0vmU/Applications/Maps.app/Maps
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos.
*/

#import <Maps/RAPTablePartSection.h>

@class NSString, NSArray;

@interface RAPTableCheckmarkRadioSection : RAPTablePartSection {

	id _owner;
	Class _defaultCellClass;
	/*^block*/id _dequeue;
	/*^block*/id _configure;
	/*^block*/id _selection;
	/*^block*/id _presentOverflow;
	NSString* _overflowTitleNoValues;
	NSString* _overflowTitleWithValues;
	BOOL _selectedValueIsOverflowSelection;
	BOOL _isDequeueingCellForOverflowSelection;
	BOOL _showsOverflowCell;
	NSArray* _values;
	id _selectedValue;

}

@property (nonatomic,copy) NSArray * values;                      //@synthesize values=_values - In the implementation block
@property (nonatomic,retain) id selectedValue;                    //@synthesize selectedValue=_selectedValue - In the implementation block
@property (assign,nonatomic) BOOL showsOverflowCell;              //@synthesize showsOverflowCell=_showsOverflowCell - In the implementation block
-(id)selectedValue;
-(id)initWithOwner:(id)arg1 defaultCellClass:(Class)arg2 dequeueForValue:(/*^block*/id)arg3 configureForValue:(/*^block*/id)arg4 selection:(/*^block*/id)arg5 presentOverflow:(/*^block*/id)arg6 ;
-(void)setSelectedValue:(id)arg1 ;
-(void)registerReuseIdentifiersForCells;
-(id)cellForRowAtIndex:(long long)arg1 ;
-(void)didSelectCellForRowAtIndex:(long long)arg1 tableIndexPath:(id)arg2 ;
-(id)dequeueCellForValue:(id)arg1 ;
-(void)selectedValueDidChange;
-(BOOL)showsOverflowCell;
-(Class)defaultCellClass;
-(void)configureCell:(id)arg1 forValue:(id)arg2 isOverflowSelection:(BOOL)arg3 ;
-(void)configureCell:(id)arg1 forValue:(id)arg2 ;
-(long long)_overflowCellIndex;
-(long long)_overflowSelectionCellIndex;
-(id)_effectiveOverflowCellTitle;
-(id)dequeueCellForValue:(id)arg1 isOverflowSelection:(BOOL)arg2 ;
-(void)presentOverflow;
-(void)setShowsOverflowCell:(BOOL)arg1 ;
-(id)overflowCellTitleWithOtherValuesPresent:(BOOL)arg1 ;
-(void)setOverflowCellTitle:(id)arg1 forDisplayWhenOtherValuesPresent:(BOOL)arg2 ;
-(id)init;
-(void)setValues:(NSArray *)arg1 ;
-(NSArray *)values;
-(long long)rowsCount;
@end

