/*
* This header is generated by classdump-dyld 1.0
* on Tuesday, June 5, 2018 at 6:38:22 PM China Standard Time
* Operating System: Version 8.2 (Build 12D508)
* Image Source: /private/var/db/stash/_.8k0vmU/Applications/Maps.app/Maps
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos.
*/

#import <Maps/RouteStepLabelListView.h>

@interface RouteMiddleStepLabelListView : RouteStepLabelListView
+(id)stringsForRoute:(id)arg1 step:(id)arg2 tableMode:(BOOL)arg3 ;
+(id)fontsForStrings:(id)arg1 route:(id)arg2 step:(id)arg3 tableMode:(BOOL)arg4 ;
+(id)voiceOverStringsForRoute:(id)arg1 step:(id)arg2 tableMode:(BOOL)arg3 ;
+(id)stringsForRoute:(id)arg1 step:(id)arg2 tableMode:(BOOL)arg3 isPrinting:(BOOL)arg4 ;
+(id)stringsForRoute:(id)arg1 step:(id)arg2 tableMode:(BOOL)arg3 isPrinting:(BOOL)arg4 forAccessibility:(BOOL)arg5 ;
@end

