/*
* This header is generated by classdump-dyld 1.0
* on Tuesday, June 5, 2018 at 6:38:22 PM China Standard Time
* Operating System: Version 8.2 (Build 12D508)
* Image Source: /private/var/db/stash/_.8k0vmU/Applications/Maps.app/Maps
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos.
*/

#import <Maps/PersistentSearchResultHistoryItem.h>
#import <Maps/HistoryItem.h>

@class NSString;

@interface SearchResultHistoryItem : PersistentSearchResultHistoryItem <HistoryItem>

@property (readonly) unsigned long long hash; 
@property (readonly) Class superclass; 
@property (copy,readonly) NSString * description; 
@property (copy,readonly) NSString * debugDescription; 
-(id)initWithSearchResult:(id)arg1 ;
-(double)timestamp;
-(int)type;
@end

