/*
* This header is generated by classdump-dyld 1.0
* on Tuesday, June 5, 2018 at 6:38:24 PM China Standard Time
* Operating System: Version 8.2 (Build 12D508)
* Image Source: /private/var/db/stash/_.8k0vmU/Applications/Maps.app/Maps
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos.
*/

#import <Maps/StarkTableViewController.h>

@class SearchInfo;

@interface StarkDisambiguationViewController : StarkTableViewController {

	SearchInfo* _searchInfo;
	/*^block*/id _result;

}
-(id)initWithSearchInfo:(id)arg1 completionBlock:(/*^block*/id)arg2 ;
-(void)_cancel:(id)arg1 ;
-(void)tableView:(id)arg1 didSelectRowAtIndexPath:(id)arg2 ;
-(long long)tableView:(id)arg1 numberOfRowsInSection:(long long)arg2 ;
-(id)tableView:(id)arg1 cellForRowAtIndexPath:(id)arg2 ;
-(void)viewDidLoad;
@end

