/*
* This header is generated by classdump-dyld 1.0
* on Tuesday, June 5, 2018 at 6:38:22 PM China Standard Time
* Operating System: Version 8.2 (Build 12D508)
* Image Source: /private/var/db/stash/_.8k0vmU/Applications/Maps.app/Maps
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos.
*/


@interface StarkWaypointsController : NSObject
-(void)nextPlaceWithTraits:(id)arg1 ;
-(void)previousPlaceWithTraits:(id)arg1 ;
-(void)startLoadWithTraits:(id)arg1 ;
-(id)destinationSearchResultIfAvailable;
-(id)titleForCurrentDestination;
-(id)subtitleForCurrentDestination;
-(unsigned long long)indexOfCurrentDestination;
-(unsigned long long)totalDestinations;
-(id)destinationWaypoint;
@end

