/*
* This header is generated by classdump-dyld 1.0
* on Tuesday, June 5, 2018 at 6:38:23 PM China Standard Time
* Operating System: Version 8.2 (Build 12D508)
* Image Source: /private/var/db/stash/_.8k0vmU/Applications/Maps.app/Maps
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos.
*/

#import <UIKit/UIViewController.h>
#import <Maps/SearchCompletionsTableViewControllerDelegate.h>
#import <Maps/StarkSearchBarViewDelegate.h>
#import <UIKit/UIKeyboardImplGeometryDelegate.h>

@class StarkSearchKeyboardContainerView, StarkSearchBarView, SearchCompletionsTableViewController, UIKeyboard, StarkChromeViewController, NSString;

@interface StarkSearchKeyboardInputViewController : UIViewController <SearchCompletionsTableViewControllerDelegate, StarkSearchBarViewDelegate, UIKeyboardImplGeometryDelegate> {

	StarkSearchKeyboardContainerView* _containerView;
	StarkSearchBarView* _searchBar;
	SearchCompletionsTableViewController* _completionsTable;
	UIKeyboard* _keyboard;
	StarkChromeViewController* _chrome;
	BOOL _minimized;

}

@property (readonly) unsigned long long hash; 
@property (readonly) Class superclass; 
@property (copy,readonly) NSString * description; 
@property (copy,readonly) NSString * debugDescription; 
@property (assign,getter=isMinimized,nonatomic) BOOL minimized;              //@synthesize minimized=_minimized - In the implementation block
-(void)modeWillPop;
-(void)updateKeyboardEnabled;
-(void)activateKeyboardIfNecessary;
-(void)searchCompletionsTableViewController:(id)arg1 didSelectHistoryItem:(id)arg2 forQuery:(id)arg3 ;
-(void)searchCompletionsTableViewController:(id)arg1 didSelectQueryCompletion:(id)arg2 forQuery:(id)arg3 ;
-(void)searchCompletionsTableViewController:(id)arg1 didSelectSearchCompletion:(id)arg2 forQuery:(id)arg3 ;
-(void)starkSearchBar:(id)arg1 willEditSearchTextToString:(id)arg2 ;
-(void)starkSearchBarChosePerformSearch:(id)arg1 ;
-(void)starkSearchBarChoseCancel:(id)arg1 ;
-(void)dealloc;
-(id)init;
-(BOOL)isActive;
-(void)viewWillLayoutSubviews;
-(void)viewDidLoad;
-(void)viewDidAppear:(BOOL)arg1 ;
-(BOOL)isMinimized;
-(BOOL)shouldSaveMinimizationState;
-(void)setMinimized:(BOOL)arg1 ;
-(BOOL)canDismiss;
-(void)prepareForImplBoundsHeightChange:(double)arg1 suppressNotification:(BOOL)arg2 ;
-(void)implBoundsHeightChangeDone:(double)arg1 suppressNotification:(BOOL)arg2 ;
@end

