/*
* This header is generated by classdump-dyld 1.0
* on Tuesday, June 5, 2018 at 6:38:23 PM China Standard Time
* Operating System: Version 8.2 (Build 12D508)
* Image Source: /private/var/db/stash/_.8k0vmU/Applications/Maps.app/Maps
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos.
*/

#import <Maps/StarkTableViewController.h>
#import <Maps/DirectionsManagerObserver.h>

@class NSArray, UIBarButtonItem, NSString;

@interface StarkDirectionsListViewController : StarkTableViewController <DirectionsManagerObserver> {

	/*^block*/id _completion;
	NSArray* _steps;
	long long _stepIndex;
	BOOL _needsToScroll;
	BOOL _hasUserScrolled;
	UIBarButtonItem* _doneBarButtonItem;

}

@property (nonatomic,readonly) UIBarButtonItem * doneBarButtonItem;              //@synthesize doneBarButtonItem=_doneBarButtonItem - In the implementation block
@property (readonly) unsigned long long hash; 
@property (readonly) Class superclass; 
@property (copy,readonly) NSString * description; 
@property (copy,readonly) NSString * debugDescription; 
-(void)tableViewWillScrollFromMoveEvent:(id)arg1 ;
-(void)directionsManagerDidSwitchToNewRoute:(id)arg1 route:(id)arg2 ;
-(void)directionsManagerDidUpdateToStepIndex:(id)arg1 stepIndex:(id)arg2 ;
-(void)_updateSteps;
-(void)_scrollToCurrentStepIfNeeded:(BOOL)arg1 ;
-(void)directionsManager:(id)arg1 didReplaceRoute:(id)arg2 withRoute:(id)arg3 ;
-(UIBarButtonItem *)doneBarButtonItem;
-(void)dealloc;
-(double)tableView:(id)arg1 heightForRowAtIndexPath:(id)arg2 ;
-(void)scrollViewWillBeginDragging:(id)arg1 ;
-(long long)tableView:(id)arg1 numberOfRowsInSection:(long long)arg2 ;
-(id)tableView:(id)arg1 cellForRowAtIndexPath:(id)arg2 ;
-(long long)numberOfSectionsInTableView:(id)arg1 ;
-(void)viewDidLayoutSubviews;
-(void)viewWillAppear:(BOOL)arg1 ;
-(void)viewDidAppear:(BOOL)arg1 ;
-(id)initWithCompletion:(/*^block*/id)arg1 ;
-(void)_done;
@end

