/*
* This header is generated by classdump-dyld 1.0
* on Tuesday, June 5, 2018 at 6:38:24 PM China Standard Time
* Operating System: Version 8.2 (Build 12D508)
* Image Source: /private/var/db/stash/_.8k0vmU/Applications/Maps.app/Maps
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos.
*/


@protocol StarkRoutePreviewOverlayDelegate <NSObject>
@required
-(void)routePreviewSignSelectedNext:(id)arg1;
-(void)routePreviewSignSelectedPrevious:(id)arg1;
-(void)routePreviewSign:(id)arg1 isShowingAlternates:(BOOL)arg2;
-(void)routePreviewSign:(id)arg1 selectedAlternateRouteAtIndex:(unsigned long long)arg2;

@end

