/*
* This header is generated by classdump-dyld 1.0
* on Tuesday, June 5, 2018 at 6:38:22 PM China Standard Time
* Operating System: Version 8.2 (Build 12D508)
* Image Source: /private/var/db/stash/_.8k0vmU/Applications/Maps.app/Maps
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos.
*/

#import <UIKit/UIView.h>

@interface StarkTableViewCellContentView : UIView {

	/*^block*/id _layoutHandler;

}

@property (nonatomic,copy) id layoutHandler;              //@synthesize layoutHandler=_layoutHandler - In the implementation block
-(id)layoutHandler;
-(void)setLayoutHandler:(id)arg1 ;
-(void)layoutSubviews;
@end

