/*
* This header is generated by classdump-dyld 1.0
* on Tuesday, June 5, 2018 at 6:38:24 PM China Standard Time
* Operating System: Version 8.2 (Build 12D508)
* Image Source: /private/var/db/stash/_.8k0vmU/Applications/Maps.app/Maps
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos.
*/

#import <Maps/Maps-Structs.h>
#import <Maps/StarkButton.h>

@interface StarkFloatingButton : StarkButton {

	long long _starkFloatingButtonStyle;

}

@property (assign,nonatomic) long long starkFloatingButtonStyle;              //@synthesize starkFloatingButtonStyle=_starkFloatingButtonStyle - In the implementation block
-(void)setStarkFloatingButtonStyle:(long long)arg1 ;
-(long long)starkFloatingButtonStyle;
-(id)initWithFrame:(CGRect)arg1 ;
@end

