/*
* This header is generated by classdump-dyld 1.0
* on Tuesday, June 5, 2018 at 6:38:23 PM China Standard Time
* Operating System: Version 8.2 (Build 12D508)
* Image Source: /private/var/db/stash/_.8k0vmU/Applications/Maps.app/Maps
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos.
*/

#import <Maps/GEORouteHypothesizerDelegate.h>

@class NSHashTable, StarkSuggestion, GEORouteHypothesizer, GEORouteHypothesis, GEOURLRouteHandle, GEOComposedWaypoint, NSMutableArray, MNTraceRecorder, StarkRouteGeniusTestLogger, GEOComposedRoute, NSString, NSDate, NSArray;

@interface StarkLikelyRouteUpdater : NSObject <GEORouteHypothesizerDelegate> {

	NSHashTable* _observers;
	StarkSuggestion* _suggestion;
	GEORouteHypothesizer* _routeHypothesizer;
	GEORouteHypothesis* _lastHypothesis;
	GEOURLRouteHandle* _routeHandle;
	GEOComposedWaypoint* _source;
	GEOComposedWaypoint* _destination;
	double _remainingDistance;
	double _remainingTime;
	NSMutableArray* _trafficIncidents;
	MNTraceRecorder* _traceRecorder;
	BOOL _recordedInitialRoute;
	StarkRouteGeniusTestLogger* _testLogger;
	BOOL _isForegroundRoute;
	BOOL _isHighThermalPressureLevel;

}

@property (nonatomic,readonly) double score; 
@property (nonatomic,readonly) GEOComposedRoute * route; 
@property (nonatomic,readonly) StarkSuggestion * suggestion;                       //@synthesize suggestion=_suggestion - In the implementation block
@property (nonatomic,readonly) GEOURLRouteHandle * routeHandle;                    //@synthesize routeHandle=_routeHandle - In the implementation block
@property (nonatomic,readonly) NSString * name; 
@property (nonatomic,readonly) NSString * address; 
@property (nonatomic,readonly) double remainingDistance;                           //@synthesize remainingDistance=_remainingDistance - In the implementation block
@property (nonatomic,readonly) double remainingTime;                               //@synthesize remainingTime=_remainingTime - In the implementation block
@property (nonatomic,readonly) NSDate * etaFromLastLocation; 
@property (nonatomic,readonly) NSArray * trafficIncidents; 
@property (nonatomic,readonly) BOOL isUsingUsualRoute; 
@property (nonatomic,retain) StarkRouteGeniusTestLogger * testLogger;              //@synthesize testLogger=_testLogger - In the implementation block
@property (readonly) unsigned long long hash; 
@property (readonly) Class superclass; 
@property (copy,readonly) NSString * description; 
@property (copy,readonly) NSString * debugDescription; 
-(double)remainingDistance;
-(StarkSuggestion *)suggestion;
-(id)initWithSuggestion:(id)arg1 traceRecorder:(id)arg2 ;
-(void)setIsForegroundRoute:(BOOL)arg1 ;
-(void)updateThermalPressureLevel:(BOOL)arg1 ;
-(StarkRouteGeniusTestLogger *)testLogger;
-(void)setTestLogger:(StarkRouteGeniusTestLogger *)arg1 ;
-(void)_updateETAUpdateFrequency;
-(void)_updateRemainingTimeAndDistanceWithRouteMatch:(id)arg1 ;
-(NSDate *)etaFromLastLocation;
-(BOOL)isUsingUsualRoute;
-(NSString *)address;
-(NSString *)name;
-(void)removeObserver:(id)arg1 ;
-(void)addObserver:(id)arg1 ;
-(double)remainingTime;
-(GEOURLRouteHandle *)routeHandle;
-(void)routeHypothesizerArrived:(id)arg1 ;
-(void)routeHypothesizer:(id)arg1 matchedToRoute:(id)arg2 ;
-(void)routeHypothesizer:(id)arg1 willRequestNewRoute:(id)arg2 ;
-(void)routeHypothesizerRerouted:(id)arg1 request:(id)arg2 response:(id)arg3 ;
-(void)routeHypothesizer:(id)arg1 willSendETARequest:(id)arg2 ;
-(void)routeHypothesizer:(id)arg1 receivedETAResponse:(id)arg2 ;
-(void)routeHypothesizer:(id)arg1 receivedETAError:(id)arg2 ;
-(void)routeHypothesizerUpdatedETA:(id)arg1 etaRoute:(id)arg2 ;
-(double)score;
-(GEOComposedRoute *)route;
-(NSArray *)trafficIncidents;
-(void)updateLocation:(id)arg1 ;
@end

