/*
* This header is generated by classdump-dyld 1.0
* on Tuesday, June 5, 2018 at 6:38:23 PM China Standard Time
* Operating System: Version 8.2 (Build 12D508)
* Image Source: /private/var/db/stash/_.8k0vmU/Applications/Maps.app/Maps
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos.
*/

#import <Maps/Maps-Structs.h>
#import <UIKit/UIView.h>

@class UILabel, TwoPartETALabel, TwoPartTimeLabel, MapsAutoLayoutContext, NSTimeZone, NSString;

@interface StarkETAOnlyOverlaySign : UIView {

	UILabel* _titleLabel;
	TwoPartETALabel* _etaLabel;
	TwoPartTimeLabel* _durationLabel;
	MapsAutoLayoutContext* _layoutContext;
	double _remainingTime;
	NSTimeZone* _destinationTimezone;

}

@property (nonatomic,retain) NSString * title; 
@property (assign,nonatomic) double remainingTime;                          //@synthesize remainingTime=_remainingTime - In the implementation block
@property (nonatomic,retain) NSTimeZone * destinationTimezone;              //@synthesize destinationTimezone=_destinationTimezone - In the implementation block
+(BOOL)requiresConstraintBasedLayout;
-(void)setDestinationTimezone:(NSTimeZone *)arg1 ;
-(NSTimeZone *)destinationTimezone;
-(double)overlayHeight;
-(UIEdgeInsets)overlayPadding;
-(id)initWithFrame:(CGRect)arg1 ;
-(void)setTitle:(NSString *)arg1 ;
-(NSString *)title;
-(void)updateConstraints;
-(void)setRemainingTime:(double)arg1 ;
-(double)remainingTime;
@end

