/*
* This header is generated by classdump-dyld 1.0
* on Tuesday, June 5, 2018 at 6:38:23 PM China Standard Time
* Operating System: Version 8.2 (Build 12D508)
* Image Source: /private/var/db/stash/_.8k0vmU/Applications/Maps.app/Maps
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos.
*/

#import <Maps/AuxiliaryDebugViewController.h>
#import <Maps/GEOResourceManifestTileGroupObserver.h>

@protocol MapsDebugViewControllerDelegate;
@class GEOResourceManifestDownload, NSString;

@interface TileGroupInfoDebugController : AuxiliaryDebugViewController <GEOResourceManifestTileGroupObserver> {

	BOOL _canChangeActiveTileGroup;
	id<MapsDebugViewControllerDelegate> _delegate;
	long long tileGroupIdentifier;
	GEOResourceManifestDownload* _resourceManifest;

}

@property (assign,nonatomic) long long tileGroupIdentifier; 
@property (assign,nonatomic) BOOL canChangeActiveTileGroup;                               //@synthesize canChangeActiveTileGroup=_canChangeActiveTileGroup - In the implementation block
@property (nonatomic,retain) GEOResourceManifestDownload * resourceManifest;              //@synthesize resourceManifest=_resourceManifest - In the implementation block
@property (readonly) unsigned long long hash; 
@property (readonly) Class superclass; 
@property (copy,readonly) NSString * description; 
@property (copy,readonly) NSString * debugDescription; 
+(id)navigationDestinationTitle;
-(GEOResourceManifestDownload *)resourceManifest;
-(void)setCanChangeActiveTileGroup:(BOOL)arg1 ;
-(void)setResourceManifest:(GEOResourceManifestDownload *)arg1 ;
-(id)_tileGroup;
-(id)_resourceNames;
-(BOOL)canChangeActiveTileGroup;
-(void)dealloc;
-(void)setDelegate:(id)arg1 ;
-(void)tableView:(id)arg1 didSelectRowAtIndexPath:(id)arg2 ;
-(long long)tableView:(id)arg1 numberOfRowsInSection:(long long)arg2 ;
-(id)tableView:(id)arg1 cellForRowAtIndexPath:(id)arg2 ;
-(long long)numberOfSectionsInTableView:(id)arg1 ;
-(id)delegate;
-(id)initWithStyle:(long long)arg1 ;
-(void)setTileGroupIdentifier:(long long)arg1 ;
-(void)resourceManifestManagerWillChangeActiveTileGroup:(id)arg1 ;
-(void)resourceManifestManagerDidChangeActiveTileGroup:(id)arg1 ;
-(long long)tileGroupIdentifier;
@end

