/*
* This header is generated by classdump-dyld 1.0
* on Tuesday, June 5, 2018 at 10:35:58 PM China Standard Time
* Operating System: Version 8.2 (Build 12D508)
* Image Source: /private/var/db/stash/_.8k0vmU/Applications/MobileMail.app/MobileMail
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos.
*/

#import <UIKit/UIBarButtonItem.h>

@interface BarLabelItem : UIBarButtonItem {

	int _itemStyle;

}
+(id)_boldAttributes;
+(id)_defaultAttributes;
-(id)initWithTitle:(id)arg1 width:(double)arg2 style:(int)arg3 ;
-(id)initWithWidth:(double)arg1 style:(int)arg2 ;
-(void)setTitle:(id)arg1 ;
-(id)initWithTitle:(id)arg1 style:(int)arg2 ;
@end

