/*
* This header is generated by classdump-dyld 1.0
* on Tuesday, June 5, 2018 at 10:35:58 PM China Standard Time
* Operating System: Version 8.2 (Build 12D508)
* Image Source: /private/var/db/stash/_.8k0vmU/Applications/MobileMail.app/MobileMail
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos.
*/

#import <MobileMail/MailStatusLabelView.h>

@class UIProgressView;

@interface MailStatusProgressBarView : MailStatusLabelView {

	UIProgressView* _progressView;
	float _filler;
	int _countUsedUp;
	float _lastProgress;
	int _lastUsedCount;
	int _lastUsedTotal;

}

@property (nonatomic,retain) UIProgressView * progressView;              //@synthesize progressView=_progressView - In the implementation block
-(id)getStatusAndProgress:(float*)arg1 ;
-(void)dealloc;
-(void)removeFromSuperview;
-(void)update;
-(void)setProgressView:(UIProgressView *)arg1 ;
-(UIProgressView *)progressView;
@end

