/*
* This header is generated by classdump-dyld 1.0
* on Tuesday, June 5, 2018 at 10:35:58 PM China Standard Time
* Operating System: Version 8.2 (Build 12D508)
* Image Source: /private/var/db/stash/_.8k0vmU/Applications/MobileMail.app/MobileMail
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos.
*/

#import <MobileMail/MFNanoBridgeSettingsMailbox.h>
#import <MobileMail/NSSecureCoding.h>

@class MFMailboxUid, NSURL, NSString;

@interface MFNanoBridgeSettingsAccountSpecificMailbox : MFNanoBridgeSettingsMailbox <NSSecureCoding> {

	MFMailboxUid* _mailboxUid;
	NSURL* _mailboxURL;
	NSString* _accountUniqueIdentifier;

}

@property (nonatomic,readonly) NSString * accountUniqueIdentifier;              //@synthesize accountUniqueIdentifier=_accountUniqueIdentifier - In the implementation block
@property (nonatomic,readonly) NSURL * mailboxURL;                              //@synthesize mailboxURL=_mailboxURL - In the implementation block
@property (nonatomic,readonly) int type; 
+(BOOL)supportsSecureCoding;
-(id)icon;
-(void)dealloc;
-(id)initWithCoder:(id)arg1 ;
-(void)encodeWithCoder:(id)arg1 ;
-(BOOL)isEqual:(id)arg1 ;
-(BOOL)isValid;
-(int)type;
-(unsigned long long)level;
-(id)displayName;
-(id)initWithMailboxUid:(id)arg1 ;
-(id)initWithAccountUniqueIdentifier:(id)arg1 mailboxURL:(id)arg2 ;
-(id)_mailboxUid;
-(NSURL *)mailboxURL;
-(void)invalidateCachedData;
-(NSString *)accountUniqueIdentifier;
@end

