/*
* This header is generated by classdump-dyld 1.0
* on Tuesday, June 5, 2018 at 10:35:58 PM China Standard Time
* Operating System: Version 8.2 (Build 12D508)
* Image Source: /private/var/db/stash/_.8k0vmU/Applications/MobileMail.app/MobileMail
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos.
*/

#import <MobileMail/LibrarySearchSource.h>

@interface SecondaryLibrarySearchSource : LibrarySearchSource
-(BOOL)representsMailboxUid:(id)arg1 ;
-(id)mailboxUids;
-(BOOL)representsMailboxID:(unsigned)arg1 ;
-(void)_messagesAdded:(id)arg1 ;
-(id)_baseCriterionFromSources:(id)arg1 ;
-(id)_performSearchUsingManager:(id)arg1 usingSearchContext:(id)arg2 ;
@end

