/*
* This header is generated by classdump-dyld 1.0
* on Tuesday, June 5, 2018 at 10:35:58 PM China Standard Time
* Operating System: Version 8.2 (Build 12D508)
* Image Source: /private/var/db/stash/_.8k0vmU/Applications/MobileMail.app/MobileMail
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos.
*/


@protocol StackDataSource
@required
-(id)defaultViewForStackController:(id)arg1;
-(id)stackContainerViewForStackController:(id)arg1;
-(UIEdgeInsets*)stackContainerViewEdgeInsetsForStackController:(id)arg1;
-(id)defaultItemForStackController:(id)arg1;
-(id)stackController:(id)arg1 viewForItem:(id)arg2;
-(BOOL)stackController:(id)arg1 isDataLoadedForItem:(id)arg2 inView:(id)arg3;
-(void)stackController:(id)arg1 loadDataForItem:(id)arg2 inView:(id)arg3;

@end

