/*
* This header is generated by classdump-dyld 1.0
* on Tuesday, June 5, 2018 at 6:32:08 PM China Standard Time
* Operating System: Version 8.2 (Build 12D508)
* Image Source: /private/var/db/stash/_.8k0vmU/Applications/MobileTimer.app/MobileTimer
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos.
*/

#import <UIKit/UITableViewCell.h>
#import <MobileTimer/StopWatchLapCell.h>

@class UILabel, NSString;

@interface LapTableViewCell : UITableViewCell <StopWatchLapCell> {

	UILabel* _lapLabel;
	UILabel* _timeLabel;
	long long _lap;
	double _time;

}

@property (assign,nonatomic) long long lap;                         //@synthesize lap=_lap - In the implementation block
@property (assign,nonatomic) double time;                           //@synthesize time=_time - In the implementation block
@property (readonly) unsigned long long hash; 
@property (readonly) Class superclass; 
@property (copy,readonly) NSString * description; 
@property (copy,readonly) NSString * debugDescription; 
+(double)rowHeight;
-(void)handleLocaleChange;
-(void)setLap:(long long)arg1 ;
-(id)lapLabelTextForNumber:(long long)arg1 ;
-(void)setupLapFormatter;
-(void)resetLapFormatter;
-(id)_accessibilityFormatTime:(double)arg1 showHours:(BOOL*)arg2 showSubseconds:(BOOL)arg3 ;
-(long long)lap;
-(void)dealloc;
-(id)init;
-(void)layoutSubviews;
-(void)setTime:(double)arg1 ;
-(double)time;
@end

