/*
* This header is generated by classdump-dyld 1.0
* on Tuesday, June 5, 2018 at 5:31:43 PM China Standard Time
* Operating System: Version 8.2 (Build 12D508)
* Image Source: /private/var/db/stash/_.8k0vmU/Applications/Weather.app/Weather
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos.
*/

#import <Weather/Weather-Structs.h>
#import <UIKit/UIView.h>

@class NSArray;

@interface WACityDetailsView : UIView {

	NSArray* _titleLabels;
	NSArray* _valueLabels;
	BOOL _useCompactLayout;
	double _lineHeight;
	unsigned long long _lastDetailToShow;

}

@property (assign,nonatomic) BOOL useCompactLayout;                            //@synthesize useCompactLayout=_useCompactLayout - In the implementation block
@property (assign,nonatomic) double lineHeight;                                //@synthesize lineHeight=_lineHeight - In the implementation block
@property (assign,nonatomic) unsigned long long lastDetailToShow;              //@synthesize lastDetailToShow=_lastDetailToShow - In the implementation block
+(double)defaultLineHeight;
+(id)_font;
-(void)_setTitle:(id)arg1 forDetail:(unsigned long long)arg2 ;
-(id)valueLabelForDetail:(unsigned long long)arg1 ;
-(id)titleLabelForDetail:(unsigned long long)arg1 ;
-(double)_topToFirstBaselinePadding;
-(double)_interGroupPadding;
-(unsigned long long)lastDetailToShow;
-(double)_baselineOffsetForDetailLabel:(unsigned long long)arg1 ;
-(double)_lastBaselineToBottomPadding;
-(id)_leftLabelForDetail:(unsigned long long)arg1 ;
-(id)_rightLabelForDetail:(unsigned long long)arg1 ;
-(void)setTitle:(id)arg1 value:(id)arg2 forDetail:(unsigned long long)arg3 ;
-(void)setTitle:(id)arg1 attributedValue:(id)arg2 forDetail:(unsigned long long)arg3 ;
-(void)clearDetailsText;
-(void)setUseCompactLayout:(BOOL)arg1 ;
-(void)setLastDetailToShow:(unsigned long long)arg1 ;
-(BOOL)useCompactLayout;
-(id)initWithFrame:(CGRect)arg1 ;
-(void)dealloc;
-(void)layoutSubviews;
-(double)lineHeight;
-(CGSize)intrinsicContentSize;
-(void)setLineHeight:(double)arg1 ;
@end

