/*
* This header is generated by classdump-dyld 1.0
* on Tuesday, June 5, 2018 at 10:39:49 PM China Standard Time
* Operating System: Version 8.2 (Build 12D508)
* Image Source: /private/var/db/stash/_.8k0vmU/Applications/Podcasts.app/Podcasts
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos.
*/


@class NSString, NSArray;

@interface AEAnnotationCSKeyGroup : NSObject {

	NSString* _keyPrefix;
	NSArray* _annotationTypes;
	long long _index;

}

@property (nonatomic,retain) NSString * keyPrefix;                   //@synthesize keyPrefix=_keyPrefix - In the implementation block
@property (nonatomic,retain) NSArray * annotationTypes;              //@synthesize annotationTypes=_annotationTypes - In the implementation block
@property (assign,nonatomic) long long index;                        //@synthesize index=_index - In the implementation block
-(NSString *)keyPrefix;
-(void)setKeyPrefix:(NSString *)arg1 ;
-(void)setAnnotationTypes:(NSArray *)arg1 ;
-(NSArray *)annotationTypes;
-(void)dealloc;
-(long long)index;
-(void)setIndex:(long long)arg1 ;
@end

