/*
* This header is generated by classdump-dyld 1.0
* on Tuesday, June 5, 2018 at 10:39:49 PM China Standard Time
* Operating System: Version 8.2 (Build 12D508)
* Image Source: /private/var/db/stash/_.8k0vmU/Applications/Podcasts.app/Podcasts
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos.
*/

#import <Podcasts/Podcasts-Structs.h>
#import <Podcasts/AEUserPublishingDataSource.h>
#import <Podcasts/AEAssetHTMLGeneratorDataSource.h>

@class UIImage, NSURL, NSString;

@interface AEAssetActivityItemProviderSource : NSObject <AEUserPublishingDataSource, AEAssetHTMLGeneratorDataSource> {

	UIImage* _assetCover;
	NSURL* _storeUrl;
	NSURL* _storeShortUrl;
	BOOL _storeUrlRequested;
	BOOL _storeShortUrlRequested;
	NSString* _epubID;
	NSString* _storeId;
	/*^block*/id _propertySource;
	NSString* _activityType;

}

@property (nonatomic,copy) id propertySource;                       //@synthesize propertySource=_propertySource - In the implementation block
@property (nonatomic,retain) NSString * activityType;               //@synthesize activityType=_activityType - In the implementation block
@property (readonly) unsigned long long hash; 
@property (readonly) Class superclass; 
@property (copy,readonly) NSString * description; 
@property (copy,readonly) NSString * debugDescription; 
+(id)activityItemProviderWithPropertySource:(/*^block*/id)arg1 ;
+(id)citationWithPropertySource:(/*^block*/id)arg1 activityType:(id)arg2 storeURL:(id)arg3 pageRange:(NSRange)arg4 ;
-(id)initWithPropertySource:(/*^block*/id)arg1 ;
-(id)citation;
-(BOOL)isStoreAsset;
-(id)storeUrl;
-(id)storeShortUrl;
-(void)populateHTMLGenerator:(id)arg1 ;
-(BOOL)contentProtected;
-(id)readingDirection;
-(id)HTMLGenerator:(id)arg1 citationForStoreURL:(id)arg2 ;
-(id)propertySource;
-(void)setPropertySource:(id)arg1 ;
-(id)assetCover;
-(id)epubID;
-(id)publisherLocation;
-(id)publisherName;
-(id)publisherYear;
-(id)userPublishing:(id)arg1 storeURLForStoreId:(id)arg2 ;
-(id)userPublishing:(id)arg1 storeShortURLForStoreId:(id)arg2 ;
-(id)assetCoverForHTMLGenerator:(id)arg1 ;
-(id)storeURLForHTMLGenerator:(id)arg1 ;
-(id)checkOutBookWithShortCitationWithCharacterLimit:(unsigned long long)arg1 ;
-(void)dealloc;
-(id)title;
-(NSString *)activityType;
-(id)genre;
-(id)storeId;
-(id)author;
-(void)setActivityType:(NSString *)arg1 ;
@end

