/*
* This header is generated by classdump-dyld 1.0
* on Tuesday, June 5, 2018 at 10:39:49 PM China Standard Time
* Operating System: Version 8.2 (Build 12D508)
* Image Source: /private/var/db/stash/_.8k0vmU/Applications/Podcasts.app/Podcasts
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos.
*/

#import <Podcasts/Podcasts-Structs.h>
#import <UIKit/UIView.h>

@class UIColor;

@interface AENoteLinesView : UIView {

	BOOL _useHalfPixelAdjustment;
	double _lineHeight;
	UIColor* _lineColor;

}

@property (assign,nonatomic) double lineHeight;                        //@synthesize lineHeight=_lineHeight - In the implementation block
@property (nonatomic,retain) UIColor * lineColor;                      //@synthesize lineColor=_lineColor - In the implementation block
@property (assign,nonatomic) BOOL useHalfPixelAdjustment;              //@synthesize useHalfPixelAdjustment=_useHalfPixelAdjustment - In the implementation block
-(BOOL)useHalfPixelAdjustment;
-(void)setUseHalfPixelAdjustment:(BOOL)arg1 ;
-(id)initWithFrame:(CGRect)arg1 ;
-(void)dealloc;
-(void)drawRect:(CGRect)arg1 ;
-(double)lineHeight;
-(void)setLineHeight:(double)arg1 ;
-(UIColor *)lineColor;
-(void)setLineColor:(UIColor *)arg1 ;
@end

