/*
* This header is generated by classdump-dyld 1.0
* on Tuesday, June 5, 2018 at 10:39:49 PM China Standard Time
* Operating System: Version 8.2 (Build 12D508)
* Image Source: /private/var/db/stash/_.8k0vmU/Applications/Podcasts.app/Podcasts
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos.
*/


@class NSOperationQueue, ISOperationQueue, ISURLBag;

@interface IMBaseServiceSingletonContext : NSObject {

	NSOperationQueue* _bagQueue;
	ISOperationQueue* _mainQueue;
	ISURLBag* _bag;

}

@property (nonatomic,retain) ISOperationQueue * mainQueue;              //@synthesize mainQueue=_mainQueue - In the implementation block
@property (nonatomic,retain) ISURLBag * bag;                            //@synthesize bag=_bag - In the implementation block
-(void)setMainQueue:(ISOperationQueue *)arg1 ;
-(id)init;
-(ISOperationQueue *)mainQueue;
-(ISURLBag *)bag;
-(void)setBag:(ISURLBag *)arg1 ;
@end

