/*
* This header is generated by classdump-dyld 1.0
* on Tuesday, June 5, 2018 at 10:39:49 PM China Standard Time
* Operating System: Version 8.2 (Build 12D508)
* Image Source: /private/var/db/stash/_.8k0vmU/Applications/Podcasts.app/Podcasts
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos.
*/

#import <Podcasts/IMActivityItemSource.h>

@class NSString, NSArray;

@interface IMBlockActivityItemProvider : NSObject <IMActivityItemSource> {

	NSString* _UTI;
	/*^block*/id _resolutionBlock;
	NSArray* _supportedActivityTypes;
	NSString* _activityType;

}

@property (nonatomic,retain) NSString * UTI;                                //@synthesize UTI=_UTI - In the implementation block
@property (nonatomic,copy) id resolutionBlock;                              //@synthesize resolutionBlock=_resolutionBlock - In the implementation block
@property (nonatomic,retain) NSArray * supportedActivityTypes;              //@synthesize supportedActivityTypes=_supportedActivityTypes - In the implementation block
@property (nonatomic,retain) NSString * activityType;                       //@synthesize activityType=_activityType - In the implementation block
@property (readonly) unsigned long long hash; 
@property (readonly) Class superclass; 
@property (copy,readonly) NSString * description; 
@property (copy,readonly) NSString * debugDescription; 
-(id)resolutionBlock;
-(void)setResolutionBlock:(id)arg1 ;
-(NSArray *)supportedActivityTypes;
-(id)initWithUTI:(id)arg1 resolutionBlock:(/*^block*/id)arg2 ;
-(void)setSupportedActivityTypes:(NSArray *)arg1 ;
-(void)dealloc;
-(NSString *)activityType;
-(NSString *)UTI;
-(id)activityViewControllerPlaceholderItem:(id)arg1 ;
-(id)activityViewController:(id)arg1 itemForActivityType:(id)arg2 ;
-(void)setUTI:(NSString *)arg1 ;
-(void)setActivityType:(NSString *)arg1 ;
@end

