/*
* This header is generated by classdump-dyld 1.0
* on Tuesday, June 5, 2018 at 10:39:49 PM China Standard Time
* Operating System: Version 8.2 (Build 12D508)
* Image Source: /private/var/db/stash/_.8k0vmU/Applications/Podcasts.app/Podcasts
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos.
*/


@class NSMutableArray;

@interface IMHTMLStripper : NSObject {

	BOOL _convertListItems;
	NSMutableArray* _enclosingListTags;
	unsigned long long _orderedListItemCount;

}

@property (assign,nonatomic) BOOL convertListItems;                                //@synthesize convertListItems=_convertListItems - In the implementation block
@property (nonatomic,retain) NSMutableArray * enclosingListTags;                   //@synthesize enclosingListTags=_enclosingListTags - In the implementation block
@property (assign,nonatomic) unsigned long long orderedListItemCount;              //@synthesize orderedListItemCount=_orderedListItemCount - In the implementation block
+(id)extractPlainTextBody:(id)arg1 ;
-(id)replacementStringForTag:(id)arg1 isStartTag:(BOOL)arg2 ;
-(BOOL)convertListItems;
-(NSMutableArray *)enclosingListTags;
-(unsigned long long)orderedListItemCount;
-(void)setOrderedListItemCount:(unsigned long long)arg1 ;
-(void)setConvertListItems:(BOOL)arg1 ;
-(id)htmlBody:(id)arg1 ;
-(id)stripHTMLString:(id)arg1 ;
-(void)setEnclosingListTags:(NSMutableArray *)arg1 ;
-(void)dealloc;
@end

