/*
* This header is generated by classdump-dyld 1.0
* on Tuesday, June 5, 2018 at 10:39:48 PM China Standard Time
* Operating System: Version 8.2 (Build 12D508)
* Image Source: /private/var/db/stash/_.8k0vmU/Applications/Podcasts.app/Podcasts
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos.
*/

#import <Podcasts/Podcasts-Structs.h>
#import <Podcasts/IMLibraryBooksViewController.h>
#import <Podcasts/IMGridViewDelegate.h>
#import <Podcasts/IMGridViewDataSource.h>
#import <UIKit/UITextFieldDelegate.h>

@class IMGridView, IMBookshelfBackgroundView, IMBookshelfImageConfiguration, NSString;

@interface IMLibraryBookshelfViewController : IMLibraryBooksViewController <IMGridViewDelegate, IMGridViewDataSource, UITextFieldDelegate> {

	IMGridView* _gridView;
	double _shelfHeight;
	CGSize _landscapeSize;
	CGSize _portraitSize;
	CGSize _alternateLandscapeSize;
	IMBookshelfBackgroundView* _background;
	IMBookshelfImageConfiguration* _bookshelfImageConfiguration;

}

@property (assign,nonatomic) CGSize landscapeSize;                                                     //@synthesize landscapeSize=_landscapeSize - In the implementation block
@property (assign,nonatomic) CGSize portraitSize;                                                      //@synthesize portraitSize=_portraitSize - In the implementation block
@property (assign,nonatomic) CGSize alternateLandscapeSize;                                            //@synthesize alternateLandscapeSize=_alternateLandscapeSize - In the implementation block
@property (nonatomic,retain) IMBookshelfImageConfiguration * bookshelfImageConfiguration;              //@synthesize bookshelfImageConfiguration=_bookshelfImageConfiguration - In the implementation block
@property (readonly) unsigned long long hash; 
@property (readonly) Class superclass; 
@property (copy,readonly) NSString * description; 
@property (copy,readonly) NSString * debugDescription; 
-(long long)gridView:(id)arg1 willSelectItemAtIndex:(long long)arg2 ;
-(void)gridView:(id)arg1 didSelectItemAtIndex:(long long)arg2 ;
-(BOOL)gridView:(id)arg1 canDeleteCellAtIndex:(long long)arg2 ;
-(BOOL)gridView:(id)arg1 canMoveCellAtIndex:(long long)arg2 ;
-(void)gridView:(id)arg1 moveCellAtIndex:(long long)arg2 toIndex:(long long)arg3 ;
-(void)gridView:(id)arg1 willGrabCell:(id)arg2 ;
-(long long)numberOfCellsInGridView:(id)arg1 ;
-(id)gridView:(id)arg1 cellForIndex:(long long)arg2 ;
-(id)initWithShelfHeight:(double)arg1 ;
-(id)initWithNibName:(id)arg1 bundle:(id)arg2 shelfHeight:(double)arg3 ;
-(void)releaseViews;
-(IMBookshelfImageConfiguration *)bookshelfImageConfiguration;
-(CGSize)alternateLandscapeSize;
-(void)_setupGestureRecognizers;
-(void)repopulateDisplay;
-(void)setEmbeddedToolbarItems:(id)arg1 ;
-(void)configureCell:(id)arg1 atIndex:(long long)arg2 ;
-(id)assetAtIndex:(long long)arg1 ;
-(void)leftSwipeGesture:(id)arg1 ;
-(void)rightSwipeGesture:(id)arg1 ;
-(void)setBookshelfImageConfiguration:(IMBookshelfImageConfiguration *)arg1 ;
-(BOOL)isBookFullyVisible:(id)arg1 ;
-(void)scrollToMakeObjectVisible:(id)arg1 ;
-(void)useAlternateLandscapeSize:(BOOL)arg1 ;
-(void)dataSourceWillChangeContent:(id)arg1 ;
-(void)dataSource:(id)arg1 didChangeSectionAtIndex:(unsigned long long)arg2 forChangeType:(int)arg3 ;
-(void)dataSource:(id)arg1 didChangeObject:(id)arg2 atIndexPath:(id)arg3 forChangeType:(int)arg4 newIndexPath:(id)arg5 ;
-(void)dataSourceDidChangeContent:(id)arg1 ;
-(void)setAlternateLandscapeSize:(CGSize)arg1 ;
-(void)_updateBackground;
-(void)dealloc;
-(id)init;
-(void)scrollViewDidScroll:(id)arg1 ;
-(void)scrollViewWillBeginDragging:(id)arg1 ;
-(void)viewDidLayoutSubviews;
-(void)setEditing:(BOOL)arg1 animated:(BOOL)arg2 ;
-(id)initWithNibName:(id)arg1 bundle:(id)arg2 ;
-(void)loadView;
-(BOOL)textFieldShouldReturn:(id)arg1 ;
-(BOOL)shouldAutorotateToInterfaceOrientation:(long long)arg1 ;
-(void)viewWillAppear:(BOOL)arg1 ;
-(void)viewDidAppear:(BOOL)arg1 ;
-(void)viewWillDisappear:(BOOL)arg1 ;
-(void)viewDidDisappear:(BOOL)arg1 ;
-(void)willRotateToInterfaceOrientation:(long long)arg1 duration:(double)arg2 ;
-(void)willAnimateRotationToInterfaceOrientation:(long long)arg1 duration:(double)arg2 ;
-(void)didRotateFromInterfaceOrientation:(long long)arg1 ;
-(id)searchField;
-(id)gridView;
-(CGSize)landscapeSize;
-(void)setLandscapeSize:(CGSize)arg1 ;
-(CGSize)portraitSize;
-(void)setPortraitSize:(CGSize)arg1 ;
@end

