/*
* This header is generated by classdump-dyld 1.0
* on Tuesday, June 5, 2018 at 10:39:48 PM China Standard Time
* Operating System: Version 8.2 (Build 12D508)
* Image Source: /private/var/db/stash/_.8k0vmU/Applications/Podcasts.app/Podcasts
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos.
*/

#import <Podcasts/IMPopupControllerAccessibility_super.h>

@interface IMPopupControllerAccessibility : IMPopupControllerAccessibility_super
+(void)_initializeSafeCategory;
-(void)dismissPopupViewControllerAnimated:(BOOL)arg1 ;
-(void)_axHandleDismissPopupNotification:(id)arg1 ;
-(void)presentPopupViewController:(id)arg1 parent:(id)arg2 dimmedView:(id)arg3 animated:(BOOL)arg4 ;
-(void)dealloc;
-(id)init;
@end

