/*
* This header is generated by classdump-dyld 1.0
* on Tuesday, June 5, 2018 at 10:39:48 PM China Standard Time
* Operating System: Version 8.2 (Build 12D508)
* Image Source: /private/var/db/stash/_.8k0vmU/Applications/Podcasts.app/Podcasts
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos.
*/

#import <Podcasts/Podcasts-Structs.h>
#import <UIKit/UITextField.h>

@class UIColor;

@interface IMSearchField : UITextField {

	BOOL _xTapped;
	UIColor* _placeholderTextColor;

}

@property (assign,nonatomic) BOOL xTapped;                                //@synthesize xTapped=_xTapped - In the implementation block
@property (nonatomic,retain) UIColor * placeholderTextColor;              //@synthesize placeholderTextColor=_placeholderTextColor - In the implementation block
-(void)setPlaceholderTextColor:(UIColor *)arg1 ;
-(void)setXTapped:(BOOL)arg1 ;
-(BOOL)xTapped;
-(UIColor *)placeholderTextColor;
-(id)initWithFrame:(CGRect)arg1 ;
-(void)dealloc;
-(BOOL)canBecomeFirstResponder;
-(CGRect)editingRectForBounds:(CGRect)arg1 ;
-(CGPoint)_offsetForMiniBarState:(BOOL)arg1 ;
-(CGRect)textRectForBounds:(CGRect)arg1 ;
-(CGRect)leftViewRectForBounds:(CGRect)arg1 ;
-(CGRect)borderRectForBounds:(CGRect)arg1 ;
-(void)drawPlaceholderInRect:(CGRect)arg1 ;
@end

