/*
* This header is generated by classdump-dyld 1.0
* on Tuesday, June 5, 2018 at 10:39:49 PM China Standard Time
* Operating System: Version 8.2 (Build 12D508)
* Image Source: /private/var/db/stash/_.8k0vmU/Applications/Podcasts.app/Podcasts
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos.
*/

#import <UIKit/UIViewController.h>
#import <UIKit/UITableViewDataSource.h>
#import <UIKit/UITableViewDelegate.h>

@protocol IMSubtitlesViewControllerDelegate;
@class MPAlternateTrack, MPAlternateTracks, UITableView, NSString;

@interface IMSubtitlesViewController : UIViewController <UITableViewDataSource, UITableViewDelegate> {

	BOOL _hasSubtitles;
	MPAlternateTrack* _originalSubtitleTrack;
	MPAlternateTrack* _newSubtitleTrack;
	MPAlternateTracks* _subtitles;
	id<IMSubtitlesViewControllerDelegate> _delegate;
	UITableView* _tableView;

}

@property (nonatomic,retain) MPAlternateTracks * subtitles;                                      //@synthesize subtitles=_subtitles - In the implementation block
@property (assign,nonatomic,__weak) id<IMSubtitlesViewControllerDelegate> delegate;              //@synthesize delegate=_delegate - In the implementation block
@property (nonatomic,retain) UITableView * tableView;                                            //@synthesize tableView=_tableView - In the implementation block
@property (readonly) unsigned long long hash; 
@property (readonly) Class superclass; 
@property (copy,readonly) NSString * description; 
@property (copy,readonly) NSString * debugDescription; 
-(void)setSubtitles:(MPAlternateTracks *)arg1 ;
-(id)initWithSubtitles:(id)arg1 ;
-(MPAlternateTracks *)subtitles;
-(void)_doneButtonTapped:(id)arg1 ;
-(id)_trackAtIndexPath:(id)arg1 ;
-(void)_cancelButtonTapped:(id)arg1 ;
-(void)setDelegate:(id<IMSubtitlesViewControllerDelegate>)arg1 ;
-(void)tableView:(id)arg1 didSelectRowAtIndexPath:(id)arg2 ;
-(long long)tableView:(id)arg1 numberOfRowsInSection:(long long)arg2 ;
-(id)tableView:(id)arg1 cellForRowAtIndexPath:(id)arg2 ;
-(id<IMSubtitlesViewControllerDelegate>)delegate;
-(void)setTableView:(UITableView *)arg1 ;
-(void)viewWillAppear:(BOOL)arg1 ;
-(void)viewDidLoad;
-(UITableView *)tableView;
@end

