/*
* This header is generated by classdump-dyld 1.0
* on Tuesday, June 5, 2018 at 10:39:48 PM China Standard Time
* Operating System: Version 8.2 (Build 12D508)
* Image Source: /private/var/db/stash/_.8k0vmU/Applications/Podcasts.app/Podcasts
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos.
*/

#import <UIKit/UIViewController.h>
#import <UIKit/UIPopoverControllerDelegate.h>
#import <Podcasts/MTReachabilityObserver.h>

@class UIView, MTLibrary, TKImageFactory, TKTheme, NSString, NSOperationQueue;

@interface MTBaseTopChartsViewController : UIViewController <UIPopoverControllerDelegate, MTReachabilityObserver> {

	BOOL _reachable;
	BOOL _viewDataLoaded;
	UIView* _baseView;
	MTLibrary* _library;
	TKImageFactory* _imageFactory;
	TKTheme* _globalTheme;
	NSString* _feedURL;
	NSOperationQueue* _chartQueue;

}

@property (retain) UIView * baseView;                                    //@synthesize baseView=_baseView - In the implementation block
@property (assign) BOOL reachable;                                       //@synthesize reachable=_reachable - In the implementation block
@property (assign) BOOL viewDataLoaded;                                  //@synthesize viewDataLoaded=_viewDataLoaded - In the implementation block
@property (assign,nonatomic,__weak) MTLibrary * library;                 //@synthesize library=_library - In the implementation block
@property (nonatomic,retain) TKImageFactory * imageFactory;              //@synthesize imageFactory=_imageFactory - In the implementation block
@property (nonatomic,retain) TKTheme * globalTheme;                      //@synthesize globalTheme=_globalTheme - In the implementation block
@property (nonatomic,retain) NSString * feedURL;                         //@synthesize feedURL=_feedURL - In the implementation block
@property (nonatomic,retain) NSOperationQueue * chartQueue;              //@synthesize chartQueue=_chartQueue - In the implementation block
@property (readonly) unsigned long long hash; 
@property (readonly) Class superclass; 
@property (copy,readonly) NSString * description; 
@property (copy,readonly) NSString * debugDescription; 
+(id)playableStoreMediaDictionaryItemFromTopChartEpisodeDetailsDictionaryItem:(id)arg1 ;
+(id)stringFromDictionary:(id)arg1 forKey:(id)arg2 ;
+(BOOL)isAValue:(id)arg1 ;
+(id)encodedQueryStringFromDictionary:(id)arg1 ;
+(id)formatDate:(id)arg1 ;
-(void)reachabilityChangedFrom:(BOOL)arg1 to:(BOOL)arg2 ;
-(void)setFeedURL:(NSString *)arg1 ;
-(void)explicitContentChanged:(id)arg1 ;
-(BOOL)reachable;
-(TKTheme *)globalTheme;
-(BOOL)isSubscribedToPodcast:(id)arg1 ;
-(void)updateGuidelinesWithPalette:(BOOL)arg1 ;
-(id)podcastUUIDForFeed:(id)arg1 ;
-(id)downloadingEpisodesForPodcast:(id)arg1 ;
-(id)knownChildrenForPodcast:(id)arg1 ;
-(BOOL)allowExplicit;
-(void)playMediaItem:(id)arg1 withEpisodes:(id)arg2 withComponent:(id)arg3 atIndex:(long long)arg4 ;
-(void)downloadEpisode:(id)arg1 withPodcast:(id)arg2 withCompletionBlock:(/*^block*/id)arg3 ;
-(void)pauseDownloadEpisode:(id)arg1 withCompletionBlock:(/*^block*/id)arg2 ;
-(void)subscribe:(id)arg1 withComponent:(id)arg2 ;
-(void)unsubscribe:(id)arg1 ;
-(void)setGlobalTheme:(TKTheme *)arg1 ;
-(id)episodeGuidForUUID:(id)arg1 ;
-(id)showPaletteWithHeight:(double)arg1 ;
-(void)showCannotConnectAlertWithTitle:(id)arg1 withMessage:(id)arg2 ;
-(NSOperationQueue *)chartQueue;
-(BOOL)viewDataLoaded;
-(void)loadViewData;
-(void)setViewDataLoaded:(BOOL)arg1 ;
-(TKImageFactory *)imageFactory;
-(void)setImageFactory:(TKImageFactory *)arg1 ;
-(id)createPodcastPlaylistItemWithDetails:(id)arg1 ;
-(BOOL)isMedia:(id)arg1 ;
-(void)openNonMedia:(id)arg1 ;
-(id)episodeForURL:(id)arg1 ;
-(BOOL)episodeDownloaded:(id)arg1 ;
-(BOOL)hasEpisodeForURL:(id)arg1 ;
-(void)setChartQueue:(NSOperationQueue *)arg1 ;
-(UIView *)baseView;
-(void)dealloc;
-(id)initWithNibName:(id)arg1 bundle:(id)arg2 ;
-(void)viewWillAppear:(BOOL)arg1 ;
-(void)popoverControllerDidDismissPopover:(id)arg1 ;
-(id)noContentView;
-(void)setReachable:(BOOL)arg1 ;
-(void)setBaseView:(UIView *)arg1 ;
-(MTLibrary *)library;
-(void)setLibrary:(MTLibrary *)arg1 ;
-(NSString *)feedURL;
@end

