/*
* This header is generated by classdump-dyld 1.0
* on Tuesday, June 5, 2018 at 10:39:47 PM China Standard Time
* Operating System: Version 8.2 (Build 12D508)
* Image Source: /private/var/db/stash/_.8k0vmU/Applications/Podcasts.app/Podcasts
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos.
*/


#import <Podcasts/Podcasts-Structs.h>
@class NSOperationQueue, MTURLSessionManager, NSMutableDictionary, NSMutableSet;

@interface MTFeedUpdater : NSObject {

	NSOperationQueue* _postUpdateQueue;
	MTURLSessionManager* _sessionManager;
	NSMutableDictionary* _md5Cache;
	NSOperationQueue* _queue;
	NSMutableSet* _updatingPodcastUuids;

}

@property (nonatomic,retain) NSOperationQueue * queue;                         //@synthesize queue=_queue - In the implementation block
@property (nonatomic,retain) NSOperationQueue * postUpdateQueue;               //@synthesize postUpdateQueue=_postUpdateQueue - In the implementation block
@property (nonatomic,retain) NSMutableSet * updatingPodcastUuids;              //@synthesize updatingPodcastUuids=_updatingPodcastUuids - In the implementation block
+(void)standardDeviationForEpisodes:(id)arg1 standardDeviation:(double*)arg2 average:(double*)arg3 ;
+(id)sharedInstance;
+(id)allocWithZone:(NSZone*)arg1 ;
-(void)updateAllPodcastsForced:(BOOL)arg1 completion:(/*^block*/id)arg2 ;
-(void)cancelAllUpdates;
-(void)subscribeToPodcastWithParams:(id)arg1 ;
-(void)saveSubscriptionMetadata;
-(void)removeMetadataForPodcastUuid:(id)arg1 ;
-(void)updatePodcastWithUuid:(id)arg1 interactive:(BOOL)arg2 completion:(/*^block*/id)arg3 ;
-(NSOperationQueue *)postUpdateQueue;
-(void)_preUpdate;
-(void)updatePodcastWithUuid:(id)arg1 interactive:(BOOL)arg2 forced:(BOOL)arg3 completion:(/*^block*/id)arg4 ;
-(void)_postUpdate;
-(void)_postUpdateWithForce:(BOOL)arg1 syncSubscriptions:(BOOL)arg2 ;
-(void)didStartUpdatingPodcastUuid:(id)arg1 ;
-(void)didFinishUpdatingPodcsatUuid:(id)arg1 ;
-(/*^block*/id)createUpdateCallbackBlockWithContext:(id)arg1 podcastUuid:(id)arg2 ;
-(void)addUpdateOperation:(id)arg1 ;
-(/*^block*/id)createAddSubscriptionCallbackForParams:(id)arg1 ;
-(void)headRequestForUrl:(id)arg1 completion:(/*^block*/id)arg2 queue:(id)arg3 forced:(BOOL)arg4 ;
-(void)updatePodcastsWithUuids:(id)arg1 interactive:(BOOL)arg2 completion:(/*^block*/id)arg3 ;
-(BOOL)isUpdatingPodcastWithUuid:(id)arg1 ;
-(void)setPostUpdateQueue:(NSOperationQueue *)arg1 ;
-(NSMutableSet *)updatingPodcastUuids;
-(void)setUpdatingPodcastUuids:(NSMutableSet *)arg1 ;
-(id)init;
-(id)copy;
-(void)setQueue:(NSOperationQueue *)arg1 ;
-(NSOperationQueue *)queue;
-(BOOL)networkReachable;
-(id)_metadataPath;
@end

