/*
* This header is generated by classdump-dyld 1.0
* on Tuesday, June 5, 2018 at 10:39:48 PM China Standard Time
* Operating System: Version 8.2 (Build 12D508)
* Image Source: /private/var/db/stash/_.8k0vmU/Applications/Podcasts.app/Podcasts
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos.
*/

#import <Foundation/NSProxy.h>
#import <UIKit/UIApplicationDelegate.h>

@class UIWindow, MTAppDelegate, NSMutableArray, NSString;

@interface MTMigrationAppDelegate : NSProxy <UIApplicationDelegate> {

	BOOL _isMigrating;
	UIWindow* _window;
	MTAppDelegate* _appDelegate;
	NSMutableArray* _queuedInvocations;
	unsigned long long _processAssertion;

}

@property (nonatomic,retain) UIWindow * window;                                //@synthesize window=_window - In the implementation block
@property (assign,nonatomic) BOOL isMigrating;                                 //@synthesize isMigrating=_isMigrating - In the implementation block
@property (nonatomic,retain) MTAppDelegate * appDelegate;                      //@synthesize appDelegate=_appDelegate - In the implementation block
@property (nonatomic,retain) NSMutableArray * queuedInvocations;               //@synthesize queuedInvocations=_queuedInvocations - In the implementation block
@property (assign,nonatomic) unsigned long long processAssertion;              //@synthesize processAssertion=_processAssertion - In the implementation block
@property (readonly) unsigned long long hash; 
@property (readonly) Class superclass; 
@property (copy,readonly) NSString * description; 
@property (copy,readonly) NSString * debugDescription; 
-(void)setIsMigrating:(BOOL)arg1 ;
-(void)finishMigration;
-(void)showIncompatibleDBDialog;
-(void)moveSourceFile:(id)arg1 toPath:(id)arg2 ;
-(void)flushInvocations;
-(BOOL)isMigrating;
-(UIWindow *)window;
-(BOOL)respondsToSelector:(SEL)arg1 ;
-(id)init;
-(BOOL)isKindOfClass:(Class)arg1 ;
-(BOOL)application:(id)arg1 shouldRestoreApplicationState:(id)arg2 ;
-(BOOL)application:(id)arg1 willFinishLaunchingWithOptions:(id)arg2 ;
-(void)setWindow:(UIWindow *)arg1 ;
-(id)methodSignatureForSelector:(SEL)arg1 ;
-(void)forwardInvocation:(id)arg1 ;
-(void)setQueuedInvocations:(NSMutableArray *)arg1 ;
-(NSMutableArray *)queuedInvocations;
-(MTAppDelegate *)appDelegate;
-(void)setAppDelegate:(MTAppDelegate *)arg1 ;
-(void)setProcessAssertion:(unsigned long long)arg1 ;
-(unsigned long long)processAssertion;
@end

