/*
* This header is generated by classdump-dyld 1.0
* on Tuesday, June 5, 2018 at 10:39:48 PM China Standard Time
* Operating System: Version 8.2 (Build 12D508)
* Image Source: /private/var/db/stash/_.8k0vmU/Applications/Podcasts.app/Podcasts
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos.
*/

#import <UIKit/UIViewController.h>
#import <UIKit/UITableViewDelegate.h>
#import <UIKit/UITableViewDataSource.h>

@protocol MTNowPlayingSleepViewControllerDelegate;
@class UITableView, NSString;

@interface MTNowPlayingSleepViewController : UIViewController <UITableViewDelegate, UITableViewDataSource> {

	BOOL _hasChapters;
	BOOL _hasEpisodes;
	id<MTNowPlayingSleepViewControllerDelegate> _delegate;
	long long _sleepEnum;
	UITableView* _tableView;

}

@property (assign,nonatomic) id<MTNowPlayingSleepViewControllerDelegate> delegate;              //@synthesize delegate=_delegate - In the implementation block
@property (assign,nonatomic) double sleepInterval; 
@property (assign,nonatomic) BOOL hasChapters;                                                  //@synthesize hasChapters=_hasChapters - In the implementation block
@property (assign,nonatomic) BOOL hasEpisodes;                                                  //@synthesize hasEpisodes=_hasEpisodes - In the implementation block
@property (assign,nonatomic) long long sleepEnum;                                               //@synthesize sleepEnum=_sleepEnum - In the implementation block
@property (nonatomic,retain) UITableView * tableView;                                           //@synthesize tableView=_tableView - In the implementation block
@property (readonly) unsigned long long hash; 
@property (readonly) Class superclass; 
@property (copy,readonly) NSString * description; 
@property (copy,readonly) NSString * debugDescription; 
-(void)setSleepInterval:(double)arg1 ;
-(void)setHasChapters:(BOOL)arg1 ;
-(void)setHasEpisodes:(BOOL)arg1 ;
-(void)setSleepEnum:(long long)arg1 ;
-(double)sleepInterval;
-(BOOL)hasChapters;
-(BOOL)hasEpisodes;
-(long long)sleepEnum;
-(void)setDelegate:(id<MTNowPlayingSleepViewControllerDelegate>)arg1 ;
-(void)tableView:(id)arg1 didSelectRowAtIndexPath:(id)arg2 ;
-(long long)tableView:(id)arg1 numberOfRowsInSection:(long long)arg2 ;
-(id)tableView:(id)arg1 cellForRowAtIndexPath:(id)arg2 ;
-(long long)numberOfSectionsInTableView:(id)arg1 ;
-(id<MTNowPlayingSleepViewControllerDelegate>)delegate;
-(unsigned long long)supportedInterfaceOrientations;
-(void)setTableView:(UITableView *)arg1 ;
-(void)viewDidLoad;
-(UITableView *)tableView;
@end

