/*
* This header is generated by classdump-dyld 1.0
* on Tuesday, June 5, 2018 at 10:39:48 PM China Standard Time
* Operating System: Version 8.2 (Build 12D508)
* Image Source: /private/var/db/stash/_.8k0vmU/Applications/Podcasts.app/Podcasts
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos.
*/

#import <Podcasts/MTListController.h>
#import <Podcasts/MTSourceListDelegate.h>
#import <UIKit/UIViewControllerRestoration.h>
#import <Podcasts/MTReachabilityObserver.h>
#import <Podcasts/MTPlaylistLayoutControllerProtocol.h>

@protocol MTPlaylistLayoutViewControllerDelegate;
@class UIViewController, UIPopoverController, NSString, UIView, UIButton, UIBarButtonItem, UIRefreshControl, MTPodcastPlaylistSheetViewController, MTAllPropertyChangesQueryObserver;

@interface MTPlaylistGroupDetailListController : MTListController <MTSourceListDelegate, UIViewControllerRestoration, MTReachabilityObserver, MTPlaylistLayoutControllerProtocol> {

	UIViewController* _detailController;
	UIPopoverController* _episodePopover;
	NSString* _settingsUuidDisplayingPopover;
	UIView* _headerViewSeparator;
	UIView* _footerView;
	UIButton* _settingsButton;
	UIBarButtonItem* _settingsButtonItem;
	UIPopoverController* _settingsPopover;
	UIRefreshControl* _refreshControl;
	unsigned long long _episodesCount;
	MTPodcastPlaylistSheetViewController* _addPodcastsViewController;
	MTAllPropertyChangesQueryObserver* _downloadedQuery;
	BOOL _restoring;
	BOOL _downloadButtonEnabled;
	BOOL _downloadsAvailable;
	/*^block*/id _settingsBlock;
	id<MTPlaylistLayoutViewControllerDelegate> _layoutDelegate;
	NSString* _playlistUuid;
	NSString* _playingUuid;

}

@property (nonatomic,retain) NSString * playlistUuid;                                                       //@synthesize playlistUuid=_playlistUuid - In the implementation block
@property (nonatomic,copy) NSString * playingUuid;                                                          //@synthesize playingUuid=_playingUuid - In the implementation block
@property (assign,nonatomic) BOOL downloadButtonEnabled;                                                    //@synthesize downloadButtonEnabled=_downloadButtonEnabled - In the implementation block
@property (assign,nonatomic) BOOL downloadsAvailable;                                                       //@synthesize downloadsAvailable=_downloadsAvailable - In the implementation block
@property (readonly) unsigned long long hash; 
@property (readonly) Class superclass; 
@property (copy,readonly) NSString * description; 
@property (copy,readonly) NSString * debugDescription; 
@property (nonatomic,copy) id settingsBlock;                                                                //@synthesize settingsBlock=_settingsBlock - In the implementation block
@property (assign,nonatomic,__weak) id<MTPlaylistLayoutViewControllerDelegate> layoutDelegate;              //@synthesize layoutDelegate=_layoutDelegate - In the implementation block
+(id)stationPodcastPredicateForPlaylist:(id)arg1 ;
+(Class)playlistSettingsClass;
+(id)viewControllerWithRestorationIdentifierPath:(id)arg1 coder:(id)arg2 ;
-(void)reachabilityChangedFrom:(BOOL)arg1 to:(BOOL)arg2 ;
-(void)sourceList:(id)arg1 didSelectItemUuid:(id)arg2 atIndexPath:(id)arg3 ;
-(void)sourceList:(id)arg1 didUpdateSelectedItemUuid:(id)arg2 ;
-(id)newCellInstanceWithReuseIdentifier:(id)arg1 ;
-(void)configureCell:(id)arg1 withObject:(id)arg2 atIndexPath:(id)arg3 ;
-(void)setPlaylistUuid:(NSString *)arg1 ;
-(void)setPlayingUuid:(NSString *)arg1 ;
-(void)transitionToState:(int)arg1 animated:(BOOL)arg2 ;
-(void)selectedItemAtIndexPath:(id)arg1 ;
-(id)editingToolbarButtons;
-(void)markSelectedItems:(BOOL)arg1 ;
-(void)markSelectedItemsAsSaved:(BOOL)arg1 ;
-(id)toolbarButtons;
-(void)edit:(id)arg1 ;
-(NSString *)playingUuid;
-(id)emptyListMessage;
-(void)showSettings:(id)arg1 ;
-(id)leftButtonItems;
-(NSString *)playlistUuid;
-(id)episodeListForSettings:(id)arg1 ;
-(id)settingsButtonItem;
-(void)refreshPlaylist:(id)arg1 ;
-(void)setDownloadButtonEnabled:(BOOL)arg1 ;
-(void)setDownloadsAvailable:(BOOL)arg1 ;
-(void)updateDownloadButtonState;
-(id<MTPlaylistLayoutViewControllerDelegate>)layoutDelegate;
-(void)_synchronousUpdatePlaylist;
-(void)_modifyEpisodesForSettingsWithBlock:(/*^block*/id)arg1 atIndexPaths:(id)arg2 ctx:(id)arg3 ;
-(void)updateEditingState:(BOOL)arg1 animated:(BOOL)arg2 ;
-(void)_updatePlaylist;
-(void)_updatePlaylistSuppressUpdates:(BOOL)arg1 ;
-(void)playlistSettingsDidChange;
-(id)settingsBlock;
-(void)setSettingsBlock:(id)arg1 ;
-(void)setLayoutDelegate:(id<MTPlaylistLayoutViewControllerDelegate>)arg1 ;
-(id)leftEditingItems;
-(id)rightEditingItems;
-(void)downloadAll:(id)arg1 ;
-(void)finishedSettings:(id)arg1 ;
-(void)finishedAdding:(id)arg1 ;
-(void)playlistSettingsDidChangeSetting:(id)arg1 ;
-(BOOL)downloadButtonEnabled;
-(BOOL)downloadsAvailable;
-(void)controller:(id)arg1 didChangeObject:(id)arg2 atIndexPath:(id)arg3 forChangeType:(unsigned long long)arg4 newIndexPath:(id)arg5 ;
-(void)controllerDidChangeContent:(id)arg1 ;
-(void)dealloc;
-(id)tableView:(id)arg1 willSelectRowAtIndexPath:(id)arg2 ;
-(long long)tableView:(id)arg1 editingStyleForRowAtIndexPath:(id)arg2 ;
-(BOOL)tableView:(id)arg1 shouldIndentWhileEditingRowAtIndexPath:(id)arg2 ;
-(long long)tableView:(id)arg1 numberOfRowsInSection:(long long)arg2 ;
-(long long)numberOfSectionsInTableView:(id)arg1 ;
-(BOOL)tableView:(id)arg1 canEditRowAtIndexPath:(id)arg2 ;
-(BOOL)tableView:(id)arg1 canMoveRowAtIndexPath:(id)arg2 ;
-(void)tableView:(id)arg1 commitEditingStyle:(long long)arg2 forRowAtIndexPath:(id)arg3 ;
-(void)tableView:(id)arg1 moveRowAtIndexPath:(id)arg2 toIndexPath:(id)arg3 ;
-(void)encodeRestorableStateWithCoder:(id)arg1 ;
-(void)decodeRestorableStateWithCoder:(id)arg1 ;
-(void)viewDidLayoutSubviews;
-(void)setEditing:(BOOL)arg1 animated:(BOOL)arg2 ;
-(id)initWithNibName:(id)arg1 bundle:(id)arg2 ;
-(void)viewWillAppear:(BOOL)arg1 ;
-(void)viewDidLoad;
-(void)viewDidAppear:(BOOL)arg1 ;
-(void)viewWillDisappear:(BOOL)arg1 ;
-(void)willRotateToInterfaceOrientation:(long long)arg1 duration:(double)arg2 ;
-(id)headerView;
-(void)observeValueForKeyPath:(id)arg1 ofObject:(id)arg2 change:(id)arg3 context:(void*)arg4 ;
-(void)delete:(id)arg1 ;
-(id)footerView;
-(void)contentSizeCategoryDidChange:(id)arg1 ;
-(id)settingsButton;
-(void)cancel:(id)arg1 ;
-(void)setLibrary:(id)arg1 ;
-(id)reuseIdentifierForRow:(id)arg1 ;
@end

