/*
* This header is generated by classdump-dyld 1.0
* on Tuesday, June 5, 2018 at 10:39:47 PM China Standard Time
* Operating System: Version 8.2 (Build 12D508)
* Image Source: /private/var/db/stash/_.8k0vmU/Applications/Podcasts.app/Podcasts
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos.
*/

#import <Podcasts/Podcasts-Structs.h>
#import <Podcasts/IMMediaChapter.h>

@class NSString, UIImage, NSURL, NSData;

@interface MTPlayerChapterInfo : NSObject <IMMediaChapter> {

	UIImage* _artwork;
	int _type;
	int _metadataType;
	NSString* _title;
	NSURL* assetURL;
	NSURL* _externalURL;
	double _duration;
	double _time;
	NSData* _artworkData;
	SCD_Struct_MT4 _assetTimeRange;
	SCD_Struct_MT4 _mediaTimeRange;

}

@property (nonatomic,retain) NSString * title;                           //@synthesize title=_title - In the implementation block
@property (nonatomic,retain) NSURL * assetURL; 
@property (nonatomic,retain) NSURL * externalURL;                        //@synthesize externalURL=_externalURL - In the implementation block
@property (nonatomic,readonly) UIImage * artwork; 
@property (nonatomic,retain) NSData * artworkData;                       //@synthesize artworkData=_artworkData - In the implementation block
@property (assign,nonatomic) double duration;                            //@synthesize duration=_duration - In the implementation block
@property (assign,nonatomic) double time;                                //@synthesize time=_time - In the implementation block
@property (assign,nonatomic) SCD_Struct_MT4 mediaTimeRange;              //@synthesize mediaTimeRange=_mediaTimeRange - In the implementation block
@property (assign,nonatomic) SCD_Struct_MT4 assetTimeRange;              //@synthesize assetTimeRange=_assetTimeRange - In the implementation block
@property (assign,nonatomic) int type;                                   //@synthesize type=_type - In the implementation block
@property (assign,nonatomic) int metadataType;                           //@synthesize metadataType=_metadataType - In the implementation block
@property (readonly) unsigned long long hash; 
@property (readonly) Class superclass; 
@property (copy,readonly) NSString * description; 
@property (copy,readonly) NSString * debugDescription; 
-(int)metadataType;
-(SCD_Struct_MT4)mediaTimeRange;
-(SCD_Struct_MT4)assetTimeRange;
-(void)setExternalURL:(NSURL *)arg1 ;
-(void)setMetadataType:(int)arg1 ;
-(void)setAssetTimeRange:(SCD_Struct_MT4)arg1 ;
-(void)setMediaTimeRange:(SCD_Struct_MT4)arg1 ;
-(NSURL *)externalURL;
-(UIImage *)artwork;
-(void)setTitle:(NSString *)arg1 ;
-(BOOL)isEqual:(id)arg1 ;
-(unsigned long long)hash;
-(NSString *)description;
-(double)duration;
-(void)setDuration:(double)arg1 ;
-(void)setType:(int)arg1 ;
-(int)type;
-(NSString *)title;
-(void)setTime:(double)arg1 ;
-(double)time;
-(NSData *)artworkData;
-(void)setArtworkData:(NSData *)arg1 ;
-(NSURL *)assetURL;
-(void)setAssetURL:(NSURL *)arg1 ;
@end

