/*
* This header is generated by classdump-dyld 1.0
* on Tuesday, June 5, 2018 at 10:39:48 PM China Standard Time
* Operating System: Version 8.2 (Build 12D508)
* Image Source: /private/var/db/stash/_.8k0vmU/Applications/Podcasts.app/Podcasts
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos.
*/

#import <Podcasts/MTSourceListController.h>

@class NSString, NSMutableSet;

@interface MTPodcastPlaylistSheetViewController : MTSourceListController {

	BOOL _allPodcastsSelected;
	NSString* _playlistName;
	NSMutableSet* _podcastUuids;
	NSString* _playlistUuid;

}

@property (nonatomic,retain) NSString * playlistName;                  //@synthesize playlistName=_playlistName - In the implementation block
@property (nonatomic,retain) NSMutableSet * podcastUuids;              //@synthesize podcastUuids=_podcastUuids - In the implementation block
@property (assign,nonatomic) BOOL allPodcastsSelected;                 //@synthesize allPodcastsSelected=_allPodcastsSelected - In the implementation block
@property (nonatomic,retain) NSString * playlistUuid;                  //@synthesize playlistUuid=_playlistUuid - In the implementation block
-(void)restoreSelection;
-(id)newCellInstanceWithReuseIdentifier:(id)arg1 ;
-(void)configureCell:(id)arg1 withObject:(id)arg2 atIndexPath:(id)arg3 ;
-(void)setPlaylistUuid:(NSString *)arg1 ;
-(NSMutableSet *)podcastUuids;
-(void)togglePodcastUuid:(id)arg1 ;
-(void)setPlaylistName:(NSString *)arg1 ;
-(NSString *)playlistName;
-(BOOL)allPodcastsSelected;
-(void)setPodcastUuids:(NSMutableSet *)arg1 ;
-(void)setAllPodcastsSelected:(BOOL)arg1 ;
-(NSString *)playlistUuid;
-(void)tableView:(id)arg1 didSelectRowAtIndexPath:(id)arg2 ;
-(void)viewDidLoad;
-(id)reuseIdentifierForRow:(id)arg1 ;
@end

