/*
* This header is generated by classdump-dyld 1.0
* on Tuesday, June 5, 2018 at 10:39:48 PM China Standard Time
* Operating System: Version 8.2 (Build 12D508)
* Image Source: /private/var/db/stash/_.8k0vmU/Applications/Podcasts.app/Podcasts
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos.
*/

#import <Podcasts/MTDetailViewController.h>
#import <Podcasts/MTPodcastSettingsViewControllerDelegate.h>
#import <Podcasts/MTGoneDarkViewDelegate.h>
#import <UIKit/UIViewControllerRestoration.h>

@class UIButton, UIToolbar, MTGoneDarkView, MTAllPropertyChangesQueryObserver, UIRefreshControl, NSDictionary, UIPopoverController, MTEpisode, MTPodcastDetailListController, NSString;

@interface MTPodcastDetailViewController : MTDetailViewController <MTPodcastSettingsViewControllerDelegate, MTGoneDarkViewDelegate, UIViewControllerRestoration> {

	UIButton* _shareButton;
	UIToolbar* _shareToolbar;
	MTGoneDarkView* _darkView;
	MTAllPropertyChangesQueryObserver* _darkQuery;
	UIRefreshControl* _refreshControl;
	BOOL _inStateRestoration;
	BOOL _showDetailPopoverAfterRotation;
	BOOL _supressDarkQueryChanges;
	double _detailHeaderHeight;
	BOOL _showShareItem;
	BOOL _switchToFeedTabOnLoad;
	NSDictionary* _podcastInfo;
	UIPopoverController* _detailsPopover;
	MTEpisode* _episodeToHighlight;

}

@property (nonatomic,readonly) MTPodcastDetailListController * detailListViewController; 
@property (assign,nonatomic) BOOL showShareItem;                                                      //@synthesize showShareItem=_showShareItem - In the implementation block
@property (nonatomic,retain) NSDictionary * podcastInfo;                                              //@synthesize podcastInfo=_podcastInfo - In the implementation block
@property (nonatomic,retain) UIPopoverController * detailsPopover;                                    //@synthesize detailsPopover=_detailsPopover - In the implementation block
@property (nonatomic,retain) MTEpisode * episodeToHighlight;                                          //@synthesize episodeToHighlight=_episodeToHighlight - In the implementation block
@property (assign,nonatomic) BOOL switchToFeedTabOnLoad;                                              //@synthesize switchToFeedTabOnLoad=_switchToFeedTabOnLoad - In the implementation block
@property (readonly) unsigned long long hash; 
@property (readonly) Class superclass; 
@property (copy,readonly) NSString * description; 
@property (copy,readonly) NSString * debugDescription; 
+(id)viewControllerWithRestorationIdentifierPath:(id)arg1 coder:(id)arg2 ;
-(void)setEpisodeToHighlight:(MTEpisode *)arg1 ;
-(void)switchToFeedTab;
-(void)unhighlightAllEpisodes;
-(int)detailHeaderMode;
-(id)newListController;
-(BOOL)stealsHeaderBar;
-(void)detailHeaderHeightDidChangetoHeight:(double)arg1 ;
-(void)detailListController:(id)arg1 didSelectRowAtIndexPath:(id)arg2 ;
-(void)detailListController:(id)arg1 didChangeEditing:(BOOL)arg2 animated:(BOOL)arg3 ;
-(UIPopoverController *)detailsPopover;
-(void)setDetailsPopover:(UIPopoverController *)arg1 ;
-(void)setPodcastInfo:(NSDictionary *)arg1 ;
-(NSDictionary *)podcastInfo;
-(MTEpisode *)episodeToHighlight;
-(void)showDark:(BOOL)arg1 animated:(BOOL)arg2 completion:(/*^block*/id)arg3 ;
-(void)showDarkViewIfNeededForPodcast:(id)arg1 animated:(BOOL)arg2 ;
-(void)showShare:(id)arg1 ;
-(void)refreshFeedIfNeeded;
-(id)shareToolbar;
-(BOOL)switchToFeedTabOnLoad;
-(void)setSwitchToFeedTabOnLoad:(BOOL)arg1 ;
-(BOOL)shouldShowPlacardForRemovePlayedEpisodes:(id)arg1 ;
-(BOOL)shouldShowPlacardForSavedEpisodes:(id)arg1 ;
-(void)showDark:(BOOL)arg1 animated:(BOOL)arg2 ;
-(void)updateRefreshControlMessage;
-(void)updatePodcast:(BOOL)arg1 ;
-(void)updatePodcast:(BOOL)arg1 withRefreshControl:(id)arg2 ;
-(void)showSettings:(id)arg1 ;
-(void)refreshControlDidFinish:(id)arg1 ;
-(void)settingsDidChange;
-(void)didTapPlacardForOrphanedFromCloudPodcast;
-(void)didTapPlacardForRemovePlayedEpisodes;
-(void)didTapPlacardForSavedEpisodes;
-(void)setShowShareItem:(BOOL)arg1 ;
-(BOOL)showShareItem;
-(void)podcastSettings:(id)arg1 changedSortAscending:(BOOL)arg2 ;
-(void)podcastSettings:(id)arg1 changedPlaybackOrderAscending:(BOOL)arg2 ;
-(void)podcastSettings:(id)arg1 changedSubscribed:(BOOL)arg2 ;
-(void)podcastSettings:(id)arg1 changedEpisodeLimit:(long long)arg2 ;
-(void)podcastSettings:(id)arg1 changedDeletedPlayedEpisodes:(long long)arg2 ;
-(void)goneDarkViewTapped;
-(id)messageForGoneDarkView:(id)arg1 ;
-(void)finishSettings:(id)arg1 ;
-(void)dismissViewController;
-(void)dealloc;
-(id)init;
-(void)encodeRestorableStateWithCoder:(id)arg1 ;
-(void)decodeRestorableStateWithCoder:(id)arg1 ;
-(void)viewDidLayoutSubviews;
-(void)viewWillAppear:(BOOL)arg1 ;
-(void)viewDidLoad;
-(void)viewDidAppear:(BOOL)arg1 ;
-(void)viewWillDisappear:(BOOL)arg1 ;
-(void)willRotateToInterfaceOrientation:(long long)arg1 duration:(double)arg2 ;
-(void)didRotateFromInterfaceOrientation:(long long)arg1 ;
-(id)shareButton;
@end

