/*
* This header is generated by classdump-dyld 1.0
* on Tuesday, June 5, 2018 at 10:39:48 PM China Standard Time
* Operating System: Version 8.2 (Build 12D508)
* Image Source: /private/var/db/stash/_.8k0vmU/Applications/Podcasts.app/Podcasts
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos.
*/


#import <Podcasts/Podcasts-Structs.h>
@interface MTRadioGroupDescription : NSObject {

	CFArrayRef _radioSettings;
	unsigned long long _value;
	/*^block*/id _changeHandler;

}

@property (nonatomic,retain) CFArrayRef radioSettings;              //@synthesize radioSettings=_radioSettings - In the implementation block
@property (assign,nonatomic) unsigned long long value;              //@synthesize value=_value - In the implementation block
@property (nonatomic,copy) id changeHandler;                        //@synthesize changeHandler=_changeHandler - In the implementation block
+(id)radioGroupWithInitialValue:(unsigned long long)arg1 changeHandler:(/*^block*/id)arg2 ;
-(void)setChangeHandler:(id)arg1 ;
-(void)addRadioSetting:(id)arg1 ;
-(CFArrayRef)radioSettings;
-(void)setRadioSettings:(CFArrayRef)arg1 ;
-(id)changeHandler;
-(id)init;
-(id)settings;
-(void)setValue:(unsigned long long)arg1 ;
-(unsigned long long)value;
@end

