/*
* This header is generated by classdump-dyld 1.0
* on Tuesday, June 5, 2018 at 10:39:47 PM China Standard Time
* Operating System: Version 8.2 (Build 12D508)
* Image Source: /private/var/db/stash/_.8k0vmU/Applications/Podcasts.app/Podcasts
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos.
*/

#import <Podcasts/Podcasts-Structs.h>
#import <Podcasts/MTTableViewCell.h>

@class UIImageView, UILabel, MTPodcastCellAccessoryView;

@interface MTSourceListCell : MTTableViewCell {

	BOOL _showsImage;
	BOOL _needsAttention;
	BOOL _hidesUnplayedCount;
	BOOL _overridesUnplayedCount;
	UIImageView* _sourceImageView;
	UILabel* _sourceTitleLabel;
	UILabel* _sourceDetailLabel;
	MTPodcastCellAccessoryView* _accessoryContainer;
	unsigned long long _unplayedCount;
	UIImageView* _videoIndicatorView;
	UILabel* _unplayedLabel;

}

@property (nonatomic,retain) UIImageView * sourceImageView;                                //@synthesize sourceImageView=_sourceImageView - In the implementation block
@property (nonatomic,retain) UILabel * sourceTitleLabel;                                   //@synthesize sourceTitleLabel=_sourceTitleLabel - In the implementation block
@property (nonatomic,retain) UILabel * sourceDetailLabel;                                  //@synthesize sourceDetailLabel=_sourceDetailLabel - In the implementation block
@property (nonatomic,retain) MTPodcastCellAccessoryView * accessoryContainer;              //@synthesize accessoryContainer=_accessoryContainer - In the implementation block
@property (assign,nonatomic) BOOL showsImage;                                              //@synthesize showsImage=_showsImage - In the implementation block
@property (assign,nonatomic) BOOL needsAttention;                                          //@synthesize needsAttention=_needsAttention - In the implementation block
@property (assign,nonatomic) BOOL hidesUnplayedCount;                                      //@synthesize hidesUnplayedCount=_hidesUnplayedCount - In the implementation block
@property (assign,nonatomic) BOOL overridesUnplayedCount;                                  //@synthesize overridesUnplayedCount=_overridesUnplayedCount - In the implementation block
@property (assign,nonatomic) unsigned long long unplayedCount;                             //@synthesize unplayedCount=_unplayedCount - In the implementation block
@property (nonatomic,retain) UIImageView * videoIndicatorView;                             //@synthesize videoIndicatorView=_videoIndicatorView - In the implementation block
@property (nonatomic,retain) UILabel * unplayedLabel;                                      //@synthesize unplayedLabel=_unplayedLabel - In the implementation block
+(id)countFont;
+(double)rowHeight;
+(id)titleFont;
+(id)detailFont;
+(double)verticalPadding;
-(void)setUnplayedCount:(unsigned long long)arg1 ;
-(void)setupCell;
-(void)setNeedsAttention:(BOOL)arg1 ;
-(BOOL)overridesUnplayedCount;
-(unsigned long long)unplayedCount;
-(UILabel *)sourceTitleLabel;
-(id)stringForDetailLabelWithPodcast:(id)arg1 ;
-(UILabel *)sourceDetailLabel;
-(UIImageView *)sourceImageView;
-(void)setHidesUnplayedCount:(BOOL)arg1 ;
-(void)updateWithPodcast:(id)arg1 ;
-(void)setSourceImageView:(UIImageView *)arg1 ;
-(void)setSourceTitleLabel:(UILabel *)arg1 ;
-(void)setSourceDetailLabel:(UILabel *)arg1 ;
-(MTPodcastCellAccessoryView *)accessoryContainer;
-(void)setAccessoryContainer:(MTPodcastCellAccessoryView *)arg1 ;
-(BOOL)needsAttention;
-(BOOL)hidesUnplayedCount;
-(void)setOverridesUnplayedCount:(BOOL)arg1 ;
-(UIImageView *)videoIndicatorView;
-(void)setVideoIndicatorView:(UIImageView *)arg1 ;
-(UILabel *)unplayedLabel;
-(void)setUnplayedLabel:(UILabel *)arg1 ;
-(void)_updateFonts;
-(void)layoutSubviews;
-(CGSize)sizeThatFits:(CGSize)arg1 ;
-(void)setHighlighted:(BOOL)arg1 animated:(BOOL)arg2 ;
-(void)setSelected:(BOOL)arg1 animated:(BOOL)arg2 ;
-(void)prepareForReuse;
-(void)setVideo:(BOOL)arg1 ;
-(void)updateWithInfo:(id)arg1 ;
-(BOOL)showsImage;
-(void)setShowsImage:(BOOL)arg1 ;
@end

