/*
* This header is generated by classdump-dyld 1.0
* on Tuesday, June 5, 2018 at 10:39:47 PM China Standard Time
* Operating System: Version 8.2 (Build 12D508)
* Image Source: /private/var/db/stash/_.8k0vmU/Applications/Podcasts.app/Podcasts
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos.
*/


@protocol MTSSDownloadManagerDelegate <NSObject>
@optional
-(void)downloadManager:(id)arg1 updateDownloadCount:(id)arg2;

@required
-(void)downloadManager:(id)arg1 willRemoveDownload:(id)arg2;
-(void)downloadManager:(id)arg1 didUpdateDownload:(id)arg2;
-(void)downloadManager:(id)arg1 didAddDownload:(id)arg2;
-(void)downloadManager:(id)arg1 didRemoveDownloads:(id)arg2;

@end

