/*
* This header is generated by classdump-dyld 1.0
* on Tuesday, June 5, 2018 at 10:39:47 PM China Standard Time
* Operating System: Version 8.2 (Build 12D508)
* Image Source: /private/var/db/stash/_.8k0vmU/Applications/Podcasts.app/Podcasts
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos.
*/

#import <Podcasts/Podcasts-Structs.h>
#import <iTunesStoreUI/SUClientController.h>

@protocol OS_dispatch_queue;
@class NSObject, SUTabBarController;

@interface MTStoreController : SUClientController {

	NSObject*<OS_dispatch_queue> _accessQueue;
	SUTabBarController* _tabBarController;

}

@property (nonatomic,retain) SUTabBarController * tabBarController;              //@synthesize tabBarController=_tabBarController - In the implementation block
+(id)defaultSearchConfigurationWithClientInterface:(id)arg1 ;
+(id)sharedInstance;
+(id)allocWithZone:(NSZone*)arg1 ;
+(void)initialize;
-(void)setTabBarController:(SUTabBarController *)arg1 ;
-(void)openStoreUrl:(id)arg1 inNavigationController:(id)arg2 ;
-(void)reportWithType:(int)arg1 userInfo:(id)arg2 location:(id)arg3 ;
-(id)_dictionaryForPodcastUuid:(id)arg1 ;
-(void)sendRequest:(id)arg1 referer:(id)arg2 ;
-(void)reportPlaybackFromStore:(id)arg1 ;
-(BOOL)UPPEnabled;
-(BOOL)isUserLoggedIn;
-(void)presentExternalURLViewController:(id)arg1 inTabBarController:(id)arg2 ;
-(id)init;
-(id)copy;
-(SUTabBarController *)tabBarController;
-(id)tabBarControllerForClientInterface:(id)arg1 ;
-(id)initWithClientInterface:(id)arg1 ;
-(id)tabBarController:(id)arg1 rootViewControllerForSection:(id)arg2 ;
-(id)tabBarController:(id)arg1 viewControllerForContext:(id)arg2 ;
-(id)newScriptInterface;
-(void)exitStoreWithReason:(long long)arg1 ;
@end

