/*
* This header is generated by classdump-dyld 1.0
* on Tuesday, June 5, 2018 at 10:39:48 PM China Standard Time
* Operating System: Version 8.2 (Build 12D508)
* Image Source: /private/var/db/stash/_.8k0vmU/Applications/Podcasts.app/Podcasts
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos.
*/

#import <Foundation/NSOperation.h>

@class NSTimer;

@interface MTTimedOperation : NSOperation {

	NSTimer* _optimer;
	/*^block*/id _mainBlock;
	BOOL _executing;
	BOOL _finished;
	int _operationType;
	double _timeout;

}

@property (nonatomic,readonly) BOOL isExecuting;              //@synthesize executing=_executing - In the implementation block
@property (nonatomic,readonly) BOOL isFinished;               //@synthesize finished=_finished - In the implementation block
@property (assign,nonatomic) double timeout;                  //@synthesize timeout=_timeout - In the implementation block
@property (assign,nonatomic) int operationType;               //@synthesize operationType=_operationType - In the implementation block
-(void)performMain:(id)arg1 ;
-(void)cancel;
-(id)init;
-(void)start;
-(void)main;
-(BOOL)isFinished;
-(BOOL)isExecuting;
-(void)finish;
-(BOOL)isConcurrent;
-(void)setMainBlock:(/*^block*/id)arg1 ;
-(void)scheduleTimer;
-(void)setTimeout:(double)arg1 ;
-(void)setOperationType:(int)arg1 ;
-(int)operationType;
-(double)timeout;
@end

