/*
* This header is generated by classdump-dyld 1.0
* on Tuesday, June 5, 2018 at 10:39:48 PM China Standard Time
* Operating System: Version 8.2 (Build 12D508)
* Image Source: /private/var/db/stash/_.8k0vmU/Applications/Podcasts.app/Podcasts
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos.
*/

#import <Podcasts/Podcasts-Structs.h>
#import <UIKit/UIView.h>

@class UIView;

@interface MTTouchForwardingView : UIView {

	UIView* _alwaysHitView;

}

@property (nonatomic,retain) UIView * alwaysHitView;              //@synthesize alwaysHitView=_alwaysHitView - In the implementation block
-(UIView *)alwaysHitView;
-(void)setAlwaysHitView:(UIView *)arg1 ;
-(id)hitTest:(CGPoint)arg1 withEvent:(id)arg2 ;
@end

