/*
* This header is generated by classdump-dyld 1.0
* on Tuesday, June 5, 2018 at 10:39:49 PM China Standard Time
* Operating System: Version 8.2 (Build 12D508)
* Image Source: /private/var/db/stash/_.8k0vmU/Applications/Podcasts.app/Podcasts
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos.
*/

#import <Podcasts/Podcasts-Structs.h>
#import <UIKit/UIView.h>

@class NSMutableDictionary, NSMutableArray, TKContainerView;

@interface TKCompositeView : UIView {

	NSMutableDictionary* _componentMappings;
	BOOL isSingleView;
	float _topPadding;
	NSMutableArray* _views;
	TKContainerView* _container;

}

@property (assign) float topPadding;                         //@synthesize topPadding=_topPadding - In the implementation block
@property (retain) NSMutableArray * views;                   //@synthesize views=_views - In the implementation block
@property (__weak) TKContainerView * container;              //@synthesize container=_container - In the implementation block
-(void)renderComponents:(id)arg1 withTheme:(id)arg2 ;
-(id)viewForModel:(id)arg1 ;
-(void)renderComponent:(id)arg1 withTheme:(id)arg2 ;
-(void)willRotateToInterfaceOrientation:(long long)arg1 withFrame:(CGRect)arg2 ;
-(double)getHeight;
-(double)getTop;
-(void)setTopPadding:(float)arg1 ;
-(float)topPadding;
-(id)initWithFrame:(CGRect)arg1 ;
-(void)dealloc;
-(id)hitTest:(CGPoint)arg1 withEvent:(id)arg2 ;
-(void)setContainer:(TKContainerView *)arg1 ;
-(TKContainerView *)container;
-(void)observeValueForKeyPath:(id)arg1 ofObject:(id)arg2 change:(id)arg3 context:(void*)arg4 ;
-(void)clear;
-(void)setViews:(NSMutableArray *)arg1 ;
-(NSMutableArray *)views;
@end

