/*
* This header is generated by classdump-dyld 1.0
* on Tuesday, June 5, 2018 at 10:39:49 PM China Standard Time
* Operating System: Version 8.2 (Build 12D508)
* Image Source: /private/var/db/stash/_.8k0vmU/Applications/Podcasts.app/Podcasts
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos.
*/


#import <Podcasts/Podcasts-Structs.h>
@class UIView;

@interface TKLabelInfo : NSObject {

	UIView* _view;
	UIEdgeInsets _insets;

}

@property (assign,nonatomic) UIEdgeInsets insets;              //@synthesize insets=_insets - In the implementation block
@property (nonatomic,retain) UIView * view;                    //@synthesize view=_view - In the implementation block
+(id)viewInfoWithView:(id)arg1 insets:(UIEdgeInsets)arg2 ;
-(UIView *)view;
-(void)setView:(UIView *)arg1 ;
-(UIEdgeInsets)insets;
-(void)setInsets:(UIEdgeInsets)arg1 ;
@end

