/*
* This header is generated by classdump-dyld 1.0
* on Tuesday, June 5, 2018 at 10:39:49 PM China Standard Time
* Operating System: Version 8.2 (Build 12D508)
* Image Source: /private/var/db/stash/_.8k0vmU/Applications/Podcasts.app/Podcasts
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos.
*/

#import <Podcasts/TKBaseComponent.h>

@class NSString;

@interface TKLoadingComponent : TKBaseComponent {

	BOOL _accountForTopGuideline;
	BOOL _accountForBottomGuideline;
	NSString* _text;

}

@property (retain) NSString * text;                             //@synthesize text=_text - In the implementation block
@property (assign) BOOL accountForTopGuideline;                 //@synthesize accountForTopGuideline=_accountForTopGuideline - In the implementation block
@property (assign) BOOL accountForBottomGuideline;              //@synthesize accountForBottomGuideline=_accountForBottomGuideline - In the implementation block
-(void)setAccountForBottomGuideline:(BOOL)arg1 ;
-(void)setAccountForTopGuideline:(BOOL)arg1 ;
-(BOOL)accountForTopGuideline;
-(BOOL)accountForBottomGuideline;
-(NSString *)text;
-(void)setText:(NSString *)arg1 ;
@end

