/*
* This header is generated by classdump-dyld 1.0
* on Tuesday, June 5, 2018 at 10:39:49 PM China Standard Time
* Operating System: Version 8.2 (Build 12D508)
* Image Source: /private/var/db/stash/_.8k0vmU/Applications/Podcasts.app/Podcasts
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos.
*/

#import <Podcasts/Podcasts-Structs.h>
#import <Podcasts/TKView.h>
#import <Podcasts/TKMultilineLabelScrollerDelegate.h>

@class NSString, UIButton, UILabel, TKMultilineLabelComponent, TKMultilineLabelScroller;

@interface TKMultilineLabel : TKView <TKMultilineLabelScrollerDelegate> {

	CGRect _lastLineFrame;
	CGRect _moreSize;
	NSString* _moreText;
	BOOL hasOverflow;
	UIButton* _moreButton;
	CGSize _fullSize;
	BOOL _hasMore;
	UILabel* _bodyLabel;
	UILabel* _moreLineLabel;
	TKMultilineLabelComponent* _model;
	double _lineHeight;
	double _topBottomPadding;
	TKMultilineLabelScroller* _moreLabel;
	CGSize _expectedSize;

}

@property (retain) UILabel * bodyLabel;                               //@synthesize bodyLabel=_bodyLabel - In the implementation block
@property (retain) UILabel * moreLineLabel;                           //@synthesize moreLineLabel=_moreLineLabel - In the implementation block
@property (retain) TKMultilineLabelComponent * model;                 //@synthesize model=_model - In the implementation block
@property (assign) BOOL hasMore;                                      //@synthesize hasMore=_hasMore - In the implementation block
@property (assign) double lineHeight;                                 //@synthesize lineHeight=_lineHeight - In the implementation block
@property (assign) double topBottomPadding;                           //@synthesize topBottomPadding=_topBottomPadding - In the implementation block
@property (assign) CGSize expectedSize;                               //@synthesize expectedSize=_expectedSize - In the implementation block
@property (retain) TKMultilineLabelScroller * moreLabel;              //@synthesize moreLabel=_moreLabel - In the implementation block
@property (readonly) unsigned long long hash; 
@property (readonly) Class superclass; 
@property (copy,readonly) NSString * description; 
@property (copy,readonly) NSString * debugDescription; 
+(CGRect)rectForBounds:(CGRect)arg1 withTop:(double)arg2 withTheme:(id)arg3 withComponent:(id)arg4 ;
+(CGSize)getHeightForTheme:(id)arg1 forNode:(id)arg2 withSize:(CGSize)arg3 ;
-(id)initWithFrame:(CGRect)arg1 withComponent:(id)arg2 withTheme:(id)arg3 ;
-(id)createMoreButton;
-(void)morePressed:(CGSize)arg1 ;
-(void)expandExpandingLabel:(id)arg1 ;
-(UILabel *)moreLineLabel;
-(void)setMoreLineLabel:(UILabel *)arg1 ;
-(BOOL)hasMore;
-(void)setHasMore:(BOOL)arg1 ;
-(double)topBottomPadding;
-(void)setTopBottomPadding:(double)arg1 ;
-(void)setExpectedSize:(CGSize)arg1 ;
-(TKMultilineLabelScroller *)moreLabel;
-(void)setMoreLabel:(TKMultilineLabelScroller *)arg1 ;
-(UILabel *)bodyLabel;
-(void)setBodyLabel:(UILabel *)arg1 ;
-(double)lineHeight;
-(void)tintColorDidChange;
-(void)setLineHeight:(double)arg1 ;
-(TKMultilineLabelComponent *)model;
-(void)setModel:(TKMultilineLabelComponent *)arg1 ;
-(CGSize)expectedSize;
@end

