/*
* This header is generated by classdump-dyld 1.0
* on Tuesday, June 5, 2018 at 10:39:49 PM China Standard Time
* Operating System: Version 8.2 (Build 12D508)
* Image Source: /private/var/db/stash/_.8k0vmU/Applications/Podcasts.app/Podcasts
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos.
*/

#import <Podcasts/TKBaseComponent.h>

@class NSString;

@interface TKSegmentedControlItemComponent : TKBaseComponent {

	BOOL _selected;
	NSString* _label;

}

@property (retain) NSString * label;              //@synthesize label=_label - In the implementation block
@property (assign) BOOL selected;                 //@synthesize selected=_selected - In the implementation block
-(void)setSelected:(BOOL)arg1 ;
-(NSString *)label;
-(void)setLabel:(NSString *)arg1 ;
-(BOOL)selected;
@end

