/*
* This header is generated by classdump-dyld 1.0
* on Wednesday, June 6, 2018 at 6:40:43 PM China Standard Time
* Operating System: Version 8.2 (Build 12D508)
* Image Source: /private/var/db/stash/_.8k0vmU/Applications/Game Center.app/Game Center
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos.
*/

#import <GameCenterPrivateUI/GKBasicCollectionViewDataSource.h>

@class GKPlayer, NSString;

@interface GKFriendsOfPlayerDataSource : GKBasicCollectionViewDataSource {

	BOOL _showSharedFriends;
	BOOL _hideHiddenFriendsCount;
	GKPlayer* _player;
	unsigned long long _hiddenFriendCount;
	NSString* _title;
	NSString* _alternateTitle;

}

@property (nonatomic,retain) GKPlayer * player;                                 //@synthesize player=_player - In the implementation block
@property (assign,nonatomic) BOOL showSharedFriends;                            //@synthesize showSharedFriends=_showSharedFriends - In the implementation block
@property (assign,nonatomic) BOOL hideHiddenFriendsCount;                       //@synthesize hideHiddenFriendsCount=_hideHiddenFriendsCount - In the implementation block
@property (assign,nonatomic) unsigned long long hiddenFriendCount;              //@synthesize hiddenFriendCount=_hiddenFriendCount - In the implementation block
@property (nonatomic,retain) NSString * title;                                  //@synthesize title=_title - In the implementation block
@property (nonatomic,retain) NSString * alternateTitle;                         //@synthesize alternateTitle=_alternateTitle - In the implementation block
-(BOOL)showSharedFriends;
-(void)setShowSharedFriends:(BOOL)arg1 ;
-(BOOL)hideHiddenFriendsCount;
-(void)setHideHiddenFriendsCount:(BOOL)arg1 ;
-(unsigned long long)hiddenFriendCount;
-(void)setHiddenFriendCount:(unsigned long long)arg1 ;
-(id)sectionTitle;
-(void)setTitle:(NSString *)arg1 ;
-(NSString *)title;
-(id)collectionView:(id)arg1 cellForItemAtIndexPath:(id)arg2 ;
-(void)refreshContentsForDataType:(unsigned)arg1 userInfo:(id)arg2 updateNotifier:(id)arg3 ;
-(void)configureCollectionView:(id)arg1 ;
-(id)footerText;
-(NSString *)alternateTitle;
-(void)setPlayer:(GKPlayer *)arg1 ;
-(GKPlayer *)player;
-(void)setAlternateTitle:(NSString *)arg1 ;
@end

