/*
* This header is generated by classdump-dyld 1.0
* on Wednesday, June 6, 2018 at 6:40:43 PM China Standard Time
* Operating System: Version 8.2 (Build 12D508)
* Image Source: /private/var/db/stash/_.8k0vmU/Applications/Game Center.app/Game Center
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos.
*/

#import <UIKit/UIView.h>

@class NSLayoutConstraint;

@interface GKSignInInputView : UIView {

	NSLayoutConstraint* _topToSignInBaselineConstraint;
	NSLayoutConstraint* _signInBaselineToPromptTextTopConstraint;
	NSLayoutConstraint* _promptTextBaselineToFakeTableGroupTopConstraint;
	NSLayoutConstraint* _iForgotBaselineToBottomConstraint;
	NSLayoutConstraint* _fakeTableGroupBottomToCogTopConstraint;
	NSLayoutConstraint* _iForgotBaselineToCreateNewBaselineConstraint;
	NSLayoutConstraint* _inputViewHeightConstraint;

}

@property (nonatomic,retain) NSLayoutConstraint * topToSignInBaselineConstraint;                                //@synthesize topToSignInBaselineConstraint=_topToSignInBaselineConstraint - In the implementation block
@property (nonatomic,retain) NSLayoutConstraint * signInBaselineToPromptTextTopConstraint;                      //@synthesize signInBaselineToPromptTextTopConstraint=_signInBaselineToPromptTextTopConstraint - In the implementation block
@property (nonatomic,retain) NSLayoutConstraint * promptTextBaselineToFakeTableGroupTopConstraint;              //@synthesize promptTextBaselineToFakeTableGroupTopConstraint=_promptTextBaselineToFakeTableGroupTopConstraint - In the implementation block
@property (nonatomic,retain) NSLayoutConstraint * iForgotBaselineToBottomConstraint;                            //@synthesize iForgotBaselineToBottomConstraint=_iForgotBaselineToBottomConstraint - In the implementation block
@property (nonatomic,retain) NSLayoutConstraint * fakeTableGroupBottomToCogTopConstraint;                       //@synthesize fakeTableGroupBottomToCogTopConstraint=_fakeTableGroupBottomToCogTopConstraint - In the implementation block
@property (nonatomic,retain) NSLayoutConstraint * iForgotBaselineToCreateNewBaselineConstraint;                 //@synthesize iForgotBaselineToCreateNewBaselineConstraint=_iForgotBaselineToCreateNewBaselineConstraint - In the implementation block
@property (nonatomic,retain) NSLayoutConstraint * inputViewHeightConstraint;                                    //@synthesize inputViewHeightConstraint=_inputViewHeightConstraint - In the implementation block
-(void)setupConstraintConstantsForOrientation:(long long)arg1 ;
-(id)allVariableConstraints;
-(NSLayoutConstraint *)topToSignInBaselineConstraint;
-(void)setTopToSignInBaselineConstraint:(NSLayoutConstraint *)arg1 ;
-(NSLayoutConstraint *)signInBaselineToPromptTextTopConstraint;
-(void)setSignInBaselineToPromptTextTopConstraint:(NSLayoutConstraint *)arg1 ;
-(NSLayoutConstraint *)promptTextBaselineToFakeTableGroupTopConstraint;
-(void)setPromptTextBaselineToFakeTableGroupTopConstraint:(NSLayoutConstraint *)arg1 ;
-(NSLayoutConstraint *)iForgotBaselineToBottomConstraint;
-(void)setIForgotBaselineToBottomConstraint:(NSLayoutConstraint *)arg1 ;
-(NSLayoutConstraint *)fakeTableGroupBottomToCogTopConstraint;
-(void)setFakeTableGroupBottomToCogTopConstraint:(NSLayoutConstraint *)arg1 ;
-(NSLayoutConstraint *)iForgotBaselineToCreateNewBaselineConstraint;
-(void)setIForgotBaselineToCreateNewBaselineConstraint:(NSLayoutConstraint *)arg1 ;
-(void)dealloc;
-(NSLayoutConstraint *)inputViewHeightConstraint;
-(void)setInputViewHeightConstraint:(NSLayoutConstraint *)arg1 ;
@end

