/*
* This header is generated by classdump-dyld 1.0
* on Wednesday, June 6, 2018 at 6:40:43 PM China Standard Time
* Operating System: Version 8.2 (Build 12D508)
* Image Source: /private/var/db/stash/_.8k0vmU/Applications/Game Center.app/Game Center
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos.
*/

#import <Game Center/GKGamesRecommendationsDataSource.h>

@interface GKTopGamesDataSource : GKGamesRecommendationsDataSource
-(void)loadGamesWithHandler:(/*^block*/id)arg1 ;
-(id)sectionTitle;
-(id)init;
-(id)collectionView:(id)arg1 cellForItemAtIndexPath:(id)arg2 ;
@end

