/*
* This header is generated by classdump-dyld 1.0
* on Wednesday, June 6, 2018 at 6:40:43 PM China Standard Time
* Operating System: Version 8.2 (Build 12D508)
* Image Source: /private/var/db/stash/_.8k0vmU/Applications/Game Center.app/Game Center
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos.
*/

#import <GameCenterPrivateUI/GKSplittingDataSource.h>

@class GKGame;

@interface GKTurnBasedMatchesDataSource : GKSplittingDataSource {

	GKGame* _game;
	SEL _detailPressedAction;

}

@property (nonatomic,retain) GKGame * game;                        //@synthesize game=_game - In the implementation block
@property (assign,nonatomic) SEL detailPressedAction;              //@synthesize detailPressedAction=_detailPressedAction - In the implementation block
-(id)collectionView:(id)arg1 cellForItemAtIndexPath:(id)arg2 ;
-(unsigned long long)numberOfMatches;
-(GKGame *)game;
-(void)setGame:(GKGame *)arg1 ;
-(void)configureDataSource;
-(void)collectionViewWillBecomeActive:(id)arg1 ;
-(void)configureCollectionView:(id)arg1 ;
-(void)removeItemAtIndexPath:(id)arg1 completionHandler:(/*^block*/id)arg2 ;
-(void)setDetailPressedAction:(SEL)arg1 ;
-(SEL)detailPressedAction;
@end

