/*
* This header is generated by classdump-dyld 1.0
* on Tuesday, June 5, 2018 at 10:57:04 PM China Standard Time
* Operating System: Version 8.2 (Build 12D508)
* Image Source: /private/var/db/stash/_.8k0vmU/Applications/Bridge.app/Bridge
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos.
*/

#import <Bridge/COSNotificationAppController.h>

@class PSSystemPolicyManager;

@interface COSSockPuppetAppController : COSNotificationAppController {

	PSSystemPolicyManager* _policyManager;

}

@property (nonatomic,retain) PSSystemPolicyManager * policyManager;              //@synthesize policyManager=_policyManager - In the implementation block
-(void)setPuppetAppShows:(id)arg1 specifier:(id)arg2 ;
-(id)puppetAppShows:(id)arg1 ;
-(id)sockPuppetSpecifiersForIdentifier:(id)arg1 ;
-(PSSystemPolicyManager *)policyManager;
-(void)setPolicyManager:(PSSystemPolicyManager *)arg1 ;
-(id)specifiers;
@end

