/*
* This header is generated by classdump-dyld 1.0
* on Tuesday, June 5, 2018 at 10:57:03 PM China Standard Time
* Operating System: Version 8.2 (Build 12D508)
* Image Source: /private/var/db/stash/_.8k0vmU/Applications/Bridge.app/Bridge
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos.
*/

#import <Bridge/COSSetupPageViewController.h>
#import <Bridge/COSBuddyController.h>

@class UILabel, COSPhoneView, COSWatchView, UIButton, NSString;

@interface COSUnlockConfirmationViewController : COSSetupPageViewController <COSBuddyController> {

	UILabel* _titleLabel;
	COSPhoneView* _phoneView;
	COSWatchView* _watchView;
	UILabel* _subtitleLabel;
	UILabel* _detailLabel;
	UILabel* _subDetailLabel;
	UIButton* _confirmButton;
	BOOL _mandatory;
	BOOL _completed;

}

@property (assign,getter=isMandatory,nonatomic) BOOL mandatory;                           //@synthesize mandatory=_mandatory - In the implementation block
@property (assign,nonatomic,__weak) id<COSBuddyControllerDelegate> delegate; 
@property (assign,nonatomic) BOOL completed;                                              //@synthesize completed=_completed - In the implementation block
@property (readonly) unsigned long long hash; 
@property (readonly) Class superclass; 
@property (copy,readonly) NSString * description; 
@property (copy,readonly) NSString * debugDescription; 
+(id)_fakeBackButtonItemForTarget:(id)arg1 withAction:(SEL)arg2 ;
-(void)unlockPairingComplete:(id)arg1 ;
-(void)confirmed;
-(void)removeFromNavHierarchyOf:(id)arg1 ;
-(void)setMandatory:(BOOL)arg1 ;
-(BOOL)isMandatory;
-(BOOL)completed;
-(void)setCompleted:(BOOL)arg1 ;
-(void)_updateLayout;
-(void)dealloc;
-(id)init;
-(void)loadView;
-(id)titleString;
-(void)back:(id)arg1 ;
@end

