/*
* This header is generated by classdump-dyld 1.0
* on Wednesday, June 6, 2018 at 1:34:19 PM China Standard Time
* Operating System: Version 8.2 (Build 12D508)
* Image Source: /private/var/db/stash/_.8k0vmU/Applications/VoiceMemos.app/VoiceMemos
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos.
*/

#import <VoiceMemos/VoiceMemos-Structs.h>
#import <VoiceMemos/RCRootViewController.h>
#import <VoiceMemos/RCRecordingsTableViewDelegate.h>
#import <VoiceMemos/RCRootViewControllerDelegate.h>
#import <UIKit/UISplitViewControllerDelegate.h>

@class RCSplitViewController, UINavigationController, RCDetailNavigationController, RCRecordingsTableViewController, RCVerticalRootViewController, NSString;

@interface RCHorizontalRootViewController : RCRootViewController <RCRecordingsTableViewDelegate, RCRootViewControllerDelegate, UISplitViewControllerDelegate> {

	BOOL _masterTableViewControllerVisible;
	BOOL _shouldHideStatusBar;
	BOOL _needsInitialPrimaryLayoutAxisSetup;
	RCSplitViewController* _splitViewController;
	UINavigationController* _masterNavigationController;
	RCDetailNavigationController* _detailNavigationController;
	RCRecordingsTableViewController* _recordingsTableViewController;
	RCVerticalRootViewController* _verticalRootViewController;

}

@property (nonatomic,readonly) RCSplitViewController * splitViewController;                                                //@synthesize splitViewController=_splitViewController - In the implementation block
@property (nonatomic,readonly) UINavigationController * masterNavigationController;                                        //@synthesize masterNavigationController=_masterNavigationController - In the implementation block
@property (nonatomic,readonly) RCDetailNavigationController * detailNavigationController;                                  //@synthesize detailNavigationController=_detailNavigationController - In the implementation block
@property (nonatomic,readonly) RCRecordingsTableViewController * recordingsTableViewController;                            //@synthesize recordingsTableViewController=_recordingsTableViewController - In the implementation block
@property (nonatomic,readonly) RCVerticalRootViewController * verticalRootViewController;                                  //@synthesize verticalRootViewController=_verticalRootViewController - In the implementation block
@property (assign,getter=isMasterTableViewControllerVisible,nonatomic) BOOL masterTableViewControllerVisible;              //@synthesize masterTableViewControllerVisible=_masterTableViewControllerVisible - In the implementation block
@property (assign,nonatomic) BOOL shouldHideStatusBar;                                                                     //@synthesize shouldHideStatusBar=_shouldHideStatusBar - In the implementation block
@property (assign,nonatomic) BOOL needsInitialPrimaryLayoutAxisSetup;                                                      //@synthesize needsInitialPrimaryLayoutAxisSetup=_needsInitialPrimaryLayoutAxisSetup - In the implementation block
@property (readonly) unsigned long long hash; 
@property (readonly) Class superclass; 
@property (copy,readonly) NSString * description; 
@property (copy,readonly) NSString * debugDescription; 
+(BOOL)_shouldForwardViewWillTransitionToSize;
-(void)playSelectedRecording;
-(void)selectRecordingWithCompositionController:(id)arg1 animated:(BOOL)arg2 completionBlock:(/*^block*/id)arg3 ;
-(BOOL)canDismissForIdleEvent;
-(id)presentedWaveformDataSource;
-(void)savedRecordingsModelDidChangeNotification:(id)arg1 ;
-(void)setShouldHideStatusBar:(BOOL)arg1 ;
-(void)_updateSelectionToMatchVerticalViewController;
-(void)_updateNavigationBarsAnimated:(BOOL)arg1 ;
-(void)_updateSettingsForVerticalRootViewController:(id)arg1 ;
-(BOOL)_canPresentSideBySideUserInterfaceInLandscapeOrientation;
-(void)_createNewVerticalRootViewControllerAnimated:(BOOL)arg1 presentedCompositionController:(id)arg2 ;
-(void)setMasterTableViewControllerVisible:(BOOL)arg1 ;
-(void)_setupInitialPrimaryLayoutAxis;
-(BOOL)shouldHideStatusBar;
-(BOOL)isMasterTableViewControllerVisible;
-(id)_detailNavigationItem;
-(void)_presentEditedRecordingWithCompositionController:(id)arg1 forceUpdatePresentation:(BOOL)arg2 animated:(BOOL)arg3 completionBlock:(/*^block*/id)arg4 ;
-(void)pauseSelectedRecording;
-(BOOL)isTableViewControllerVisible;
-(id)_masterNavigationItem;
-(void)shareSelectedRecordingAction:(id)arg1 ;
-(void)deleteSelectedRecordingAction:(id)arg1 ;
-(void)recordingsTableViewController:(id)arg1 didSelectRecording:(id)arg2 compositionController:(id)arg3 ;
-(void)recordingsTableViewController:(id)arg1 willDeleteRecording:(id)arg2 compositionController:(id)arg3 ;
-(void)recordingsTableViewController:(id)arg1 wantsToEditRecording:(id)arg2 compositionController:(id)arg3 ;
-(BOOL)rootViewControllerCanShowRecordingsTable:(id)arg1 ;
-(RCDetailNavigationController *)detailNavigationController;
-(RCRecordingsTableViewController *)recordingsTableViewController;
-(RCVerticalRootViewController *)verticalRootViewController;
-(BOOL)needsInitialPrimaryLayoutAxisSetup;
-(void)setNeedsInitialPrimaryLayoutAxisSetup:(BOOL)arg1 ;
-(id)navigationItem;
-(BOOL)prefersStatusBarHidden;
-(unsigned long long)supportedInterfaceOrientations;
-(void)setEditing:(BOOL)arg1 animated:(BOOL)arg2 ;
-(RCSplitViewController *)splitViewController;
-(void)viewWillTransitionToSize:(CGSize)arg1 withTransitionCoordinator:(id)arg2 ;
-(id)initWithNibName:(id)arg1 bundle:(id)arg2 ;
-(void)dismissViewControllerAnimated:(BOOL)arg1 completion:(/*^block*/id)arg2 ;
-(void)viewWillAppear:(BOOL)arg1 ;
-(void)viewDidLoad;
-(BOOL)splitViewController:(id)arg1 collapseSecondaryViewController:(id)arg2 ontoPrimaryViewController:(id)arg3 ;
-(id)splitViewController:(id)arg1 separateSecondaryViewControllerFromPrimaryViewController:(id)arg2 ;
-(id)primaryViewControllerForCollapsingSplitViewController:(id)arg1 ;
-(id)primaryViewControllerForExpandingSplitViewController:(id)arg1 ;
-(unsigned long long)splitViewControllerSupportedInterfaceOrientations:(id)arg1 ;
-(void)splitViewController:(id)arg1 willChangeToDisplayMode:(long long)arg2 ;
-(UINavigationController *)masterNavigationController;
-(id)rc_navigationItemForPresentingNavigationItem:(id)arg1 forViewController:(id)arg2 ;
@end

