/*
* This header is generated by classdump-dyld 1.0
* on Tuesday, June 5, 2018 at 6:34:35 PM China Standard Time
* Operating System: Version 8.2 (Build 12D508)
* Image Source: /private/var/db/stash/_.8k0vmU/Applications/Health.app/Health
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos.
*/

#import <Health/WDDataProvider.h>

@class HKStatisticsCollectionQuery, HKQuery;

@interface WDCumulativeDataProvider : WDDataProvider {

	HKStatisticsCollectionQuery* _statisticsQuery;
	HKQuery* _currentValueQuery;
	HKStatisticsCollectionQuery* _averageQuery;

}
-(void)restartQueries;
-(void)stopQueries;
-(void)_restartCurrentValueQuery;
-(void)_restartHistoricalDataQuery;
-(void)_stopCurrentValueQuery;
-(void)_stopHistoricalDataQuery;
-(id)_currentValueQuery;
-(id)_chartPointForStatistics:(id)arg1 dataUnit:(id)arg2 ;
-(void)_restartAverageQuery;
-(void)_stopAverageQuery;
-(void)_refreshHistoricalDataWithStatistics:(id)arg1 error:(id)arg2 dataUnit:(id)arg3 timeScope:(long long)arg4 startDate:(id)arg5 endDate:(id)arg6 ;
-(BOOL)_shouldExecuteAverageQuery:(long long)arg1 ;
-(void)_updateAverageWithStatistics:(id)arg1 dataUnit:(id)arg2 timeScope:(long long)arg3 error:(id)arg4 ;
-(void)_updateMostRecentStatisticsWithError:(id)arg1 ;
-(void)_updateMostRecentStatisticsFromDate:(id)arg1 toDate:(id)arg2 ;
@end

