/*
* This header is generated by classdump-dyld 1.0
* on Tuesday, June 5, 2018 at 6:34:35 PM China Standard Time
* Operating System: Version 8.2 (Build 12D508)
* Image Source: /private/var/db/stash/_.8k0vmU/Applications/Health.app/Health
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos.
*/

#import <UIKit/UITableViewCell.h>

@class UILabel, UIColor, UIView, NSString;

@interface WDMeDataTableViewCell : UITableViewCell {

	UILabel* _displayNameLabel;
	UILabel* _displayValueLabel;
	UIColor* _normalDisplayValueColor;
	UIColor* _selectedDisplayValueColor;
	UIView* _inputView;
	BOOL _shouldUseSelectedColorForDisplayValue;
	NSString* _displayName;
	NSString* _displayValue;

}

@property (nonatomic,retain) NSString * displayName;                                  //@synthesize displayName=_displayName - In the implementation block
@property (nonatomic,retain) NSString * displayValue;                                 //@synthesize displayValue=_displayValue - In the implementation block
@property (assign,nonatomic) BOOL shouldUseSelectedColorForDisplayValue;              //@synthesize shouldUseSelectedColorForDisplayValue=_shouldUseSelectedColorForDisplayValue - In the implementation block
-(void)setDisplayValue:(NSString *)arg1 ;
-(void)setShouldUseSelectedColorForDisplayValue:(BOOL)arg1 ;
-(BOOL)shouldUseSelectedColorForDisplayValue;
-(NSString *)displayValue;
-(void)setDisplayName:(NSString *)arg1 ;
-(void)layoutSubviews;
-(id)initWithStyle:(long long)arg1 reuseIdentifier:(id)arg2 ;
-(BOOL)becomeFirstResponder;
-(BOOL)canBecomeFirstResponder;
-(id)inputView;
-(void)setInputView:(id)arg1 ;
-(NSString *)displayName;
-(void)_setupUI;
@end

