/*
* This header is generated by classdump-dyld 1.0
* on Tuesday, June 5, 2018 at 6:34:35 PM China Standard Time
* Operating System: Version 8.2 (Build 12D508)
* Image Source: /private/var/db/stash/_.8k0vmU/Applications/Health.app/Health
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos.
*/

#import <Health/Health-Structs.h>
#import <UIKit/UIControl.h>

@class UISegmentedControl;

@interface WDTimeScopeControl : UIControl {

	UISegmentedControl* _segments;

}

@property (assign,nonatomic) long long selectedTimeScope; 
-(long long)selectedTimeScope;
-(void)setSelectedTimeScope:(long long)arg1 ;
-(void)_segmentValueChanged:(id)arg1 ;
-(id)initWithFrame:(CGRect)arg1 ;
-(void)layoutSubviews;
-(CGSize)sizeThatFits:(CGSize)arg1 ;
@end

