/*
* This header is generated by classdump-dyld 1.0
* on Tuesday, June 5, 2018 at 6:45:48 PM China Standard Time
* Operating System: Version 8.2 (Build 12D508)
* Image Source: /private/var/db/stash/_.8k0vmU/Applications/AppStore.app/AppStore
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos.
*/

#import <StoreKitUI/SKUITableViewCell.h>

@class SKUIMessageBanner;

@interface ASBannerTableViewCell : SKUITableViewCell {

	SKUIMessageBanner* _banner;

}

@property (nonatomic,retain) SKUIMessageBanner * banner;              //@synthesize banner=_banner - In the implementation block
-(void)setBanner:(SKUIMessageBanner *)arg1 ;
-(SKUIMessageBanner *)banner;
@end

