/*
* This header is generated by classdump-dyld 1.0
* on Tuesday, June 5, 2018 at 6:45:48 PM China Standard Time
* Operating System: Version 8.2 (Build 12D508)
* Image Source: /private/var/db/stash/_.8k0vmU/Applications/AppStore.app/AppStore
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos.
*/

#import <StoreKitUI/SKUIItem.h>

@class NSString;

@interface ASUpdateItem : SKUIItem {

	NSString* _lastUpdateDateString;
	BOOL _systemApp;
	NSString* _updateDescription;

}

@property (getter=isSystemApp,nonatomic,readonly) BOOL systemApp;              //@synthesize systemApp=_systemApp - In the implementation block
@property (nonatomic,readonly) NSString * lastUpdateDateString;                //@synthesize lastUpdateDateString=_lastUpdateDateString - In the implementation block
@property (nonatomic,readonly) NSString * updateDescription;                   //@synthesize updateDescription=_updateDescription - In the implementation block
-(id)description;
-(BOOL)isSystemApp;
-(id)initWithLookupDictionary:(id)arg1 ;
-(NSString *)updateDescription;
-(NSString *)lastUpdateDateString;
@end

