/*
* This header is generated by classdump-dyld 1.0
* on Tuesday, June 5, 2018 at 10:55:36 PM China Standard Time
* Operating System: Version 8.2 (Build 12D508)
* Image Source: /private/var/db/stash/_.8k0vmU/Applications/Videos.app/Videos
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos.
*/

#import <MediaPlayer/MPMediaQueryNowPlayingItem.h>

@interface VideosAVItem : MPMediaQueryNowPlayingItem
-(id)_mediaSelectionOptionFromGroup:(id)arg1 withTrackID:(int)arg2 ;
-(void)setupPlaybackInfo;
-(void)handlePlaybackFinishedTime:(double)arg1 finishedByHittingEnd:(BOOL)arg2 ;
@end

