/*
* This header is generated by classdump-dyld 1.0
* on Tuesday, June 5, 2018 at 10:55:36 PM China Standard Time
* Operating System: Version 8.2 (Build 12D508)
* Image Source: /private/var/db/stash/_.8k0vmU/Applications/Videos.app/Videos
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos.
*/

#import <Videos/Videos-Structs.h>
#import <MediaPlayerUI/MPUArtworkView.h>

@class UIImage, UIColor, UIView, NSString, UILabel, UIImageView;

@interface VideosArtworkView : MPUArtworkView {

	UIImage* _effectiveImage;
	UIImage* _externalImage;
	UIColor* _originalBackgroundColor;
	UIView* _placeholderTopLayoutGuide;
	UIView* _placeholderBottomLayoutGuide;
	double _placeholderAspectRatio;
	NSString* _placeholderTitle;
	unsigned long long _placeholderMediaType;
	UILabel* _placeholderTitleLabel;
	UIImageView* _placeholderIconView;

}

@property (assign,nonatomic) double placeholderAspectRatio;                        //@synthesize placeholderAspectRatio=_placeholderAspectRatio - In the implementation block
@property (nonatomic,copy) NSString * placeholderTitle;                            //@synthesize placeholderTitle=_placeholderTitle - In the implementation block
@property (assign,nonatomic) unsigned long long placeholderMediaType;              //@synthesize placeholderMediaType=_placeholderMediaType - In the implementation block
@property (nonatomic,retain) UILabel * placeholderTitleLabel;                      //@synthesize placeholderTitleLabel=_placeholderTitleLabel - In the implementation block
@property (nonatomic,retain) UIImageView * placeholderIconView;                    //@synthesize placeholderIconView=_placeholderIconView - In the implementation block
-(void)setPlaceholderAspectRatio:(double)arg1 ;
-(void)setPlaceholderMediaType:(unsigned long long)arg1 ;
-(double)placeholderAspectRatio;
-(unsigned long long)placeholderMediaType;
-(void)_updatePlaceholderIconView;
-(UILabel *)placeholderTitleLabel;
-(void)_removePlaceholder;
-(UIImageView *)placeholderIconView;
-(void)setPlaceholderTitleLabel:(UILabel *)arg1 ;
-(void)setPlaceholderIconView:(UIImageView *)arg1 ;
-(void)setImage:(id)arg1 ;
-(void)setBackgroundColor:(id)arg1 ;
-(CGSize)intrinsicContentSize;
-(void)updateConstraints;
-(void)_showPlaceholder;
-(void)_updateEffectiveImage;
-(void)setPlaceholderTitle:(NSString *)arg1 ;
-(NSString *)placeholderTitle;
-(void)_setPlaceholderHidden:(BOOL)arg1 ;
-(BOOL)shouldDisplayPlaceholder;
@end

