/*
* This header is generated by classdump-dyld 1.0
* on Tuesday, June 5, 2018 at 10:55:36 PM China Standard Time
* Operating System: Version 8.2 (Build 12D508)
* Image Source: /private/var/db/stash/_.8k0vmU/Applications/Videos.app/Videos
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos.
*/

#import <UIKit/UIResponder.h>
#import <Videos/MPUExtrasContextDelegate.h>
#import <Videos/MPVideoOverlayDelegate.h>

@class UIWindow, MPUExtrasContext, NSMutableDictionary, VideosExtrasPlaybackContext, NSString;

@interface VideosAppDelegate : UIResponder <MPUExtrasContextDelegate, MPVideoOverlayDelegate> {

	UIWindow* _window;
	MPUExtrasContext* _extrasContext;
	NSMutableDictionary* _extrasPidToStoreIDMap;
	VideosExtrasPlaybackContext* _extrasPlaybackContext;

}

@property (readonly) unsigned long long hash; 
@property (readonly) Class superclass; 
@property (copy,readonly) NSString * description; 
@property (copy,readonly) NSString * debugDescription; 
-(void)launchExtrasWithURL:(id)arg1 storeID:(long long)arg2 buyParameters:(id)arg3 ;
-(void)_endDiscoveringMediaLibrariesIfNecessary;
-(void)launchExtrasWithContext:(id)arg1 ;
-(id)_mediaItemsFromMediaElement:(id)arg1 ;
-(void)launchExtrasForMediaItem:(id)arg1 ;
-(void)overlayTappedBackButton:(id)arg1 ;
-(id)init;
-(BOOL)application:(id)arg1 openURL:(id)arg2 sourceApplication:(id)arg3 annotation:(id)arg4 ;
-(void)applicationDidBecomeActive:(id)arg1 ;
-(void)applicationWillResignActive:(id)arg1 ;
-(void)applicationDidEnterBackground:(id)arg1 ;
-(void)applicationWillEnterForeground:(id)arg1 ;
-(BOOL)application:(id)arg1 shouldSaveApplicationState:(id)arg2 ;
-(BOOL)application:(id)arg1 shouldRestoreApplicationState:(id)arg2 ;
-(BOOL)application:(id)arg1 willFinishLaunchingWithOptions:(id)arg2 ;
-(BOOL)application:(id)arg1 didFinishLaunchingWithOptions:(id)arg2 ;
-(void)application:(id)arg1 didFinishLaunchingSuspendedWithOptions:(id)arg2 ;
-(void)application:(id)arg1 didReceiveLocalNotification:(id)arg2 ;
-(void)application:(id)arg1 willEncodeRestorableStateWithCoder:(id)arg2 ;
-(void)extrasRequestsMediaPlayback:(id)arg1 isBackground:(BOOL)arg2 ;
-(void)extrasRequestsPlaybackStop;
-(void)_availableMediaLibrariesDidChangeNotification:(id)arg1 ;
-(void)extrasRequestReloadWithContext:(id)arg1 ;
-(void)extrasContext:(id)arg1 hadFatalError:(id)arg2 ;
@end

