/*
* This header is generated by classdump-dyld 1.0
* on Tuesday, June 5, 2018 at 10:55:36 PM China Standard Time
* Operating System: Version 8.2 (Build 12D508)
* Image Source: /private/var/db/stash/_.8k0vmU/Applications/Videos.app/Videos
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos.
*/

#import <MPUFoundation/MPUDataSourceViewController.h>
#import <Videos/MPStoreDownloadManagerObserver.h>

@class MPUNotificationObserver, MPMediaItem, NSMutableArray, MPUItemOfferButton, VideosArtworkView, VideosDetailHeaderView, UIView, UISegmentedControl, MPUKeyValueObserver, MPUMediaDownloadObserver, VideosQueryDataSource, UIScrollView, NSString;

@interface VideosDetailViewController : MPUDataSourceViewController <MPStoreDownloadManagerObserver> {

	MPUNotificationObserver* _cloudButtonNotification;
	MPMediaItem* _item;
	NSMutableArray* _layoutConditionalConstraints;
	MPUItemOfferButton* _rightBarButtonCloudButton;
	BOOL _shouldFloatHeader;
	VideosArtworkView* _artworkView;
	VideosDetailHeaderView* _headerView;
	unsigned long long _selectedSection;
	unsigned long long _layoutMode;
	UIView* _containmentView;
	UIView* _headerContainmentView;
	UISegmentedControl* _segmentedControl;
	MPUKeyValueObserver* _artworkObserver;
	MPUMediaDownloadObserver* _downloadObserver;

}

@property (nonatomic,retain) VideosArtworkView * artworkView;                          //@synthesize artworkView=_artworkView - In the implementation block
@property (nonatomic,retain) VideosDetailHeaderView * headerView;                      //@synthesize headerView=_headerView - In the implementation block
@property (assign,nonatomic) BOOL shouldFloatHeader;                                   //@synthesize shouldFloatHeader=_shouldFloatHeader - In the implementation block
@property (nonatomic,readonly) VideosQueryDataSource * queryDataSource; 
@property (nonatomic,retain) MPMediaItem * item;                                       //@synthesize item=_item - In the implementation block
@property (assign,nonatomic) unsigned long long selectedSection;                       //@synthesize selectedSection=_selectedSection - In the implementation block
@property (nonatomic,readonly) unsigned long long numberOfSegments; 
@property (assign,nonatomic) unsigned long long layoutMode;                            //@synthesize layoutMode=_layoutMode - In the implementation block
@property (nonatomic,retain) UIView * containmentView;                                 //@synthesize containmentView=_containmentView - In the implementation block
@property (nonatomic,retain) UIView * headerContainmentView;                           //@synthesize headerContainmentView=_headerContainmentView - In the implementation block
@property (nonatomic,retain) UISegmentedControl * segmentedControl;                    //@synthesize segmentedControl=_segmentedControl - In the implementation block
@property (nonatomic,retain) MPUKeyValueObserver * artworkObserver;                    //@synthesize artworkObserver=_artworkObserver - In the implementation block
@property (nonatomic,readonly) UIScrollView * childContentScrollView; 
@property (nonatomic,retain) MPUMediaDownloadObserver * downloadObserver;              //@synthesize downloadObserver=_downloadObserver - In the implementation block
@property (readonly) unsigned long long hash; 
@property (readonly) Class superclass; 
@property (copy,readonly) NSString * description; 
@property (copy,readonly) NSString * debugDescription; 
+(BOOL)canShowPlayButton;
+(BOOL)shouldShowDownloadProgress;
-(void)setLayoutMode:(unsigned long long)arg1 ;
-(void)reloadSegments;
-(id)localizedTitleForSegment:(unsigned long long)arg1 ;
-(id)viewControllerForSegment:(unsigned long long)arg1 ;
-(void)_updateDownload;
-(void)setContainmentView:(UIView *)arg1 ;
-(UIView *)containmentView;
-(void)setHeaderContainmentView:(UIView *)arg1 ;
-(UIView *)headerContainmentView;
-(void)_cloudButtonPressed:(id)arg1 ;
-(void)_segmentValueChanged:(id)arg1 ;
-(void)setArtworkObserver:(MPUKeyValueObserver *)arg1 ;
-(void)_configurePlayButton;
-(BOOL)_setupDownloadObserver;
-(void)_configureViewsForOneColumnDisplay;
-(void)_configureViewsForTwoColumnDisplay;
-(void)_configureContainedScrollView;
-(UIScrollView *)childContentScrollView;
-(BOOL)shouldFloatHeader;
-(void)_clearDownloadObserver;
-(void)_installArtworkIntoHeaderIfNeeded;
-(void)setShouldFloatHeader:(BOOL)arg1 ;
-(BOOL)_mediaItemIsDownloadable:(id)arg1 ;
-(void)_updateForChangedDownloads:(id)arg1 ;
-(MPUKeyValueObserver *)artworkObserver;
-(void)_canShowCloudTracksDidChangeNotification:(id)arg1 ;
-(void)downloadManager:(id)arg1 didAddDownloads:(id)arg2 removeDownloads:(id)arg3 ;
-(void)downloadManager:(id)arg1 downloadDidFinish:(id)arg2 ;
-(void)downloadManager:(id)arg1 downloadDidProgress:(id)arg2 ;
-(void)dealloc;
-(void)reloadData;
-(void)encodeRestorableStateWithCoder:(id)arg1 ;
-(void)decodeRestorableStateWithCoder:(id)arg1 ;
-(void)traitCollectionDidChange:(id)arg1 ;
-(void)viewDidLayoutSubviews;
-(void)_updateContentInsets;
-(unsigned long long)selectedSection;
-(MPMediaItem *)item;
-(void)loadView;
-(void)viewWillAppear:(BOOL)arg1 ;
-(void)viewDidLoad;
-(void)updateViewConstraints;
-(void)setItem:(MPMediaItem *)arg1 ;
-(unsigned long long)numberOfSegments;
-(VideosDetailHeaderView *)headerView;
-(void)setHeaderView:(VideosDetailHeaderView *)arg1 ;
-(UISegmentedControl *)segmentedControl;
-(VideosArtworkView *)artworkView;
-(void)setArtworkView:(VideosArtworkView *)arg1 ;
-(MPUMediaDownloadObserver *)downloadObserver;
-(void)setDownloadObserver:(MPUMediaDownloadObserver *)arg1 ;
-(unsigned long long)layoutMode;
-(id)initWithDataSource:(id)arg1 ;
-(void)setSegmentedControl:(UISegmentedControl *)arg1 ;
-(void)setSelectedSection:(unsigned long long)arg1 ;
@end

