/*
* This header is generated by classdump-dyld 1.0
* on Tuesday, June 5, 2018 at 10:55:36 PM China Standard Time
* Operating System: Version 8.2 (Build 12D508)
* Image Source: /private/var/db/stash/_.8k0vmU/Applications/Videos.app/Videos
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos.
*/


@interface VideosFairplayStreaming : NSObject
+(BOOL)loaderShouldWaitForResourceLoadingRequest:(id)arg1 ;
+(BOOL)handleResourceLoadingRequest:(id)arg1 withLoader:(id)arg2 ;
+(id)_sharedInstance;
-(BOOL)_handleResourceLoadingRequest:(id)arg1 withLoader:(id)arg2 ;
-(id)_pastisCertificateURL;
-(id)_pastisKeyServerURL;
@end

