/*
* This header is generated by classdump-dyld 1.0
* on Tuesday, June 5, 2018 at 10:47:45 PM China Standard Time
* Operating System: Version 8.2 (Build 12D508)
* Image Source: /private/var/db/stash/_.8k0vmU/Applications/Reminders.app/Reminders
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos.
*/

#import <UIKit/UIViewController.h>
#import <UIKit/UITableViewDataSource.h>
#import <UIKit/UITableViewDelegate.h>
#import <UIKit/UISearchBarDelegate.h>
#import <Reminders/RemindersLocationPickerModelDelegate.h>
#import <Reminders/ABSearchOperationDelegate.h>
#import <Reminders/MKMapViewDelegate.h>
#import <Reminders/RemindersMapDragRadiusDelegate.h>

@protocol RemindersLocationEditorDelegate;
@class UISearchBar, UIView, UITableView, UISegmentedControl, MKMapView, RemindersMapDragRadiusView, NSMutableArray, NSString, EKStructuredLocation, RemindersLocationPickerModel, _MKLocationShifter, MKLocalSearch, NSArray, NSOperationQueue, ABSearchOperation;

@interface RemindersInlineLocEditViewController : UIViewController <UITableViewDataSource, UITableViewDelegate, UISearchBarDelegate, RemindersLocationPickerModelDelegate, ABSearchOperationDelegate, MKMapViewDelegate, RemindersMapDragRadiusDelegate> {

	UISearchBar* _searchBar;
	UIView* _dividerView;
	UITableView* _tableView;
	UISegmentedControl* _proximityControl;
	MKMapView* _mapView;
	RemindersMapDragRadiusView* _dragView;
	NSMutableArray* _constraints;
	NSString* _selectedLocationAddressString;
	EKStructuredLocation* _structuredLocation;
	long long _proximity;
	RemindersLocationPickerModel* _model;
	_MKLocationShifter* _locationShifter;
	BOOL _needsAddToRecents;
	NSMutableArray* _recents;
	MKLocalSearch* _locationSearch;
	NSArray* _locationSearchResults;
	NSOperationQueue* _abSearchQueue;
	ABSearchOperation* _abSearchOperation;
	NSMutableArray* _abSearchResults;
	NSMutableArray* _abAccumulatingResults;
	id<RemindersLocationEditorDelegate> _delegate;

}

@property (assign,nonatomic) id<RemindersLocationEditorDelegate> delegate;              //@synthesize delegate=_delegate - In the implementation block
@property (readonly) unsigned long long hash; 
@property (readonly) Class superclass; 
@property (copy,readonly) NSString * description; 
@property (copy,readonly) NSString * debugDescription; 
+(id)locationImage;
+(id)homeImage;
+(id)workImage;
+(id)pinImage;
-(BOOL)_allowsSearching;
-(void)setupMap;
-(void)displayLocation:(id)arg1 ;
-(BOOL)_hasLocation;
-(void)_proximityChanged:(id)arg1 ;
-(void)_updateLayoutContraints;
-(void)resetSearchResults;
-(void)radiusDidChange:(double)arg1 ;
-(id)initWithProximity:(long long)arg1 structuredLocation:(id)arg2 ;
-(void)searchOperation:(id)arg1 didFindMatches:(id)arg2 moreComing:(BOOL)arg3 ;
-(void)locationPickerModelDidUpdateCurrentLocation:(id)arg1 ;
-(void)locationPickerModelDidUpdateCustomLocation:(id)arg1 ;
-(void)locationPickerModel:(id)arg1 didUpdateMeCardItem:(long long)arg2 ;
-(void)locationPickerModelDidChangeSelection:(id)arg1 ;
-(void)locationPickerModel:(id)arg1 didEncounterError:(id)arg2 ;
-(void)updateRecents:(id)arg1 ;
-(id)CLLocationForDictionary:(id)arg1 ;
-(id)dictionaryForCLLocation:(id)arg1 ;
-(void)mapView:(id)arg1 regionWillChangeAnimated:(BOOL)arg2 ;
-(void)mapView:(id)arg1 regionDidChangeAnimated:(BOOL)arg2 ;
-(void)mapView:(id)arg1 didSelectAnnotationView:(id)arg2 ;
-(void)mapView:(id)arg1 didDeselectAnnotationView:(id)arg2 ;
-(id)mapView:(id)arg1 rendererForOverlay:(id)arg2 ;
-(void)dealloc;
-(void)setDelegate:(id<RemindersLocationEditorDelegate>)arg1 ;
-(void)tableView:(id)arg1 willDisplayCell:(id)arg2 forRowAtIndexPath:(id)arg3 ;
-(void)tableView:(id)arg1 didSelectRowAtIndexPath:(id)arg2 ;
-(long long)tableView:(id)arg1 numberOfRowsInSection:(long long)arg2 ;
-(id)tableView:(id)arg1 cellForRowAtIndexPath:(id)arg2 ;
-(id<RemindersLocationEditorDelegate>)delegate;
-(void)viewDidLayoutSubviews;
-(void)loadView;
-(void)viewDidAppear:(BOOL)arg1 ;
-(void)viewWillDisappear:(BOOL)arg1 ;
-(void)searchBar:(id)arg1 textDidChange:(id)arg2 ;
-(void)_updateUI;
@end

