/*
* This header is generated by classdump-dyld 1.0
* on Tuesday, June 5, 2018 at 10:47:45 PM China Standard Time
* Operating System: Version 8.2 (Build 12D508)
* Image Source: /private/var/db/stash/_.8k0vmU/Applications/Reminders.app/Reminders
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos.
*/

#import <Reminders/Reminders-Structs.h>
#import <UIKit/UIView.h>

@protocol RemindersMapDragRadiusDelegate, MKAnnotation, MKOverlay;
@class MKMapView, UIImageView, CAShapeLayer;

@interface RemindersMapDragRadiusView : UIView {

	BOOL _isDragging;
	BOOL _isMinimum;
	BOOL _isMaximum;
	id<RemindersMapDragRadiusDelegate> delegate;
	long long proximity;
	MKMapView* _mapView;
	UIImageView* _handleImageView;
	id<MKAnnotation> _annotation;
	id<MKOverlay> _overlay;
	CAShapeLayer* _shapeLayer;

}

@property (nonatomic,retain) MKMapView * mapView;                                      //@synthesize mapView=_mapView - In the implementation block
@property (assign,nonatomic) BOOL isDragging;                                          //@synthesize isDragging=_isDragging - In the implementation block
@property (assign,nonatomic) id<RemindersMapDragRadiusDelegate> delegate; 
@property (assign,nonatomic) long long proximity; 
@property (nonatomic,retain) UIImageView * handleImageView;                            //@synthesize handleImageView=_handleImageView - In the implementation block
@property (nonatomic,retain) id<MKAnnotation> annotation;                              //@synthesize annotation=_annotation - In the implementation block
@property (nonatomic,retain) id<MKOverlay> overlay;                                    //@synthesize overlay=_overlay - In the implementation block
@property (nonatomic,retain) CAShapeLayer * shapeLayer;                                //@synthesize shapeLayer=_shapeLayer - In the implementation block
@property (assign,nonatomic) BOOL isMinimum;                                           //@synthesize isMinimum=_isMinimum - In the implementation block
@property (assign,nonatomic) BOOL isMaximum;                                           //@synthesize isMaximum=_isMaximum - In the implementation block
-(void)addHandleForAnnotation:(id)arg1 withOverlay:(id)arg2 ;
-(void)setHandleImageView:(UIImageView *)arg1 ;
-(UIImageView *)handleImageView;
-(id)bezierPathWithEndPoint:(CGPoint)arg1 ;
-(id)shapeLayerWithEndPoint:(CGPoint)arg1 ;
-(void)popAnimateHandle;
-(void)animateHandleIn:(BOOL)arg1 ;
-(double)currentHandleDistanceNormalized;
-(BOOL)isMinimum;
-(double)minimumRadiusNormalized;
-(BOOL)isMaximum;
-(double)maximumRadiusNormalized;
-(BOOL)usesMetric;
-(void)setIsDragging:(BOOL)arg1 ;
-(CGPoint)minPoint;
-(CGPoint)maxPoint;
-(void)setIsMinimum:(BOOL)arg1 ;
-(void)setIsMaximum:(BOOL)arg1 ;
-(double)minimumInMeters;
-(double)currentHandleDistance;
-(void)resizeCircleAfterDelay;
-(double)feetToMeters:(double)arg1 ;
-(long long)proximity;
-(void)setProximity:(long long)arg1 ;
-(void)setMapView:(MKMapView *)arg1 ;
-(MKMapView *)mapView;
-(id)initWithFrame:(CGRect)arg1 ;
-(void)drawRect:(CGRect)arg1 ;
-(void)setDelegate:(id<RemindersMapDragRadiusDelegate>)arg1 ;
-(id)hitTest:(CGPoint)arg1 withEvent:(id)arg2 ;
-(BOOL)isDragging;
-(id<RemindersMapDragRadiusDelegate>)delegate;
-(void)touchesBegan:(id)arg1 withEvent:(id)arg2 ;
-(void)touchesMoved:(id)arg1 withEvent:(id)arg2 ;
-(void)touchesEnded:(id)arg1 withEvent:(id)arg2 ;
-(CGPoint)center;
-(CAShapeLayer *)shapeLayer;
-(id<MKAnnotation>)annotation;
-(void)setAnnotation:(id<MKAnnotation>)arg1 ;
-(void)setShapeLayer:(CAShapeLayer *)arg1 ;
-(id<MKOverlay>)overlay;
-(void)setOverlay:(id<MKOverlay>)arg1 ;
-(void)removeHandle:(BOOL)arg1 ;
@end

