/*
* This header is generated by classdump-dyld 1.0
* on Tuesday, June 5, 2018 at 10:47:45 PM China Standard Time
* Operating System: Version 8.2 (Build 12D508)
* Image Source: /private/var/db/stash/_.8k0vmU/Applications/Reminders.app/Reminders
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos.
*/


@class NSIndexPath;

@interface RemindersListScrollPosition : NSObject {

	NSIndexPath* _topVisibleIndexPath;
	double _deltaFromTop;

}

@property (nonatomic,retain) NSIndexPath * topVisibleIndexPath;              //@synthesize topVisibleIndexPath=_topVisibleIndexPath - In the implementation block
@property (assign,nonatomic) double deltaFromTop;                            //@synthesize deltaFromTop=_deltaFromTop - In the implementation block
-(NSIndexPath *)topVisibleIndexPath;
-(void)setTopVisibleIndexPath:(NSIndexPath *)arg1 ;
-(double)deltaFromTop;
-(void)setDeltaFromTop:(double)arg1 ;
-(id)description;
@end

