/*
* This header is generated by classdump-dyld 1.0
* on Tuesday, June 5, 2018 at 10:47:45 PM China Standard Time
* Operating System: Version 8.2 (Build 12D508)
* Image Source: /private/var/db/stash/_.8k0vmU/Applications/Reminders.app/Reminders
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos.
*/

#import <Reminders/Reminders-Structs.h>
#import <UIKit/UITableView.h>

@interface RemindersTableView : UITableView {

	BOOL _ignoreBoundsChange;

}

@property (assign) BOOL ignoreBoundsChange;              //@synthesize ignoreBoundsChange=_ignoreBoundsChange - In the implementation block
-(BOOL)ignoreBoundsChange;
-(void)setIgnoreBoundsChange:(BOOL)arg1 ;
-(void)setBounds:(CGRect)arg1 ;
-(BOOL)canBecomeFirstResponder;
@end

