/*
* This header is generated by classdump-dyld 1.0
* on Tuesday, June 5, 2018 at 12:52:29 PM China Standard Time
* Operating System: Version 8.2 (Build 12D508)
* Image Source: /private/var/db/stash/_.8k0vmU/Applications/MobileCal.app/MobileCal
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos.
*/

#import <UIKit/UIApplicationTestingDelegate.h>

@class NSMutableDictionary, ApplicationTest, CalendarModel, NSString, UIWindow;

@interface ApplicationTester : NSObject <UIApplicationTestingDelegate> {

	NSMutableDictionary* _testNamesToTestClasses;
	ApplicationTest* _currentlyRunningTest;
	CalendarModel* _model;

}

@property (nonatomic,readonly) NSString * extendedLaunchTestName; 
@property (readonly) unsigned long long hash; 
@property (readonly) Class superclass; 
@property (copy,readonly) NSString * description; 
@property (copy,readonly) NSString * debugDescription; 
@property (nonatomic,retain) UIWindow * window; 
+(BOOL)testingSessionStarted;
-(Class)_testClassForTestName:(id)arg1 ;
-(NSString *)extendedLaunchTestName;
-(BOOL)application:(id)arg1 runTest:(id)arg2 options:(id)arg3 ;
-(id)initWithModel:(id)arg1 ;
@end

