/*
* This header is generated by classdump-dyld 1.0
* on Tuesday, June 5, 2018 at 12:52:29 PM China Standard Time
* Operating System: Version 8.2 (Build 12D508)
* Image Source: /private/var/db/stash/_.8k0vmU/Applications/MobileCal.app/MobileCal
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos.
*/

#import <UIKit/UIViewController.h>

@protocol BlankViewControllerDelegate;
@class BlankView, NSObject;

@interface BlankViewController : UIViewController {

	BlankView* _blankView;
	NSObject*<BlankViewControllerDelegate> _dataSourceDelegate;

}

@property (assign,nonatomic) NSObject*<BlankViewControllerDelegate> dataSourceDelegate;              //@synthesize dataSourceDelegate=_dataSourceDelegate - In the implementation block
-(void)updateMessage;
-(void)loadView;
-(void)viewWillAppear:(BOOL)arg1 ;
-(void)viewDidAppear:(BOOL)arg1 ;
-(void)setDataSourceDelegate:(NSObject*<BlankViewControllerDelegate>)arg1 ;
-(NSObject*<BlankViewControllerDelegate>)dataSourceDelegate;
@end

