/*
* This header is generated by classdump-dyld 1.0
* on Tuesday, June 5, 2018 at 12:52:29 PM China Standard Time
* Operating System: Version 8.2 (Build 12D508)
* Image Source: /private/var/db/stash/_.8k0vmU/Applications/MobileCal.app/MobileCal
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos.
*/

#import <MobileCal/MainViewControllerContainer.h>

@class CompactWidthMonthViewController, CompactHeightMonthViewController, LargeMonthViewController;

@interface MonthViewContainerViewController : MainViewControllerContainer {

	CompactWidthMonthViewController* _compactWidthController;
	CompactHeightMonthViewController* _compactHeightController;
	LargeMonthViewController* _regularController;

}

@property (nonatomic,retain) CompactWidthMonthViewController * compactWidthController;                //@synthesize compactWidthController=_compactWidthController - In the implementation block
@property (nonatomic,retain) CompactHeightMonthViewController * compactHeightController;              //@synthesize compactHeightController=_compactHeightController - In the implementation block
@property (nonatomic,retain) LargeMonthViewController * regularController;                            //@synthesize regularController=_regularController - In the implementation block
-(id)currentChildViewController;
-(id)childViewControllerForCompactWidthRegularHeight;
-(id)pushedNextLevelMainViewControllerContainerAnimated:(BOOL)arg1 ;
-(id)childViewControllerForUnknownTraits;
-(id)childViewControllerForRegularWidthCompactHeight;
-(id)childViewControllerForRegularWidthRegularHeight;
-(Class)childViewControllerClassForTraits:(id)arg1 ;
-(BOOL)childViewControllerNeedsToBeInsettedFromNavigationElements;
-(CompactWidthMonthViewController *)compactWidthController;
-(void)setCompactWidthController:(CompactWidthMonthViewController *)arg1 ;
-(CompactHeightMonthViewController *)compactHeightController;
-(void)setCompactHeightController:(CompactHeightMonthViewController *)arg1 ;
-(LargeMonthViewController *)regularController;
-(void)setRegularController:(LargeMonthViewController *)arg1 ;
-(void)willTransitionToTraitCollection:(id)arg1 withTransitionCoordinator:(id)arg2 ;
@end

