/*
* This header is generated by classdump-dyld 1.0
* on Tuesday, June 5, 2018 at 12:52:29 PM China Standard Time
* Operating System: Version 8.2 (Build 12D508)
* Image Source: /private/var/db/stash/_.8k0vmU/Applications/MobileCal.app/MobileCal
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos.
*/

#import <MobileCal/MobileCal-Structs.h>
#import <UIKit/UIView.h>

@class _UINavigationControllerPalette, WeekDayInitialsHeaderView, DayNavigationViewController;

@interface PaletteView : UIView {

	_UINavigationControllerPalette* _containingPalette;
	WeekDayInitialsHeaderView* _dayInitialsHeaderView;
	BOOL _freezeSize;
	BOOL _weekdayHeaderVisible;
	BOOL _weekdayHeaderFillsHalfWidth;
	BOOL _useCustomDayFrames;
	DayNavigationViewController* _dayScrubberController;

}

@property (nonatomic,readonly) BOOL hasContent; 
@property (assign,nonatomic) BOOL freezeSize;                                                  //@synthesize freezeSize=_freezeSize - In the implementation block
@property (assign,nonatomic) BOOL weekdayHeaderVisible;                                        //@synthesize weekdayHeaderVisible=_weekdayHeaderVisible - In the implementation block
@property (assign,nonatomic) BOOL weekdayHeaderFillsHalfWidth;                                 //@synthesize weekdayHeaderFillsHalfWidth=_weekdayHeaderFillsHalfWidth - In the implementation block
@property (nonatomic,retain) DayNavigationViewController * dayScrubberController;              //@synthesize dayScrubberController=_dayScrubberController - In the implementation block
@property (assign,nonatomic) BOOL useCustomDayFrames;                                          //@synthesize useCustomDayFrames=_useCustomDayFrames - In the implementation block
-(void)layoutWithoutResizingPalette;
-(void)setDayHeaderFrames:(id)arg1 ;
-(void)setWeekdayHeaderVisible:(BOOL)arg1 ;
-(void)setWeekdayHeaderFillsHalfWidth:(BOOL)arg1 ;
-(void)setDayScrubberController:(DayNavigationViewController *)arg1 ;
-(void)setUseCustomDayFrames:(BOOL)arg1 ;
-(BOOL)useCustomDayFrames;
-(DayNavigationViewController *)dayScrubberController;
-(void)setFreezeSize:(BOOL)arg1 ;
-(id)initWithNavigationPalette:(id)arg1 ;
-(void)removeAllContent;
-(void)invalidateForWindowSizeParadigmChange;
-(double)sideMargin;
-(BOOL)weekdayHeaderVisible;
-(BOOL)freezeSize;
-(BOOL)weekdayHeaderFillsHalfWidth;
-(id)_generateWeekDayInitialsHeaderView;
-(void)dealloc;
-(void)layoutSubviews;
-(CGSize)sizeThatFits:(CGSize)arg1 ;
-(BOOL)hasContent;
-(void)_localeChanged:(id)arg1 ;
@end

