/*
* This header is generated by classdump-dyld 1.0
* on Wednesday, June 6, 2018 at 1:25:15 PM China Standard Time
* Operating System: Version 8.2 (Build 12D508)
* Image Source: /private/var/db/stash/_.8k0vmU/Applications/FaceTime.app/FaceTime
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos.
*/

#import <UIKit/UIViewController.h>
#import <UIKit/UITableViewDelegate.h>
#import <UIKit/UITableViewDataSource.h>
#import <FaceTime/PHFrecentCellDelegate.h>

@class UITableView, NSString;

@interface PHFrecentResultViewController : UIViewController <UITableViewDelegate, UITableViewDataSource, PHFrecentCellDelegate> {

	UITableView* _tableView;

}

@property (retain) UITableView * tableView;                         //@synthesize tableView=_tableView - In the implementation block
@property (readonly) unsigned long long hash; 
@property (readonly) Class superclass; 
@property (copy,readonly) NSString * description; 
@property (copy,readonly) NSString * debugDescription; 
-(BOOL)performDial:(id)arg1 audioOnlyCall:(BOOL)arg2 ;
-(void)dialResult:(id)arg1 audioOnlyCall:(BOOL)arg2 fromButton:(id)arg3 ;
-(id)additionalActionsForSearchResult:(id)arg1 ;
-(id)additionalActionsAlertTitleForSearchResult:(id)arg1 ;
-(void)_resetFrecentAlphaAndContentView;
-(void)dealloc;
-(long long)tableView:(id)arg1 numberOfRowsInSection:(long long)arg2 ;
-(id)tableView:(id)arg1 cellForRowAtIndexPath:(id)arg2 ;
-(unsigned long long)supportedInterfaceOrientations;
-(void)setTableView:(UITableView *)arg1 ;
-(void)viewDidLoad;
-(UITableView *)tableView;
@end

