/*
* This header is generated by classdump-dyld 1.0
* on Wednesday, June 6, 2018 at 1:25:15 PM China Standard Time
* Operating System: Version 8.2 (Build 12D508)
* Image Source: /private/var/db/stash/_.8k0vmU/Applications/FaceTime.app/FaceTime
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos.
*/

#import <FaceTime/FaceTime-Structs.h>
#import <UIKit/UINavigationController.h>
#import <FaceTime/PhoneTabViewController.h>

@protocol PhoneTabViewController;
@class UIViewController, NSString;

@interface PhoneNavigationController : UINavigationController <PhoneTabViewController> {

	UIViewController*<PhoneTabViewController> _rootController;

}

@property (readonly) unsigned long long hash; 
@property (readonly) Class superclass; 
@property (copy,readonly) NSString * description; 
@property (copy,readonly) NSString * debugDescription; 
+(id)tabBarIconImage;
+(id)tabBarIconImageSelected;
+(id)tabBarIconName;
+(int)tabViewType;
+(BOOL)_isViewSizeFullScreen:(id)arg1 inWindow:(id)arg2 ;
+(id)defaultPNGName;
+(SCD_Struct_Ph0)badge;
-(BOOL)shouldSnapshot;
-(void)prepareForSnapshot;
-(void)_updateRootViewController;
-(void)dealloc;
-(id)rootViewController;
-(void)presentViewController:(id)arg1 animated:(BOOL)arg2 completion:(/*^block*/id)arg3 ;
-(void)pushViewController:(id)arg1 animated:(BOOL)arg2 ;
-(id)initWithRootViewController:(id)arg1 ;
-(void)setViewControllers:(id)arg1 ;
-(void)handleURL:(id)arg1 ;
@end

