/*
* This header is generated by classdump-dyld 1.0
* on Wednesday, June 6, 2018 at 1:25:15 PM China Standard Time
* Operating System: Version 8.2 (Build 12D508)
* Image Source: /private/var/db/stash/_.8k0vmU/Applications/FaceTime.app/FaceTime
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos.
*/


@protocol UIActionSheetDelegate <NSObject>
@optional
-(void)actionSheet:(id)arg1 clickedButtonAtIndex:(long long)arg2;
-(void)actionSheetCancel:(id)arg1;
-(void)willPresentActionSheet:(id)arg1;
-(void)didPresentActionSheet:(id)arg1;
-(void)actionSheet:(id)arg1 willDismissWithButtonIndex:(long long)arg2;
-(void)actionSheet:(id)arg1 didDismissWithButtonIndex:(long long)arg2;

@end

